//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplicationPDV.bancoSQLite
{
    public static class ConnectionHelper
    {
        static Type[] persistentTypes = new Type[] {
            typeof(tb_ator),
            typeof(tb_categoria_produto),
            typeof(tb_certificado_digital),
            typeof(tb_clasCont1),
            typeof(tb_clasCont2),
            typeof(tb_codigo_produto),
            typeof(tb_cont),
            typeof(tb_contExt),
            typeof(tb_contExtGru),
            typeof(tb_contExtSec),
            typeof(tb_contExtSubGru),
            typeof(tb_contGru),
            typeof(tb_contSec),
            typeof(tb_contSubGru),
            typeof(tb_est),
            typeof(tb_estados_br),
            typeof(tb_forma_pagamento),
            typeof(tb_historico),
            typeof(tb_jornada),
            typeof(tb_marca_produto),
            typeof(tb_matriz),
            typeof(tb_movimentacao),
            typeof(tb_movimentacao_caixa),
            typeof(tb_movimentacao_impressao),
            typeof(tb_movimentacao_pagamento),
            typeof(tb_movimentacao_pagamento_parcela),
            typeof(tb_movimentacao_produto),
            typeof(tb_municipio),
            typeof(tb_ncm),
            typeof(tb_nfe),
            typeof(tb_nfe_enviada_filial),
            typeof(tb_pais),
            typeof(tb_pdv),
            typeof(tb_planCont),
            typeof(tb_produto),
            typeof(tb_produto_filial),
            typeof(tb_rede),
            typeof(tb_regioes_br),
            typeof(tb_relacao_produto_cadastro_XML),
            typeof(tb_resEventoNFe),
            typeof(tb_resposta_NFe),
            typeof(tb_secao_produto),
            typeof(tb_sub_forma_pagamento),
            typeof(tb_subcategoria_produto),
            typeof(tb_unidade_monetaria)
        };
        public static Type[] GetPersistentTypes()
        {
            Type[] copy = new Type[persistentTypes.Length];
            Array.Copy(persistentTypes, copy, persistentTypes.Length);
            return copy;
        }
        public static string ConnectionString { get { return System.Configuration.ConfigurationManager.ConnectionStrings["bancoSQLite"].ConnectionString; } }
        public static void Connect(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, bool threadSafe = false)
        {
            if (threadSafe)
            {
                var provider = XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
                var dictionary = new DevExpress.Xpo.Metadata.ReflectionDictionary();
                dictionary.GetDataStoreSchema(persistentTypes);
                XpoDefault.DataLayer = new ThreadSafeDataLayer(dictionary, provider);
            }
            else
            {
                XpoDefault.DataLayer = XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
            }
            XpoDefault.Session = null;
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, out IDisposable[] objectsToDisposeOnDisconnect)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption, out objectsToDisposeOnDisconnect);
        }
        public static IDataLayer GetDataLayer(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
        }
    }

}
