//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplicationPDV.bancoSQLite
{

    public partial class tb_contGru : XPLiteObject
    {
        long fid_contGru;
        [Key(AutoGenerate = true)]
        public long id_contGru
        {
            get { return fid_contGru; }
            set { SetPropertyValue<long>(nameof(id_contGru), ref fid_contGru, value); }
        }
        long fcg_contSec;
        public long cg_contSec
        {
            get { return fcg_contSec; }
            set { SetPropertyValue<long>(nameof(cg_contSec), ref fcg_contSec, value); }
        }
        DateTime fcg_dtCri;
        public DateTime cg_dtCri
        {
            get { return fcg_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(cg_dtCri), ref fcg_dtCri, value); }
        }
        DateTime fcg_dtAlt;
        public DateTime cg_dtAlt
        {
            get { return fcg_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(cg_dtAlt), ref fcg_dtAlt, value); }
        }
        DateTime fcg_dtAcs;
        public DateTime cg_dtAcs
        {
            get { return fcg_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(cg_dtAcs), ref fcg_dtAcs, value); }
        }
        string fcg_desc;
        [Size(60)]
        public string cg_desc
        {
            get { return fcg_desc; }
            set { SetPropertyValue<string>(nameof(cg_desc), ref fcg_desc, value); }
        }
        decimal fcg_canc;
        public decimal cg_canc
        {
            get { return fcg_canc; }
            set { SetPropertyValue<decimal>(nameof(cg_canc), ref fcg_canc, value); }
        }
        decimal fcg_conc;
        public decimal cg_conc
        {
            get { return fcg_conc; }
            set { SetPropertyValue<decimal>(nameof(cg_conc), ref fcg_conc, value); }
        }
        [Association(@"tb_contExtGruReferencestb_contGru")]
        public XPCollection<tb_contExtGru> tb_contExtGrus { get { return GetCollection<tb_contExtGru>(nameof(tb_contExtGrus)); } }
        [Association(@"tb_contSubGruReferencestb_contGru")]
        public XPCollection<tb_contSubGru> tb_contSubGrus { get { return GetCollection<tb_contSubGru>(nameof(tb_contSubGrus)); } }
    }

}
