//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplicationPDV.bancoSQLite
{

    public partial class tb_contExt : XPLiteObject
    {
        long fid_contExt;
        [Key(AutoGenerate = true)]
        public long id_contExt
        {
            get { return fid_contExt; }
            set { SetPropertyValue<long>(nameof(id_contExt), ref fid_contExt, value); }
        }
        decimal fce_deb;
        public decimal ce_deb
        {
            get { return fce_deb; }
            set { SetPropertyValue<decimal>(nameof(ce_deb), ref fce_deb, value); }
        }
        decimal fce_cred;
        public decimal ce_cred
        {
            get { return fce_cred; }
            set { SetPropertyValue<decimal>(nameof(ce_cred), ref fce_cred, value); }
        }
        DateTime fce_dtCri;
        public DateTime ce_dtCri
        {
            get { return fce_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(ce_dtCri), ref fce_dtCri, value); }
        }
        DateTime fce_dtAlt;
        public DateTime ce_dtAlt
        {
            get { return fce_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(ce_dtAlt), ref fce_dtAlt, value); }
        }
        DateTime fce_dtAcs;
        public DateTime ce_dtAcs
        {
            get { return fce_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(ce_dtAcs), ref fce_dtAcs, value); }
        }
        decimal fce_canc;
        public decimal ce_canc
        {
            get { return fce_canc; }
            set { SetPropertyValue<decimal>(nameof(ce_canc), ref fce_canc, value); }
        }
        decimal fce_conc;
        public decimal ce_conc
        {
            get { return fce_conc; }
            set { SetPropertyValue<decimal>(nameof(ce_conc), ref fce_conc, value); }
        }
        tb_cont ffk_tb_cont;
        [Association(@"tb_contExtReferencestb_cont")]
        public tb_cont fk_tb_cont
        {
            get { return ffk_tb_cont; }
            set { SetPropertyValue<tb_cont>(nameof(fk_tb_cont), ref ffk_tb_cont, value); }
        }
    }

}
