//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplicationPDV.bancoSQLite
{

    public partial class tb_est : XPLiteObject
    {
        long fid_est;
        [Key(AutoGenerate = true)]
        public long id_est
        {
            get { return fid_est; }
            set { SetPropertyValue<long>(nameof(id_est), ref fid_est, value); }
        }
        DateTime fes_dtCri;
        public DateTime es_dtCri
        {
            get { return fes_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(es_dtCri), ref fes_dtCri, value); }
        }
        DateTime fes_dtAlt;
        public DateTime es_dtAlt
        {
            get { return fes_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(es_dtAlt), ref fes_dtAlt, value); }
        }
        DateTime fes_dtAcs;
        public DateTime es_dtAcs
        {
            get { return fes_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(es_dtAcs), ref fes_dtAcs, value); }
        }
        string fes_dskCaption;
        [Size(64)]
        public string es_dskCaption
        {
            get { return fes_dskCaption; }
            set { SetPropertyValue<string>(nameof(es_dskCaption), ref fes_dskCaption, value); }
        }
        decimal fes_dskIndex;
        public decimal es_dskIndex
        {
            get { return fes_dskIndex; }
            set { SetPropertyValue<decimal>(nameof(es_dskIndex), ref fes_dskIndex, value); }
        }
        string fes_dskSerialNumber;
        [Size(128)]
        public string es_dskSerialNumber
        {
            get { return fes_dskSerialNumber; }
            set { SetPropertyValue<string>(nameof(es_dskSerialNumber), ref fes_dskSerialNumber, value); }
        }
        decimal fes_dskSignature;
        public decimal es_dskSignature
        {
            get { return fes_dskSignature; }
            set { SetPropertyValue<decimal>(nameof(es_dskSignature), ref fes_dskSignature, value); }
        }
        decimal fes_dskSize;
        public decimal es_dskSize
        {
            get { return fes_dskSize; }
            set { SetPropertyValue<decimal>(nameof(es_dskSize), ref fes_dskSize, value); }
        }
        string fes_dskStatus;
        [Size(10)]
        public string es_dskStatus
        {
            get { return fes_dskStatus; }
            set { SetPropertyValue<string>(nameof(es_dskStatus), ref fes_dskStatus, value); }
        }
        string fes_nicAdapterType;
        [Size(64)]
        public string es_nicAdapterType
        {
            get { return fes_nicAdapterType; }
            set { SetPropertyValue<string>(nameof(es_nicAdapterType), ref fes_nicAdapterType, value); }
        }
        decimal fes_nicAdapterTypeID;
        public decimal es_nicAdapterTypeID
        {
            get { return fes_nicAdapterTypeID; }
            set { SetPropertyValue<decimal>(nameof(es_nicAdapterTypeID), ref fes_nicAdapterTypeID, value); }
        }
        string fes_nicCaption;
        [Size(64)]
        public string es_nicCaption
        {
            get { return fes_nicCaption; }
            set { SetPropertyValue<string>(nameof(es_nicCaption), ref fes_nicCaption, value); }
        }
        string fes_nicDescription;
        [Size(128)]
        public string es_nicDescription
        {
            get { return fes_nicDescription; }
            set { SetPropertyValue<string>(nameof(es_nicDescription), ref fes_nicDescription, value); }
        }
        decimal fes_nicInterfaceIndex;
        public decimal es_nicInterfaceIndex
        {
            get { return fes_nicInterfaceIndex; }
            set { SetPropertyValue<decimal>(nameof(es_nicInterfaceIndex), ref fes_nicInterfaceIndex, value); }
        }
        string fes_nicMacAddress;
        [Size(32)]
        public string es_nicMacAddress
        {
            get { return fes_nicMacAddress; }
            set { SetPropertyValue<string>(nameof(es_nicMacAddress), ref fes_nicMacAddress, value); }
        }
        string fes_nicMacAddressVpn;
        [Size(32)]
        public string es_nicMacAddressVpn
        {
            get { return fes_nicMacAddressVpn; }
            set { SetPropertyValue<string>(nameof(es_nicMacAddressVpn), ref fes_nicMacAddressVpn, value); }
        }
        string fes_nicManufacturer;
        [Size(64)]
        public string es_nicManufacturer
        {
            get { return fes_nicManufacturer; }
            set { SetPropertyValue<string>(nameof(es_nicManufacturer), ref fes_nicManufacturer, value); }
        }
        string fes_nicName;
        [Size(128)]
        public string es_nicName
        {
            get { return fes_nicName; }
            set { SetPropertyValue<string>(nameof(es_nicName), ref fes_nicName, value); }
        }
        decimal fes_nicNetEnabled;
        public decimal es_nicNetEnabled
        {
            get { return fes_nicNetEnabled; }
            set { SetPropertyValue<decimal>(nameof(es_nicNetEnabled), ref fes_nicNetEnabled, value); }
        }
        decimal fes_nicSpeed;
        public decimal es_nicSpeed
        {
            get { return fes_nicSpeed; }
            set { SetPropertyValue<decimal>(nameof(es_nicSpeed), ref fes_nicSpeed, value); }
        }
        decimal fes_nicCfgDHCPEnabled;
        public decimal es_nicCfgDHCPEnabled
        {
            get { return fes_nicCfgDHCPEnabled; }
            set { SetPropertyValue<decimal>(nameof(es_nicCfgDHCPEnabled), ref fes_nicCfgDHCPEnabled, value); }
        }
        string fes_nicCfgDHCPServer;
        [Size(48)]
        public string es_nicCfgDHCPServer
        {
            get { return fes_nicCfgDHCPServer; }
            set { SetPropertyValue<string>(nameof(es_nicCfgDHCPServer), ref fes_nicCfgDHCPServer, value); }
        }
        string fes_nicCfgDNSDomain;
        [Size(255)]
        public string es_nicCfgDNSDomain
        {
            get { return fes_nicCfgDNSDomain; }
            set { SetPropertyValue<string>(nameof(es_nicCfgDNSDomain), ref fes_nicCfgDNSDomain, value); }
        }
        string fes_nicCfgIPAddress;
        [Size(SizeAttribute.Unlimited)]
        public string es_nicCfgIPAddress
        {
            get { return fes_nicCfgIPAddress; }
            set { SetPropertyValue<string>(nameof(es_nicCfgIPAddress), ref fes_nicCfgIPAddress, value); }
        }
        string fes_nicCfgIPAddressVpn;
        [Size(SizeAttribute.Unlimited)]
        public string es_nicCfgIPAddressVpn
        {
            get { return fes_nicCfgIPAddressVpn; }
            set { SetPropertyValue<string>(nameof(es_nicCfgIPAddressVpn), ref fes_nicCfgIPAddressVpn, value); }
        }
        decimal fes_nicCfgIPConnectionMetric;
        public decimal es_nicCfgIPConnectionMetric
        {
            get { return fes_nicCfgIPConnectionMetric; }
            set { SetPropertyValue<decimal>(nameof(es_nicCfgIPConnectionMetric), ref fes_nicCfgIPConnectionMetric, value); }
        }
        decimal fes_nicCfgIPEnabled;
        public decimal es_nicCfgIPEnabled
        {
            get { return fes_nicCfgIPEnabled; }
            set { SetPropertyValue<decimal>(nameof(es_nicCfgIPEnabled), ref fes_nicCfgIPEnabled, value); }
        }
        decimal fes_pcPgFlAllocatedBaseSize;
        public decimal es_pcPgFlAllocatedBaseSize
        {
            get { return fes_pcPgFlAllocatedBaseSize; }
            set { SetPropertyValue<decimal>(nameof(es_pcPgFlAllocatedBaseSize), ref fes_pcPgFlAllocatedBaseSize, value); }
        }
        decimal fes_pcPgFlCurrentUsage;
        public decimal es_pcPgFlCurrentUsage
        {
            get { return fes_pcPgFlCurrentUsage; }
            set { SetPropertyValue<decimal>(nameof(es_pcPgFlCurrentUsage), ref fes_pcPgFlCurrentUsage, value); }
        }
        decimal fes_pcPgFlPeakUsage;
        public decimal es_pcPgFlPeakUsage
        {
            get { return fes_pcPgFlPeakUsage; }
            set { SetPropertyValue<decimal>(nameof(es_pcPgFlPeakUsage), ref fes_pcPgFlPeakUsage, value); }
        }
        string fes_pcPowInstanceID;
        [Size(60)]
        public string es_pcPowInstanceID
        {
            get { return fes_pcPowInstanceID; }
            set { SetPropertyValue<string>(nameof(es_pcPowInstanceID), ref fes_pcPowInstanceID, value); }
        }
        string fes_pcPowElementName;
        [Size(60)]
        public string es_pcPowElementName
        {
            get { return fes_pcPowElementName; }
            set { SetPropertyValue<string>(nameof(es_pcPowElementName), ref fes_pcPowElementName, value); }
        }
        string fes_pcLdCaption;
        [Size(60)]
        public string es_pcLdCaption
        {
            get { return fes_pcLdCaption; }
            set { SetPropertyValue<string>(nameof(es_pcLdCaption), ref fes_pcLdCaption, value); }
        }
        decimal fes_pcLdCompressed;
        public decimal es_pcLdCompressed
        {
            get { return fes_pcLdCompressed; }
            set { SetPropertyValue<decimal>(nameof(es_pcLdCompressed), ref fes_pcLdCompressed, value); }
        }
        decimal fes_pcLdConfigManagerErrorCode;
        public decimal es_pcLdConfigManagerErrorCode
        {
            get { return fes_pcLdConfigManagerErrorCode; }
            set { SetPropertyValue<decimal>(nameof(es_pcLdConfigManagerErrorCode), ref fes_pcLdConfigManagerErrorCode, value); }
        }
        string fes_pcLdDeviceID;
        [Size(60)]
        public string es_pcLdDeviceID
        {
            get { return fes_pcLdDeviceID; }
            set { SetPropertyValue<string>(nameof(es_pcLdDeviceID), ref fes_pcLdDeviceID, value); }
        }
        decimal fes_pcLdDriveType;
        public decimal es_pcLdDriveType
        {
            get { return fes_pcLdDriveType; }
            set { SetPropertyValue<decimal>(nameof(es_pcLdDriveType), ref fes_pcLdDriveType, value); }
        }
        string fes_pcLdFileSystem;
        [Size(20)]
        public string es_pcLdFileSystem
        {
            get { return fes_pcLdFileSystem; }
            set { SetPropertyValue<string>(nameof(es_pcLdFileSystem), ref fes_pcLdFileSystem, value); }
        }
        decimal fes_pcLdFreeSpace;
        public decimal es_pcLdFreeSpace
        {
            get { return fes_pcLdFreeSpace; }
            set { SetPropertyValue<decimal>(nameof(es_pcLdFreeSpace), ref fes_pcLdFreeSpace, value); }
        }
        decimal fes_pcLdLastErrorCode;
        public decimal es_pcLdLastErrorCode
        {
            get { return fes_pcLdLastErrorCode; }
            set { SetPropertyValue<decimal>(nameof(es_pcLdLastErrorCode), ref fes_pcLdLastErrorCode, value); }
        }
        string fes_pcLdName;
        [Size(64)]
        public string es_pcLdName
        {
            get { return fes_pcLdName; }
            set { SetPropertyValue<string>(nameof(es_pcLdName), ref fes_pcLdName, value); }
        }
        decimal fes_pcLdSize;
        public decimal es_pcLdSize
        {
            get { return fes_pcLdSize; }
            set { SetPropertyValue<decimal>(nameof(es_pcLdSize), ref fes_pcLdSize, value); }
        }
        decimal fes_pcLdVolumeDirty;
        public decimal es_pcLdVolumeDirty
        {
            get { return fes_pcLdVolumeDirty; }
            set { SetPropertyValue<decimal>(nameof(es_pcLdVolumeDirty), ref fes_pcLdVolumeDirty, value); }
        }
        string fes_pcLdVolumeSerialNumber;
        [Size(60)]
        public string es_pcLdVolumeSerialNumber
        {
            get { return fes_pcLdVolumeSerialNumber; }
            set { SetPropertyValue<string>(nameof(es_pcLdVolumeSerialNumber), ref fes_pcLdVolumeSerialNumber, value); }
        }
        decimal fes_pcAutomaticManagedPagefile;
        public decimal es_pcAutomaticManagedPagefile
        {
            get { return fes_pcAutomaticManagedPagefile; }
            set { SetPropertyValue<decimal>(nameof(es_pcAutomaticManagedPagefile), ref fes_pcAutomaticManagedPagefile, value); }
        }
        decimal fes_pcAutomaticResetBootOption;
        public decimal es_pcAutomaticResetBootOption
        {
            get { return fes_pcAutomaticResetBootOption; }
            set { SetPropertyValue<decimal>(nameof(es_pcAutomaticResetBootOption), ref fes_pcAutomaticResetBootOption, value); }
        }
        decimal fes_pcAutomaticResetCapability;
        public decimal es_pcAutomaticResetCapability
        {
            get { return fes_pcAutomaticResetCapability; }
            set { SetPropertyValue<decimal>(nameof(es_pcAutomaticResetCapability), ref fes_pcAutomaticResetCapability, value); }
        }
        decimal fes_pcBootROMSupported;
        public decimal es_pcBootROMSupported
        {
            get { return fes_pcBootROMSupported; }
            set { SetPropertyValue<decimal>(nameof(es_pcBootROMSupported), ref fes_pcBootROMSupported, value); }
        }
        string fes_pcBootupState;
        [Size(50)]
        public string es_pcBootupState
        {
            get { return fes_pcBootupState; }
            set { SetPropertyValue<string>(nameof(es_pcBootupState), ref fes_pcBootupState, value); }
        }
        short fes_pcCurrentTimeZone;
        public short es_pcCurrentTimeZone
        {
            get { return fes_pcCurrentTimeZone; }
            set { SetPropertyValue<short>(nameof(es_pcCurrentTimeZone), ref fes_pcCurrentTimeZone, value); }
        }
        decimal fes_pcDaylightInEffect;
        public decimal es_pcDaylightInEffect
        {
            get { return fes_pcDaylightInEffect; }
            set { SetPropertyValue<decimal>(nameof(es_pcDaylightInEffect), ref fes_pcDaylightInEffect, value); }
        }
        string fes_pcDNSHostName;
        [Size(255)]
        public string es_pcDNSHostName
        {
            get { return fes_pcDNSHostName; }
            set { SetPropertyValue<string>(nameof(es_pcDNSHostName), ref fes_pcDNSHostName, value); }
        }
        decimal fes_pcDomainRole;
        public decimal es_pcDomainRole
        {
            get { return fes_pcDomainRole; }
            set { SetPropertyValue<decimal>(nameof(es_pcDomainRole), ref fes_pcDomainRole, value); }
        }
        decimal fes_pcEnableDaylightSavingsTime;
        public decimal es_pcEnableDaylightSavingsTime
        {
            get { return fes_pcEnableDaylightSavingsTime; }
            set { SetPropertyValue<decimal>(nameof(es_pcEnableDaylightSavingsTime), ref fes_pcEnableDaylightSavingsTime, value); }
        }
        decimal fes_pcHypervisorPresent;
        public decimal es_pcHypervisorPresent
        {
            get { return fes_pcHypervisorPresent; }
            set { SetPropertyValue<decimal>(nameof(es_pcHypervisorPresent), ref fes_pcHypervisorPresent, value); }
        }
        string fes_pcManufacturer;
        [Size(50)]
        public string es_pcManufacturer
        {
            get { return fes_pcManufacturer; }
            set { SetPropertyValue<string>(nameof(es_pcManufacturer), ref fes_pcManufacturer, value); }
        }
        decimal fes_pcNetworkServerModeEnabled;
        public decimal es_pcNetworkServerModeEnabled
        {
            get { return fes_pcNetworkServerModeEnabled; }
            set { SetPropertyValue<decimal>(nameof(es_pcNetworkServerModeEnabled), ref fes_pcNetworkServerModeEnabled, value); }
        }
        decimal fes_pcNumberOfLogicalProcessors;
        public decimal es_pcNumberOfLogicalProcessors
        {
            get { return fes_pcNumberOfLogicalProcessors; }
            set { SetPropertyValue<decimal>(nameof(es_pcNumberOfLogicalProcessors), ref fes_pcNumberOfLogicalProcessors, value); }
        }
        decimal fes_pcNumberOfProcessors;
        public decimal es_pcNumberOfProcessors
        {
            get { return fes_pcNumberOfProcessors; }
            set { SetPropertyValue<decimal>(nameof(es_pcNumberOfProcessors), ref fes_pcNumberOfProcessors, value); }
        }
        decimal fes_pcPCSystemType;
        public decimal es_pcPCSystemType
        {
            get { return fes_pcPCSystemType; }
            set { SetPropertyValue<decimal>(nameof(es_pcPCSystemType), ref fes_pcPCSystemType, value); }
        }
        decimal fes_pcTotalPhysicalMemory;
        public decimal es_pcTotalPhysicalMemory
        {
            get { return fes_pcTotalPhysicalMemory; }
            set { SetPropertyValue<decimal>(nameof(es_pcTotalPhysicalMemory), ref fes_pcTotalPhysicalMemory, value); }
        }
        string fes_pcUserName;
        [Size(255)]
        public string es_pcUserName
        {
            get { return fes_pcUserName; }
            set { SetPropertyValue<string>(nameof(es_pcUserName), ref fes_pcUserName, value); }
        }
        decimal fes_pcWakeUpType;
        public decimal es_pcWakeUpType
        {
            get { return fes_pcWakeUpType; }
            set { SetPropertyValue<decimal>(nameof(es_pcWakeUpType), ref fes_pcWakeUpType, value); }
        }
        string fes_biosCaption;
        [Size(64)]
        public string es_biosCaption
        {
            get { return fes_biosCaption; }
            set { SetPropertyValue<string>(nameof(es_biosCaption), ref fes_biosCaption, value); }
        }
        string fes_biosSerialNumber;
        [Size(64)]
        public string es_biosSerialNumber
        {
            get { return fes_biosSerialNumber; }
            set { SetPropertyValue<string>(nameof(es_biosSerialNumber), ref fes_biosSerialNumber, value); }
        }
        string fes_biosSMBIOSBIOSVersion;
        [Size(64)]
        public string es_biosSMBIOSBIOSVersion
        {
            get { return fes_biosSMBIOSBIOSVersion; }
            set { SetPropertyValue<string>(nameof(es_biosSMBIOSBIOSVersion), ref fes_biosSMBIOSBIOSVersion, value); }
        }
        string fes_biosSoftwareElementID;
        [Size(256)]
        public string es_biosSoftwareElementID
        {
            get { return fes_biosSoftwareElementID; }
            set { SetPropertyValue<string>(nameof(es_biosSoftwareElementID), ref fes_biosSoftwareElementID, value); }
        }
        string fes_boardManufacturer;
        [Size(256)]
        public string es_boardManufacturer
        {
            get { return fes_boardManufacturer; }
            set { SetPropertyValue<string>(nameof(es_boardManufacturer), ref fes_boardManufacturer, value); }
        }
        string fes_boardProduct;
        [Size(64)]
        public string es_boardProduct
        {
            get { return fes_boardProduct; }
            set { SetPropertyValue<string>(nameof(es_boardProduct), ref fes_boardProduct, value); }
        }
        string fes_boardSerialNumber;
        [Size(64)]
        public string es_boardSerialNumber
        {
            get { return fes_boardSerialNumber; }
            set { SetPropertyValue<string>(nameof(es_boardSerialNumber), ref fes_boardSerialNumber, value); }
        }
        string fes_boardStatus;
        [Size(10)]
        public string es_boardStatus
        {
            get { return fes_boardStatus; }
            set { SetPropertyValue<string>(nameof(es_boardStatus), ref fes_boardStatus, value); }
        }
        string fes_boardVersion;
        [Size(64)]
        public string es_boardVersion
        {
            get { return fes_boardVersion; }
            set { SetPropertyValue<string>(nameof(es_boardVersion), ref fes_boardVersion, value); }
        }
        string fes_pcOsBuildNumber;
        [Size(10)]
        public string es_pcOsBuildNumber
        {
            get { return fes_pcOsBuildNumber; }
            set { SetPropertyValue<string>(nameof(es_pcOsBuildNumber), ref fes_pcOsBuildNumber, value); }
        }
        string fes_pcOsCaption;
        [Size(64)]
        public string es_pcOsCaption
        {
            get { return fes_pcOsCaption; }
            set { SetPropertyValue<string>(nameof(es_pcOsCaption), ref fes_pcOsCaption, value); }
        }
        string fes_pcOsCodeSet;
        [Size(6)]
        public string es_pcOsCodeSet
        {
            get { return fes_pcOsCodeSet; }
            set { SetPropertyValue<string>(nameof(es_pcOsCodeSet), ref fes_pcOsCodeSet, value); }
        }
        string fes_pcOsCountryCode;
        [Size(256)]
        public string es_pcOsCountryCode
        {
            get { return fes_pcOsCountryCode; }
            set { SetPropertyValue<string>(nameof(es_pcOsCountryCode), ref fes_pcOsCountryCode, value); }
        }
        decimal fes_pcOsCurrentTimeZone;
        public decimal es_pcOsCurrentTimeZone
        {
            get { return fes_pcOsCurrentTimeZone; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsCurrentTimeZone), ref fes_pcOsCurrentTimeZone, value); }
        }
        decimal fes_pcOsFreePhysicalMemory;
        public decimal es_pcOsFreePhysicalMemory
        {
            get { return fes_pcOsFreePhysicalMemory; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsFreePhysicalMemory), ref fes_pcOsFreePhysicalMemory, value); }
        }
        decimal fes_pcOsFreeSpaceInPagingFiles;
        public decimal es_pcOsFreeSpaceInPagingFiles
        {
            get { return fes_pcOsFreeSpaceInPagingFiles; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsFreeSpaceInPagingFiles), ref fes_pcOsFreeSpaceInPagingFiles, value); }
        }
        decimal fes_pcOsFreeVirtualMemory;
        public decimal es_pcOsFreeVirtualMemory
        {
            get { return fes_pcOsFreeVirtualMemory; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsFreeVirtualMemory), ref fes_pcOsFreeVirtualMemory, value); }
        }
        DateTime fes_pcOsInstallDate;
        public DateTime es_pcOsInstallDate
        {
            get { return fes_pcOsInstallDate; }
            set { SetPropertyValue<DateTime>(nameof(es_pcOsInstallDate), ref fes_pcOsInstallDate, value); }
        }
        DateTime fes_pcOsLastBootUpTime;
        public DateTime es_pcOsLastBootUpTime
        {
            get { return fes_pcOsLastBootUpTime; }
            set { SetPropertyValue<DateTime>(nameof(es_pcOsLastBootUpTime), ref fes_pcOsLastBootUpTime, value); }
        }
        DateTime fes_pcOsLocalDateTime;
        public DateTime es_pcOsLocalDateTime
        {
            get { return fes_pcOsLocalDateTime; }
            set { SetPropertyValue<DateTime>(nameof(es_pcOsLocalDateTime), ref fes_pcOsLocalDateTime, value); }
        }
        string fes_pcOsLocale;
        [Size(6)]
        public string es_pcOsLocale
        {
            get { return fes_pcOsLocale; }
            set { SetPropertyValue<string>(nameof(es_pcOsLocale), ref fes_pcOsLocale, value); }
        }
        decimal fes_pcOsNumberOfProcesses;
        public decimal es_pcOsNumberOfProcesses
        {
            get { return fes_pcOsNumberOfProcesses; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsNumberOfProcesses), ref fes_pcOsNumberOfProcesses, value); }
        }
        decimal fes_pcOsNumberOfUsers;
        public decimal es_pcOsNumberOfUsers
        {
            get { return fes_pcOsNumberOfUsers; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsNumberOfUsers), ref fes_pcOsNumberOfUsers, value); }
        }
        decimal fes_pcOsOperatingSystemSKU;
        public decimal es_pcOsOperatingSystemSKU
        {
            get { return fes_pcOsOperatingSystemSKU; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsOperatingSystemSKU), ref fes_pcOsOperatingSystemSKU, value); }
        }
        string fes_pcOSArchitecture;
        [Size(10)]
        public string es_pcOSArchitecture
        {
            get { return fes_pcOSArchitecture; }
            set { SetPropertyValue<string>(nameof(es_pcOSArchitecture), ref fes_pcOSArchitecture, value); }
        }
        decimal fes_pcOSLanguage;
        public decimal es_pcOSLanguage
        {
            get { return fes_pcOSLanguage; }
            set { SetPropertyValue<decimal>(nameof(es_pcOSLanguage), ref fes_pcOSLanguage, value); }
        }
        decimal fes_pcOSProductSuite;
        public decimal es_pcOSProductSuite
        {
            get { return fes_pcOSProductSuite; }
            set { SetPropertyValue<decimal>(nameof(es_pcOSProductSuite), ref fes_pcOSProductSuite, value); }
        }
        decimal fes_pcOsPortableOperatingSystem;
        public decimal es_pcOsPortableOperatingSystem
        {
            get { return fes_pcOsPortableOperatingSystem; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsPortableOperatingSystem), ref fes_pcOsPortableOperatingSystem, value); }
        }
        decimal fes_pcOsPrimary;
        public decimal es_pcOsPrimary
        {
            get { return fes_pcOsPrimary; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsPrimary), ref fes_pcOsPrimary, value); }
        }
        decimal fes_pcOsProductType;
        public decimal es_pcOsProductType
        {
            get { return fes_pcOsProductType; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsProductType), ref fes_pcOsProductType, value); }
        }
        string fes_pcOsRegisteredUser;
        public string es_pcOsRegisteredUser
        {
            get { return fes_pcOsRegisteredUser; }
            set { SetPropertyValue<string>(nameof(es_pcOsRegisteredUser), ref fes_pcOsRegisteredUser, value); }
        }
        string fes_pcOsSerialNumber;
        [Size(50)]
        public string es_pcOsSerialNumber
        {
            get { return fes_pcOsSerialNumber; }
            set { SetPropertyValue<string>(nameof(es_pcOsSerialNumber), ref fes_pcOsSerialNumber, value); }
        }
        decimal fes_pcOsServicePackMajorVersion;
        public decimal es_pcOsServicePackMajorVersion
        {
            get { return fes_pcOsServicePackMajorVersion; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsServicePackMajorVersion), ref fes_pcOsServicePackMajorVersion, value); }
        }
        decimal fes_pcOsServicePackMinorVersion;
        public decimal es_pcOsServicePackMinorVersion
        {
            get { return fes_pcOsServicePackMinorVersion; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsServicePackMinorVersion), ref fes_pcOsServicePackMinorVersion, value); }
        }
        decimal fes_pcOsSizeStoredInPagingFiles;
        public decimal es_pcOsSizeStoredInPagingFiles
        {
            get { return fes_pcOsSizeStoredInPagingFiles; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsSizeStoredInPagingFiles), ref fes_pcOsSizeStoredInPagingFiles, value); }
        }
        decimal fes_pcOsSuiteMask;
        public decimal es_pcOsSuiteMask
        {
            get { return fes_pcOsSuiteMask; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsSuiteMask), ref fes_pcOsSuiteMask, value); }
        }
        string fes_pcOsSystemDrive;
        [Size(2)]
        public string es_pcOsSystemDrive
        {
            get { return fes_pcOsSystemDrive; }
            set { SetPropertyValue<string>(nameof(es_pcOsSystemDrive), ref fes_pcOsSystemDrive, value); }
        }
        decimal fes_pcOsTotalSwapSpaceSize;
        public decimal es_pcOsTotalSwapSpaceSize
        {
            get { return fes_pcOsTotalSwapSpaceSize; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsTotalSwapSpaceSize), ref fes_pcOsTotalSwapSpaceSize, value); }
        }
        decimal fes_pcOsTotalVirtualMemorySize;
        public decimal es_pcOsTotalVirtualMemorySize
        {
            get { return fes_pcOsTotalVirtualMemorySize; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsTotalVirtualMemorySize), ref fes_pcOsTotalVirtualMemorySize, value); }
        }
        decimal fes_pcOsTotalVisibleMemorySize;
        public decimal es_pcOsTotalVisibleMemorySize
        {
            get { return fes_pcOsTotalVisibleMemorySize; }
            set { SetPropertyValue<decimal>(nameof(es_pcOsTotalVisibleMemorySize), ref fes_pcOsTotalVisibleMemorySize, value); }
        }
        string fes_pcOsVersion;
        [Size(20)]
        public string es_pcOsVersion
        {
            get { return fes_pcOsVersion; }
            set { SetPropertyValue<string>(nameof(es_pcOsVersion), ref fes_pcOsVersion, value); }
        }
        string fes_procHandle;
        [Size(256)]
        public string es_procHandle
        {
            get { return fes_procHandle; }
            set { SetPropertyValue<string>(nameof(es_procHandle), ref fes_procHandle, value); }
        }
        decimal fes_procHandleCount;
        public decimal es_procHandleCount
        {
            get { return fes_procHandleCount; }
            set { SetPropertyValue<decimal>(nameof(es_procHandleCount), ref fes_procHandleCount, value); }
        }
        decimal fes_procKernelModeTime;
        public decimal es_procKernelModeTime
        {
            get { return fes_procKernelModeTime; }
            set { SetPropertyValue<decimal>(nameof(es_procKernelModeTime), ref fes_procKernelModeTime, value); }
        }
        decimal fes_procOtherOperationCount;
        public decimal es_procOtherOperationCount
        {
            get { return fes_procOtherOperationCount; }
            set { SetPropertyValue<decimal>(nameof(es_procOtherOperationCount), ref fes_procOtherOperationCount, value); }
        }
        decimal fes_procOtherTransferCount;
        public decimal es_procOtherTransferCount
        {
            get { return fes_procOtherTransferCount; }
            set { SetPropertyValue<decimal>(nameof(es_procOtherTransferCount), ref fes_procOtherTransferCount, value); }
        }
        decimal fes_procPageFaults;
        public decimal es_procPageFaults
        {
            get { return fes_procPageFaults; }
            set { SetPropertyValue<decimal>(nameof(es_procPageFaults), ref fes_procPageFaults, value); }
        }
        decimal fes_procPageFileUsage;
        public decimal es_procPageFileUsage
        {
            get { return fes_procPageFileUsage; }
            set { SetPropertyValue<decimal>(nameof(es_procPageFileUsage), ref fes_procPageFileUsage, value); }
        }
        decimal fes_procPeakPageFileUsage;
        public decimal es_procPeakPageFileUsage
        {
            get { return fes_procPeakPageFileUsage; }
            set { SetPropertyValue<decimal>(nameof(es_procPeakPageFileUsage), ref fes_procPeakPageFileUsage, value); }
        }
        decimal fes_procPeakVirtualSize;
        public decimal es_procPeakVirtualSize
        {
            get { return fes_procPeakVirtualSize; }
            set { SetPropertyValue<decimal>(nameof(es_procPeakVirtualSize), ref fes_procPeakVirtualSize, value); }
        }
        decimal fes_procPeakWorkingSetSize;
        public decimal es_procPeakWorkingSetSize
        {
            get { return fes_procPeakWorkingSetSize; }
            set { SetPropertyValue<decimal>(nameof(es_procPeakWorkingSetSize), ref fes_procPeakWorkingSetSize, value); }
        }
        decimal fes_procPriority;
        public decimal es_procPriority
        {
            get { return fes_procPriority; }
            set { SetPropertyValue<decimal>(nameof(es_procPriority), ref fes_procPriority, value); }
        }
        decimal fes_procPrivatePageCount;
        public decimal es_procPrivatePageCount
        {
            get { return fes_procPrivatePageCount; }
            set { SetPropertyValue<decimal>(nameof(es_procPrivatePageCount), ref fes_procPrivatePageCount, value); }
        }
        decimal fes_procProcessId;
        public decimal es_procProcessId
        {
            get { return fes_procProcessId; }
            set { SetPropertyValue<decimal>(nameof(es_procProcessId), ref fes_procProcessId, value); }
        }
        decimal fes_procReadOperationCount;
        public decimal es_procReadOperationCount
        {
            get { return fes_procReadOperationCount; }
            set { SetPropertyValue<decimal>(nameof(es_procReadOperationCount), ref fes_procReadOperationCount, value); }
        }
        decimal fes_procReadTransferCount;
        public decimal es_procReadTransferCount
        {
            get { return fes_procReadTransferCount; }
            set { SetPropertyValue<decimal>(nameof(es_procReadTransferCount), ref fes_procReadTransferCount, value); }
        }
        decimal fes_procThreadCount;
        public decimal es_procThreadCount
        {
            get { return fes_procThreadCount; }
            set { SetPropertyValue<decimal>(nameof(es_procThreadCount), ref fes_procThreadCount, value); }
        }
        decimal fes_procUserModeTime;
        public decimal es_procUserModeTime
        {
            get { return fes_procUserModeTime; }
            set { SetPropertyValue<decimal>(nameof(es_procUserModeTime), ref fes_procUserModeTime, value); }
        }
        decimal fes_procVirtualSize;
        public decimal es_procVirtualSize
        {
            get { return fes_procVirtualSize; }
            set { SetPropertyValue<decimal>(nameof(es_procVirtualSize), ref fes_procVirtualSize, value); }
        }
        decimal fes_procWorkingSetSize;
        public decimal es_procWorkingSetSize
        {
            get { return fes_procWorkingSetSize; }
            set { SetPropertyValue<decimal>(nameof(es_procWorkingSetSize), ref fes_procWorkingSetSize, value); }
        }
        decimal fes_procWriteOperationCount;
        public decimal es_procWriteOperationCount
        {
            get { return fes_procWriteOperationCount; }
            set { SetPropertyValue<decimal>(nameof(es_procWriteOperationCount), ref fes_procWriteOperationCount, value); }
        }
        decimal fes_procWriteTransferCount;
        public decimal es_procWriteTransferCount
        {
            get { return fes_procWriteTransferCount; }
            set { SetPropertyValue<decimal>(nameof(es_procWriteTransferCount), ref fes_procWriteTransferCount, value); }
        }
        decimal fes_pcPrcAddressWidth;
        public decimal es_pcPrcAddressWidth
        {
            get { return fes_pcPrcAddressWidth; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcAddressWidth), ref fes_pcPrcAddressWidth, value); }
        }
        decimal fes_pcPrcArchitecture;
        public decimal es_pcPrcArchitecture
        {
            get { return fes_pcPrcArchitecture; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcArchitecture), ref fes_pcPrcArchitecture, value); }
        }
        decimal fes_pcPrcAvailability;
        public decimal es_pcPrcAvailability
        {
            get { return fes_pcPrcAvailability; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcAvailability), ref fes_pcPrcAvailability, value); }
        }
        string fes_pcPrcCaption;
        [Size(64)]
        public string es_pcPrcCaption
        {
            get { return fes_pcPrcCaption; }
            set { SetPropertyValue<string>(nameof(es_pcPrcCaption), ref fes_pcPrcCaption, value); }
        }
        decimal fes_pcPrcCharacteristics;
        public decimal es_pcPrcCharacteristics
        {
            get { return fes_pcPrcCharacteristics; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcCharacteristics), ref fes_pcPrcCharacteristics, value); }
        }
        decimal fes_pcPrcConfigManagerErrorCode;
        public decimal es_pcPrcConfigManagerErrorCode
        {
            get { return fes_pcPrcConfigManagerErrorCode; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcConfigManagerErrorCode), ref fes_pcPrcConfigManagerErrorCode, value); }
        }
        decimal fes_pcPrcConfigManagerUserConfig;
        public decimal es_pcPrcConfigManagerUserConfig
        {
            get { return fes_pcPrcConfigManagerUserConfig; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcConfigManagerUserConfig), ref fes_pcPrcConfigManagerUserConfig, value); }
        }
        decimal fes_pcPrcCpuStatus;
        public decimal es_pcPrcCpuStatus
        {
            get { return fes_pcPrcCpuStatus; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcCpuStatus), ref fes_pcPrcCpuStatus, value); }
        }
        decimal fes_pcPrcCurrentClockSpeed;
        public decimal es_pcPrcCurrentClockSpeed
        {
            get { return fes_pcPrcCurrentClockSpeed; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcCurrentClockSpeed), ref fes_pcPrcCurrentClockSpeed, value); }
        }
        decimal fes_pcPrcCurrentVoltage;
        public decimal es_pcPrcCurrentVoltage
        {
            get { return fes_pcPrcCurrentVoltage; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcCurrentVoltage), ref fes_pcPrcCurrentVoltage, value); }
        }
        decimal fes_pcPrcDataWidth;
        public decimal es_pcPrcDataWidth
        {
            get { return fes_pcPrcDataWidth; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcDataWidth), ref fes_pcPrcDataWidth, value); }
        }
        decimal fes_pcPrcExtClock;
        public decimal es_pcPrcExtClock
        {
            get { return fes_pcPrcExtClock; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcExtClock), ref fes_pcPrcExtClock, value); }
        }
        decimal fes_pcPrcFamily;
        public decimal es_pcPrcFamily
        {
            get { return fes_pcPrcFamily; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcFamily), ref fes_pcPrcFamily, value); }
        }
        decimal fes_pcPrcL2CacheSize;
        public decimal es_pcPrcL2CacheSize
        {
            get { return fes_pcPrcL2CacheSize; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcL2CacheSize), ref fes_pcPrcL2CacheSize, value); }
        }
        decimal fes_pcPrcL2CacheSpeed;
        public decimal es_pcPrcL2CacheSpeed
        {
            get { return fes_pcPrcL2CacheSpeed; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcL2CacheSpeed), ref fes_pcPrcL2CacheSpeed, value); }
        }
        decimal fes_pcPrcL3CacheSize;
        public decimal es_pcPrcL3CacheSize
        {
            get { return fes_pcPrcL3CacheSize; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcL3CacheSize), ref fes_pcPrcL3CacheSize, value); }
        }
        decimal fes_pcPrcL3CacheSpeed;
        public decimal es_pcPrcL3CacheSpeed
        {
            get { return fes_pcPrcL3CacheSpeed; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcL3CacheSpeed), ref fes_pcPrcL3CacheSpeed, value); }
        }
        decimal fes_pcPrcLevel;
        public decimal es_pcPrcLevel
        {
            get { return fes_pcPrcLevel; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcLevel), ref fes_pcPrcLevel, value); }
        }
        decimal fes_pcPrcLoadPercentage;
        public decimal es_pcPrcLoadPercentage
        {
            get { return fes_pcPrcLoadPercentage; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcLoadPercentage), ref fes_pcPrcLoadPercentage, value); }
        }
        decimal fes_pcPrcMaxClockSpeed;
        public decimal es_pcPrcMaxClockSpeed
        {
            get { return fes_pcPrcMaxClockSpeed; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcMaxClockSpeed), ref fes_pcPrcMaxClockSpeed, value); }
        }
        string fes_pcPrcName;
        public string es_pcPrcName
        {
            get { return fes_pcPrcName; }
            set { SetPropertyValue<string>(nameof(es_pcPrcName), ref fes_pcPrcName, value); }
        }
        decimal fes_pcPrcNumberOfCores;
        public decimal es_pcPrcNumberOfCores
        {
            get { return fes_pcPrcNumberOfCores; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcNumberOfCores), ref fes_pcPrcNumberOfCores, value); }
        }
        decimal fes_pcPrcNumberOfEnabledCore;
        public decimal es_pcPrcNumberOfEnabledCore
        {
            get { return fes_pcPrcNumberOfEnabledCore; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcNumberOfEnabledCore), ref fes_pcPrcNumberOfEnabledCore, value); }
        }
        decimal fes_pcPrcNumberOfLogicalProcessors;
        public decimal es_pcPrcNumberOfLogicalProcessors
        {
            get { return fes_pcPrcNumberOfLogicalProcessors; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcNumberOfLogicalProcessors), ref fes_pcPrcNumberOfLogicalProcessors, value); }
        }
        decimal fes_pcPrcPowerManagementSupported;
        public decimal es_pcPrcPowerManagementSupported
        {
            get { return fes_pcPrcPowerManagementSupported; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcPowerManagementSupported), ref fes_pcPrcPowerManagementSupported, value); }
        }
        string fes_pcPrcProcessorId;
        public string es_pcPrcProcessorId
        {
            get { return fes_pcPrcProcessorId; }
            set { SetPropertyValue<string>(nameof(es_pcPrcProcessorId), ref fes_pcPrcProcessorId, value); }
        }
        decimal fes_pcPrcProcessorType;
        public decimal es_pcPrcProcessorType
        {
            get { return fes_pcPrcProcessorType; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcProcessorType), ref fes_pcPrcProcessorType, value); }
        }
        decimal fes_pcPrcRevision;
        public decimal es_pcPrcRevision
        {
            get { return fes_pcPrcRevision; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcRevision), ref fes_pcPrcRevision, value); }
        }
        decimal fes_pcPrcSecondLevelAddressTranslationExtensions;
        public decimal es_pcPrcSecondLevelAddressTranslationExtensions
        {
            get { return fes_pcPrcSecondLevelAddressTranslationExtensions; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcSecondLevelAddressTranslationExtensions), ref fes_pcPrcSecondLevelAddressTranslationExtensions, value); }
        }
        string fes_pcPrcStatus;
        [Size(10)]
        public string es_pcPrcStatus
        {
            get { return fes_pcPrcStatus; }
            set { SetPropertyValue<string>(nameof(es_pcPrcStatus), ref fes_pcPrcStatus, value); }
        }
        decimal fes_pcPrcStatusInfo;
        public decimal es_pcPrcStatusInfo
        {
            get { return fes_pcPrcStatusInfo; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcStatusInfo), ref fes_pcPrcStatusInfo, value); }
        }
        string fes_pcPrcSystemName;
        [Size(255)]
        public string es_pcPrcSystemName
        {
            get { return fes_pcPrcSystemName; }
            set { SetPropertyValue<string>(nameof(es_pcPrcSystemName), ref fes_pcPrcSystemName, value); }
        }
        decimal fes_pcPrcThreadCount;
        public decimal es_pcPrcThreadCount
        {
            get { return fes_pcPrcThreadCount; }
            set { SetPropertyValue<decimal>(nameof(es_pcPrcThreadCount), ref fes_pcPrcThreadCount, value); }
        }
        decimal fes_gpuAdapterRAM;
        public decimal es_gpuAdapterRAM
        {
            get { return fes_gpuAdapterRAM; }
            set { SetPropertyValue<decimal>(nameof(es_gpuAdapterRAM), ref fes_gpuAdapterRAM, value); }
        }
        decimal fes_gpuAvailability;
        public decimal es_gpuAvailability
        {
            get { return fes_gpuAvailability; }
            set { SetPropertyValue<decimal>(nameof(es_gpuAvailability), ref fes_gpuAvailability, value); }
        }
        decimal fes_gpuConfigManagerErrorCode;
        public decimal es_gpuConfigManagerErrorCode
        {
            get { return fes_gpuConfigManagerErrorCode; }
            set { SetPropertyValue<decimal>(nameof(es_gpuConfigManagerErrorCode), ref fes_gpuConfigManagerErrorCode, value); }
        }
        decimal fes_gpuCurrentBitsPerPixel;
        public decimal es_gpuCurrentBitsPerPixel
        {
            get { return fes_gpuCurrentBitsPerPixel; }
            set { SetPropertyValue<decimal>(nameof(es_gpuCurrentBitsPerPixel), ref fes_gpuCurrentBitsPerPixel, value); }
        }
        decimal fes_gpuCurrentHorizontalResolution;
        public decimal es_gpuCurrentHorizontalResolution
        {
            get { return fes_gpuCurrentHorizontalResolution; }
            set { SetPropertyValue<decimal>(nameof(es_gpuCurrentHorizontalResolution), ref fes_gpuCurrentHorizontalResolution, value); }
        }
        decimal fes_gpuCurrentNumberOfColors;
        public decimal es_gpuCurrentNumberOfColors
        {
            get { return fes_gpuCurrentNumberOfColors; }
            set { SetPropertyValue<decimal>(nameof(es_gpuCurrentNumberOfColors), ref fes_gpuCurrentNumberOfColors, value); }
        }
        decimal fes_gpuCurrentRefreshRate;
        public decimal es_gpuCurrentRefreshRate
        {
            get { return fes_gpuCurrentRefreshRate; }
            set { SetPropertyValue<decimal>(nameof(es_gpuCurrentRefreshRate), ref fes_gpuCurrentRefreshRate, value); }
        }
        decimal fes_gpuCurrentScanMode;
        public decimal es_gpuCurrentScanMode
        {
            get { return fes_gpuCurrentScanMode; }
            set { SetPropertyValue<decimal>(nameof(es_gpuCurrentScanMode), ref fes_gpuCurrentScanMode, value); }
        }
        decimal fes_gpuCurrentVerticalResolution;
        public decimal es_gpuCurrentVerticalResolution
        {
            get { return fes_gpuCurrentVerticalResolution; }
            set { SetPropertyValue<decimal>(nameof(es_gpuCurrentVerticalResolution), ref fes_gpuCurrentVerticalResolution, value); }
        }
        decimal fes_gpuDitherType;
        public decimal es_gpuDitherType
        {
            get { return fes_gpuDitherType; }
            set { SetPropertyValue<decimal>(nameof(es_gpuDitherType), ref fes_gpuDitherType, value); }
        }
        string fes_gpuDriverVersion;
        [Size(50)]
        public string es_gpuDriverVersion
        {
            get { return fes_gpuDriverVersion; }
            set { SetPropertyValue<string>(nameof(es_gpuDriverVersion), ref fes_gpuDriverVersion, value); }
        }
        string fes_gpuStatus;
        [Size(10)]
        public string es_gpuStatus
        {
            get { return fes_gpuStatus; }
            set { SetPropertyValue<string>(nameof(es_gpuStatus), ref fes_gpuStatus, value); }
        }
        string fes_gpuVideoProcessor;
        public string es_gpuVideoProcessor
        {
            get { return fes_gpuVideoProcessor; }
            set { SetPropertyValue<string>(nameof(es_gpuVideoProcessor), ref fes_gpuVideoProcessor, value); }
        }
        tb_marca_produto ffk_tb_matriz;
        [Association(@"tb_estReferencestb_marca_produto")]
        public tb_marca_produto fk_tb_matriz
        {
            get { return ffk_tb_matriz; }
            set { SetPropertyValue<tb_marca_produto>(nameof(fk_tb_matriz), ref ffk_tb_matriz, value); }
        }
    }

}
