//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplicationPDV.bancoSQLite
{

    public partial class tb_jornada : XPLiteObject
    {
        long fid_jornada;
        [Key(AutoGenerate = true)]
        public long id_jornada
        {
            get { return fid_jornada; }
            set { SetPropertyValue<long>(nameof(id_jornada), ref fid_jornada, value); }
        }
        DateTime fjo_dtCri;
        public DateTime jo_dtCri
        {
            get { return fjo_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(jo_dtCri), ref fjo_dtCri, value); }
        }
        DateTime fjo_dtAlt;
        public DateTime jo_dtAlt
        {
            get { return fjo_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(jo_dtAlt), ref fjo_dtAlt, value); }
        }
        DateTime fjo_dtAcs;
        public DateTime jo_dtAcs
        {
            get { return fjo_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(jo_dtAcs), ref fjo_dtAcs, value); }
        }
        decimal fjo_desat;
        public decimal jo_desat
        {
            get { return fjo_desat; }
            set { SetPropertyValue<decimal>(nameof(jo_desat), ref fjo_desat, value); }
        }
        long fjo_numSeq;
        public long jo_numSeq
        {
            get { return fjo_numSeq; }
            set { SetPropertyValue<long>(nameof(jo_numSeq), ref fjo_numSeq, value); }
        }
        decimal fjo_aberta;
        public decimal jo_aberta
        {
            get { return fjo_aberta; }
            set { SetPropertyValue<decimal>(nameof(jo_aberta), ref fjo_aberta, value); }
        }
        decimal fjo_canc;
        public decimal jo_canc
        {
            get { return fjo_canc; }
            set { SetPropertyValue<decimal>(nameof(jo_canc), ref fjo_canc, value); }
        }
        tb_pdv ffk_tb_pdv;
        [Association(@"tb_jornadaReferencestb_pdv")]
        public tb_pdv fk_tb_pdv
        {
            get { return ffk_tb_pdv; }
            set { SetPropertyValue<tb_pdv>(nameof(fk_tb_pdv), ref ffk_tb_pdv, value); }
        }
        long ffk_tb_est;
        public long fk_tb_est
        {
            get { return ffk_tb_est; }
            set { SetPropertyValue<long>(nameof(fk_tb_est), ref ffk_tb_est, value); }
        }
        [Association(@"tb_movimentacaoReferencestb_jornada")]
        public XPCollection<tb_movimentacao> tb_movimentacaos { get { return GetCollection<tb_movimentacao>(nameof(tb_movimentacaos)); } }
    }

}
