//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplicationPDV.bancoSQLite
{

    public partial class tb_movimentacao_pagamento : XPLiteObject
    {
        long fid_movimentacao_pagamento;
        [Key(AutoGenerate = true)]
        public long id_movimentacao_pagamento
        {
            get { return fid_movimentacao_pagamento; }
            set { SetPropertyValue<long>(nameof(id_movimentacao_pagamento), ref fid_movimentacao_pagamento, value); }
        }
        DateTime fmpg_dtCri;
        public DateTime mpg_dtCri
        {
            get { return fmpg_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(mpg_dtCri), ref fmpg_dtCri, value); }
        }
        DateTime fmpg_dtAlt;
        public DateTime mpg_dtAlt
        {
            get { return fmpg_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(mpg_dtAlt), ref fmpg_dtAlt, value); }
        }
        DateTime fmpg_dtAcs;
        public DateTime mpg_dtAcs
        {
            get { return fmpg_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(mpg_dtAcs), ref fmpg_dtAcs, value); }
        }
        decimal fmpg_canc;
        public decimal mpg_canc
        {
            get { return fmpg_canc; }
            set { SetPropertyValue<decimal>(nameof(mpg_canc), ref fmpg_canc, value); }
        }
        short fmpg_numPag;
        public short mpg_numPag
        {
            get { return fmpg_numPag; }
            set { SetPropertyValue<short>(nameof(mpg_numPag), ref fmpg_numPag, value); }
        }
        decimal fmpg_parcs;
        public decimal mpg_parcs
        {
            get { return fmpg_parcs; }
            set { SetPropertyValue<decimal>(nameof(mpg_parcs), ref fmpg_parcs, value); }
        }
        decimal fmpg_nfeVlrPag;
        public decimal mpg_nfeVlrPag
        {
            get { return fmpg_nfeVlrPag; }
            set { SetPropertyValue<decimal>(nameof(mpg_nfeVlrPag), ref fmpg_nfeVlrPag, value); }
        }
        byte fmpg_nfeTipoIntegr;
        public byte mpg_nfeTipoIntegr
        {
            get { return fmpg_nfeTipoIntegr; }
            set { SetPropertyValue<byte>(nameof(mpg_nfeTipoIntegr), ref fmpg_nfeTipoIntegr, value); }
        }
        byte fmpg_nfeTipoBand;
        public byte mpg_nfeTipoBand
        {
            get { return fmpg_nfeTipoBand; }
            set { SetPropertyValue<byte>(nameof(mpg_nfeTipoBand), ref fmpg_nfeTipoBand, value); }
        }
        string fmpg_nfeNumAut;
        [Size(20)]
        public string mpg_nfeNumAut
        {
            get { return fmpg_nfeNumAut; }
            set { SetPropertyValue<string>(nameof(mpg_nfeNumAut), ref fmpg_nfeNumAut, value); }
        }
        decimal fmpg_nfeVlrTroco;
        public decimal mpg_nfeVlrTroco
        {
            get { return fmpg_nfeVlrTroco; }
            set { SetPropertyValue<decimal>(nameof(mpg_nfeVlrTroco), ref fmpg_nfeVlrTroco, value); }
        }
        decimal fmpg_nfeVlrMov;
        public decimal mpg_nfeVlrMov
        {
            get { return fmpg_nfeVlrMov; }
            set { SetPropertyValue<decimal>(nameof(mpg_nfeVlrMov), ref fmpg_nfeVlrMov, value); }
        }
        tb_movimentacao ffk_tb_movimentacao;
        [Association(@"tb_movimentacao_pagamentoReferencestb_movimentacao")]
        public tb_movimentacao fk_tb_movimentacao
        {
            get { return ffk_tb_movimentacao; }
            set { SetPropertyValue<tb_movimentacao>(nameof(fk_tb_movimentacao), ref ffk_tb_movimentacao, value); }
        }
        tb_sub_forma_pagamento ffk_tb_sub_forma_pagamento;
        [Association(@"tb_movimentacao_pagamentoReferencestb_sub_forma_pagamento")]
        public tb_sub_forma_pagamento fk_tb_sub_forma_pagamento
        {
            get { return ffk_tb_sub_forma_pagamento; }
            set { SetPropertyValue<tb_sub_forma_pagamento>(nameof(fk_tb_sub_forma_pagamento), ref ffk_tb_sub_forma_pagamento, value); }
        }
        [Association(@"tb_movimentacao_pagamento_parcelaReferencestb_movimentacao_pagamento")]
        public XPCollection<tb_movimentacao_pagamento_parcela> tb_movimentacao_pagamento_parcelas { get { return GetCollection<tb_movimentacao_pagamento_parcela>(nameof(tb_movimentacao_pagamento_parcelas)); } }
    }

}
