//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplicationPDV.bancoSQLite
{

    public partial class tb_movimentacao_impressao : XPLiteObject
    {
        long fid_movimentacao_impressao;
        [Key(AutoGenerate = true)]
        public long id_movimentacao_impressao
        {
            get { return fid_movimentacao_impressao; }
            set { SetPropertyValue<long>(nameof(id_movimentacao_impressao), ref fid_movimentacao_impressao, value); }
        }
        DateTime fmi_dtCri;
        public DateTime mi_dtCri
        {
            get { return fmi_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(mi_dtCri), ref fmi_dtCri, value); }
        }
        DateTime fmi_dtAlt;
        public DateTime mi_dtAlt
        {
            get { return fmi_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(mi_dtAlt), ref fmi_dtAlt, value); }
        }
        DateTime fmi_dtAcs;
        public DateTime mi_dtAcs
        {
            get { return fmi_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(mi_dtAcs), ref fmi_dtAcs, value); }
        }
        byte fmi_tipo;
        public byte mi_tipo
        {
            get { return fmi_tipo; }
            set { SetPropertyValue<byte>(nameof(mi_tipo), ref fmi_tipo, value); }
        }
        byte[] fmi_pdf;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] mi_pdf
        {
            get { return fmi_pdf; }
            set { SetPropertyValue<byte[]>(nameof(mi_pdf), ref fmi_pdf, value); }
        }
        decimal fmi_dcanc;
        public decimal mi_dcanc
        {
            get { return fmi_dcanc; }
            set { SetPropertyValue<decimal>(nameof(mi_dcanc), ref fmi_dcanc, value); }
        }
        tb_movimentacao ffk_tb_movimentacao;
        [Association(@"tb_movimentacao_impressaoReferencestb_movimentacao")]
        public tb_movimentacao fk_tb_movimentacao
        {
            get { return ffk_tb_movimentacao; }
            set { SetPropertyValue<tb_movimentacao>(nameof(fk_tb_movimentacao), ref ffk_tb_movimentacao, value); }
        }
    }

}
