//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplicationPDV.bancoSQLite
{

    public partial class tb_movimentacao_produto : XPLiteObject
    {
        long fid_movimentacao_produto;
        [Key(AutoGenerate = true)]
        public long id_movimentacao_produto
        {
            get { return fid_movimentacao_produto; }
            set { SetPropertyValue<long>(nameof(id_movimentacao_produto), ref fid_movimentacao_produto, value); }
        }
        string fmp_desc;
        [Size(120)]
        public string mp_desc
        {
            get { return fmp_desc; }
            set { SetPropertyValue<string>(nameof(mp_desc), ref fmp_desc, value); }
        }
        string fmp_descCurta;
        [Size(25)]
        public string mp_descCurta
        {
            get { return fmp_descCurta; }
            set { SetPropertyValue<string>(nameof(mp_descCurta), ref fmp_descCurta, value); }
        }
        string fmp_nfeIpiCnpjProd;
        [Size(18)]
        public string mp_nfeIpiCnpjProd
        {
            get { return fmp_nfeIpiCnpjProd; }
            set { SetPropertyValue<string>(nameof(mp_nfeIpiCnpjProd), ref fmp_nfeIpiCnpjProd, value); }
        }
        string fmp_nfeNcm_ImpXml;
        [Size(8)]
        public string mp_nfeNcm_ImpXml
        {
            get { return fmp_nfeNcm_ImpXml; }
            set { SetPropertyValue<string>(nameof(mp_nfeNcm_ImpXml), ref fmp_nfeNcm_ImpXml, value); }
        }
        decimal fmp_vlrFrete_ImpXml;
        public decimal mp_vlrFrete_ImpXml
        {
            get { return fmp_vlrFrete_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_vlrFrete_ImpXml), ref fmp_vlrFrete_ImpXml, value); }
        }
        long fmp_movProOrig;
        public long mp_movProOrig
        {
            get { return fmp_movProOrig; }
            set { SetPropertyValue<long>(nameof(mp_movProOrig), ref fmp_movProOrig, value); }
        }
        DateTime fmp_dtCri;
        public DateTime mp_dtCri
        {
            get { return fmp_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(mp_dtCri), ref fmp_dtCri, value); }
        }
        DateTime fmp_dtAlt;
        public DateTime mp_dtAlt
        {
            get { return fmp_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(mp_dtAlt), ref fmp_dtAlt, value); }
        }
        DateTime fmp_dtAcs;
        public DateTime mp_dtAcs
        {
            get { return fmp_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(mp_dtAcs), ref fmp_dtAcs, value); }
        }
        short fmp_nfeCfop_ImpXml;
        public short mp_nfeCfop_ImpXml
        {
            get { return fmp_nfeCfop_ImpXml; }
            set { SetPropertyValue<short>(nameof(mp_nfeCfop_ImpXml), ref fmp_nfeCfop_ImpXml, value); }
        }
        short fmp_numItem;
        public short mp_numItem
        {
            get { return fmp_numItem; }
            set { SetPropertyValue<short>(nameof(mp_numItem), ref fmp_numItem, value); }
        }
        decimal fmp_canc;
        public decimal mp_canc
        {
            get { return fmp_canc; }
            set { SetPropertyValue<decimal>(nameof(mp_canc), ref fmp_canc, value); }
        }
        byte fmp_nfePisCofinsReg;
        public byte mp_nfePisCofinsReg
        {
            get { return fmp_nfePisCofinsReg; }
            set { SetPropertyValue<byte>(nameof(mp_nfePisCofinsReg), ref fmp_nfePisCofinsReg, value); }
        }
        decimal fmp_pisCofinsIncidencia;
        public decimal mp_pisCofinsIncidencia
        {
            get { return fmp_pisCofinsIncidencia; }
            set { SetPropertyValue<decimal>(nameof(mp_pisCofinsIncidencia), ref fmp_pisCofinsIncidencia, value); }
        }
        long fmp_codRef;
        public long mp_codRef
        {
            get { return fmp_codRef; }
            set { SetPropertyValue<long>(nameof(mp_codRef), ref fmp_codRef, value); }
        }
        decimal fmp_qtdCom;
        public decimal mp_qtdCom
        {
            get { return fmp_qtdCom; }
            set { SetPropertyValue<decimal>(nameof(mp_qtdCom), ref fmp_qtdCom, value); }
        }
        string fmp_obs;
        [Size(SizeAttribute.Unlimited)]
        public string mp_obs
        {
            get { return fmp_obs; }
            set { SetPropertyValue<string>(nameof(mp_obs), ref fmp_obs, value); }
        }
        decimal fmp_qtdDevolvida;
        public decimal mp_qtdDevolvida
        {
            get { return fmp_qtdDevolvida; }
            set { SetPropertyValue<decimal>(nameof(mp_qtdDevolvida), ref fmp_qtdDevolvida, value); }
        }
        decimal fmp_qtdDevolver;
        public decimal mp_qtdDevolver
        {
            get { return fmp_qtdDevolver; }
            set { SetPropertyValue<decimal>(nameof(mp_qtdDevolver), ref fmp_qtdDevolver, value); }
        }
        byte fmp_unMedCom;
        public byte mp_unMedCom
        {
            get { return fmp_unMedCom; }
            set { SetPropertyValue<byte>(nameof(mp_unMedCom), ref fmp_unMedCom, value); }
        }
        string fmp_unMedCom_ImpXml;
        [Size(10)]
        public string mp_unMedCom_ImpXml
        {
            get { return fmp_unMedCom_ImpXml; }
            set { SetPropertyValue<string>(nameof(mp_unMedCom_ImpXml), ref fmp_unMedCom_ImpXml, value); }
        }
        decimal fmp_vlrUnCom;
        public decimal mp_vlrUnCom
        {
            get { return fmp_vlrUnCom; }
            set { SetPropertyValue<decimal>(nameof(mp_vlrUnCom), ref fmp_vlrUnCom, value); }
        }
        string fmp_ean;
        [Size(15)]
        public string mp_ean
        {
            get { return fmp_ean; }
            set { SetPropertyValue<string>(nameof(mp_ean), ref fmp_ean, value); }
        }
        decimal fmp_vlrProdTot;
        public decimal mp_vlrProdTot
        {
            get { return fmp_vlrProdTot; }
            set { SetPropertyValue<decimal>(nameof(mp_vlrProdTot), ref fmp_vlrProdTot, value); }
        }
        decimal fmp_vlrProdTot_ImpXml;
        public decimal mp_vlrProdTot_ImpXml
        {
            get { return fmp_vlrProdTot_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_vlrProdTot_ImpXml), ref fmp_vlrProdTot_ImpXml, value); }
        }
        decimal fmp_vlrFrete;
        public decimal mp_vlrFrete
        {
            get { return fmp_vlrFrete; }
            set { SetPropertyValue<decimal>(nameof(mp_vlrFrete), ref fmp_vlrFrete, value); }
        }
        decimal fmp_vlrSeg;
        public decimal mp_vlrSeg
        {
            get { return fmp_vlrSeg; }
            set { SetPropertyValue<decimal>(nameof(mp_vlrSeg), ref fmp_vlrSeg, value); }
        }
        char fmp_tipoDesc;
        public char mp_tipoDesc
        {
            get { return fmp_tipoDesc; }
            set { SetPropertyValue<char>(nameof(mp_tipoDesc), ref fmp_tipoDesc, value); }
        }
        decimal fmp_vlrDesc;
        public decimal mp_vlrDesc
        {
            get { return fmp_vlrDesc; }
            set { SetPropertyValue<decimal>(nameof(mp_vlrDesc), ref fmp_vlrDesc, value); }
        }
        decimal fmp_vlrOutro;
        public decimal mp_vlrOutro
        {
            get { return fmp_vlrOutro; }
            set { SetPropertyValue<decimal>(nameof(mp_vlrOutro), ref fmp_vlrOutro, value); }
        }
        string fmp_cest;
        [Size(7)]
        public string mp_cest
        {
            get { return fmp_cest; }
            set { SetPropertyValue<string>(nameof(mp_cest), ref fmp_cest, value); }
        }
        long fmp_nfeCfop;
        public long mp_nfeCfop
        {
            get { return fmp_nfeCfop; }
            set { SetPropertyValue<long>(nameof(mp_nfeCfop), ref fmp_nfeCfop, value); }
        }
        byte fmp_nfeIndValProdTotNfe;
        public byte mp_nfeIndValProdTotNfe
        {
            get { return fmp_nfeIndValProdTotNfe; }
            set { SetPropertyValue<byte>(nameof(mp_nfeIndValProdTotNfe), ref fmp_nfeIndValProdTotNfe, value); }
        }
        byte fmp_nfeProdOrigem;
        public byte mp_nfeProdOrigem
        {
            get { return fmp_nfeProdOrigem; }
            set { SetPropertyValue<byte>(nameof(mp_nfeProdOrigem), ref fmp_nfeProdOrigem, value); }
        }
        short fmp_nfeCst;
        public short mp_nfeCst
        {
            get { return fmp_nfeCst; }
            set { SetPropertyValue<short>(nameof(mp_nfeCst), ref fmp_nfeCst, value); }
        }
        byte fmp_nfeModBc;
        public byte mp_nfeModBc
        {
            get { return fmp_nfeModBc; }
            set { SetPropertyValue<byte>(nameof(mp_nfeModBc), ref fmp_nfeModBc, value); }
        }
        decimal fmp_nfeVlrBcIcms;
        public decimal mp_nfeVlrBcIcms
        {
            get { return fmp_nfeVlrBcIcms; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrBcIcms), ref fmp_nfeVlrBcIcms, value); }
        }
        decimal fmp_nfeVlrBcIcms_ImpXml;
        public decimal mp_nfeVlrBcIcms_ImpXml
        {
            get { return fmp_nfeVlrBcIcms_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrBcIcms_ImpXml), ref fmp_nfeVlrBcIcms_ImpXml, value); }
        }
        decimal fmp_nfeAliqIcms;
        public decimal mp_nfeAliqIcms
        {
            get { return fmp_nfeAliqIcms; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeAliqIcms), ref fmp_nfeAliqIcms, value); }
        }
        decimal fmp_nfeVlrTotIcms;
        public decimal mp_nfeVlrTotIcms
        {
            get { return fmp_nfeVlrTotIcms; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrTotIcms), ref fmp_nfeVlrTotIcms, value); }
        }
        decimal fmp_nfeVlrTotIcms_ImpXml;
        public decimal mp_nfeVlrTotIcms_ImpXml
        {
            get { return fmp_nfeVlrTotIcms_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrTotIcms_ImpXml), ref fmp_nfeVlrTotIcms_ImpXml, value); }
        }
        decimal fmp_nfeVlrBcFcp;
        public decimal mp_nfeVlrBcFcp
        {
            get { return fmp_nfeVlrBcFcp; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrBcFcp), ref fmp_nfeVlrBcFcp, value); }
        }
        decimal fmp_nfeVlrBcFcp_ImpXml;
        public decimal mp_nfeVlrBcFcp_ImpXml
        {
            get { return fmp_nfeVlrBcFcp_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrBcFcp_ImpXml), ref fmp_nfeVlrBcFcp_ImpXml, value); }
        }
        decimal fmp_nfePercFcp;
        public decimal mp_nfePercFcp
        {
            get { return fmp_nfePercFcp; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePercFcp), ref fmp_nfePercFcp, value); }
        }
        decimal fmp_nfeVlrFcp;
        public decimal mp_nfeVlrFcp
        {
            get { return fmp_nfeVlrFcp; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrFcp), ref fmp_nfeVlrFcp, value); }
        }
        long fmp_nfeModBcSt;
        public long mp_nfeModBcSt
        {
            get { return fmp_nfeModBcSt; }
            set { SetPropertyValue<long>(nameof(mp_nfeModBcSt), ref fmp_nfeModBcSt, value); }
        }
        decimal fmp_nfePercMvaSt;
        public decimal mp_nfePercMvaSt
        {
            get { return fmp_nfePercMvaSt; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePercMvaSt), ref fmp_nfePercMvaSt, value); }
        }
        decimal fmp_nfePercRedBcIcms;
        public decimal mp_nfePercRedBcIcms
        {
            get { return fmp_nfePercRedBcIcms; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePercRedBcIcms), ref fmp_nfePercRedBcIcms, value); }
        }
        decimal fmp_nfePercRedBcIcmsSt;
        public decimal mp_nfePercRedBcIcmsSt
        {
            get { return fmp_nfePercRedBcIcmsSt; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePercRedBcIcmsSt), ref fmp_nfePercRedBcIcmsSt, value); }
        }
        decimal fmp_nfeVlrBcIcmsSt;
        public decimal mp_nfeVlrBcIcmsSt
        {
            get { return fmp_nfeVlrBcIcmsSt; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrBcIcmsSt), ref fmp_nfeVlrBcIcmsSt, value); }
        }
        decimal fmp_nfeVlrBcIcmsSt_ImpXml;
        public decimal mp_nfeVlrBcIcmsSt_ImpXml
        {
            get { return fmp_nfeVlrBcIcmsSt_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrBcIcmsSt_ImpXml), ref fmp_nfeVlrBcIcmsSt_ImpXml, value); }
        }
        decimal fmp_nfeAliqIcmsSt;
        public decimal mp_nfeAliqIcmsSt
        {
            get { return fmp_nfeAliqIcmsSt; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeAliqIcmsSt), ref fmp_nfeAliqIcmsSt, value); }
        }
        decimal fmp_nfeVlrIcmsSt;
        public decimal mp_nfeVlrIcmsSt
        {
            get { return fmp_nfeVlrIcmsSt; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrIcmsSt), ref fmp_nfeVlrIcmsSt, value); }
        }
        decimal fmp_nfeVlrIcmsSt_ImpXml;
        public decimal mp_nfeVlrIcmsSt_ImpXml
        {
            get { return fmp_nfeVlrIcmsSt_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrIcmsSt_ImpXml), ref fmp_nfeVlrIcmsSt_ImpXml, value); }
        }
        decimal fmp_nfeVlrBcFcpRetSt;
        public decimal mp_nfeVlrBcFcpRetSt
        {
            get { return fmp_nfeVlrBcFcpRetSt; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrBcFcpRetSt), ref fmp_nfeVlrBcFcpRetSt, value); }
        }
        decimal fmp_nfePercFcpRetSt;
        public decimal mp_nfePercFcpRetSt
        {
            get { return fmp_nfePercFcpRetSt; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePercFcpRetSt), ref fmp_nfePercFcpRetSt, value); }
        }
        decimal fmp_nfeVlrFcpRetSt;
        public decimal mp_nfeVlrFcpRetSt
        {
            get { return fmp_nfeVlrFcpRetSt; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrFcpRetSt), ref fmp_nfeVlrFcpRetSt, value); }
        }
        decimal fmp_nfeVlrIcmsDeson;
        public decimal mp_nfeVlrIcmsDeson
        {
            get { return fmp_nfeVlrIcmsDeson; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrIcmsDeson), ref fmp_nfeVlrIcmsDeson, value); }
        }
        decimal fmp_nfeVlrIcmsDeson_ImpXml;
        public decimal mp_nfeVlrIcmsDeson_ImpXml
        {
            get { return fmp_nfeVlrIcmsDeson_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrIcmsDeson_ImpXml), ref fmp_nfeVlrIcmsDeson_ImpXml, value); }
        }
        byte fmp_nfeMotDesonIcms;
        public byte mp_nfeMotDesonIcms
        {
            get { return fmp_nfeMotDesonIcms; }
            set { SetPropertyValue<byte>(nameof(mp_nfeMotDesonIcms), ref fmp_nfeMotDesonIcms, value); }
        }
        decimal fmp_nfeVlrIcmsOp;
        public decimal mp_nfeVlrIcmsOp
        {
            get { return fmp_nfeVlrIcmsOp; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrIcmsOp), ref fmp_nfeVlrIcmsOp, value); }
        }
        decimal fmp_nfeVlrIcmsOp_ImpXml;
        public decimal mp_nfeVlrIcmsOp_ImpXml
        {
            get { return fmp_nfeVlrIcmsOp_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrIcmsOp_ImpXml), ref fmp_nfeVlrIcmsOp_ImpXml, value); }
        }
        decimal fmp_nfePercDif;
        public decimal mp_nfePercDif
        {
            get { return fmp_nfePercDif; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePercDif), ref fmp_nfePercDif, value); }
        }
        decimal fmp_nfeVlrIcmsDif;
        public decimal mp_nfeVlrIcmsDif
        {
            get { return fmp_nfeVlrIcmsDif; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrIcmsDif), ref fmp_nfeVlrIcmsDif, value); }
        }
        decimal fmp_nfeVlrIcmsDif_ImpXml;
        public decimal mp_nfeVlrIcmsDif_ImpXml
        {
            get { return fmp_nfeVlrIcmsDif_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrIcmsDif_ImpXml), ref fmp_nfeVlrIcmsDif_ImpXml, value); }
        }
        decimal fmp_nfeVlrBcIcmsStRet;
        public decimal mp_nfeVlrBcIcmsStRet
        {
            get { return fmp_nfeVlrBcIcmsStRet; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrBcIcmsStRet), ref fmp_nfeVlrBcIcmsStRet, value); }
        }
        decimal fmp_nfePercAliqSuportada;
        public decimal mp_nfePercAliqSuportada
        {
            get { return fmp_nfePercAliqSuportada; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePercAliqSuportada), ref fmp_nfePercAliqSuportada, value); }
        }
        decimal fmp_nfeVlrIcmsPropSubst;
        public decimal mp_nfeVlrIcmsPropSubst
        {
            get { return fmp_nfeVlrIcmsPropSubst; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrIcmsPropSubst), ref fmp_nfeVlrIcmsPropSubst, value); }
        }
        decimal fmp_nfeVlrIcmsStRet;
        public decimal mp_nfeVlrIcmsStRet
        {
            get { return fmp_nfeVlrIcmsStRet; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrIcmsStRet), ref fmp_nfeVlrIcmsStRet, value); }
        }
        decimal fmp_nfeBcFcpRetAnt;
        public decimal mp_nfeBcFcpRetAnt
        {
            get { return fmp_nfeBcFcpRetAnt; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeBcFcpRetAnt), ref fmp_nfeBcFcpRetAnt, value); }
        }
        decimal fmp_nfePercFcpRetAntSt;
        public decimal mp_nfePercFcpRetAntSt
        {
            get { return fmp_nfePercFcpRetAntSt; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePercFcpRetAntSt), ref fmp_nfePercFcpRetAntSt, value); }
        }
        decimal fmp_nfePercRedBcEfet;
        public decimal mp_nfePercRedBcEfet
        {
            get { return fmp_nfePercRedBcEfet; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePercRedBcEfet), ref fmp_nfePercRedBcEfet, value); }
        }
        decimal fmp_nfeVlrBcEfet;
        public decimal mp_nfeVlrBcEfet
        {
            get { return fmp_nfeVlrBcEfet; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrBcEfet), ref fmp_nfeVlrBcEfet, value); }
        }
        decimal fmp_nfePercAliqIcmsEfet;
        public decimal mp_nfePercAliqIcmsEfet
        {
            get { return fmp_nfePercAliqIcmsEfet; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePercAliqIcmsEfet), ref fmp_nfePercAliqIcmsEfet, value); }
        }
        decimal fmp_nfeVlrIcmsEfet;
        public decimal mp_nfeVlrIcmsEfet
        {
            get { return fmp_nfeVlrIcmsEfet; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrIcmsEfet), ref fmp_nfeVlrIcmsEfet, value); }
        }
        short fmp_nfeCsosn;
        public short mp_nfeCsosn
        {
            get { return fmp_nfeCsosn; }
            set { SetPropertyValue<short>(nameof(mp_nfeCsosn), ref fmp_nfeCsosn, value); }
        }
        decimal fmp_nfePercAliqCredSn;
        public decimal mp_nfePercAliqCredSn
        {
            get { return fmp_nfePercAliqCredSn; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePercAliqCredSn), ref fmp_nfePercAliqCredSn, value); }
        }
        decimal fmp_nfeVlrCredIcmsSn;
        public decimal mp_nfeVlrCredIcmsSn
        {
            get { return fmp_nfeVlrCredIcmsSn; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrCredIcmsSn), ref fmp_nfeVlrCredIcmsSn, value); }
        }
        string fmp_nfeIpiCSelo;
        [Size(60)]
        public string mp_nfeIpiCSelo
        {
            get { return fmp_nfeIpiCSelo; }
            set { SetPropertyValue<string>(nameof(mp_nfeIpiCSelo), ref fmp_nfeIpiCSelo, value); }
        }
        long fmp_nfeIpiQSelo;
        public long mp_nfeIpiQSelo
        {
            get { return fmp_nfeIpiQSelo; }
            set { SetPropertyValue<long>(nameof(mp_nfeIpiQSelo), ref fmp_nfeIpiQSelo, value); }
        }
        string fmp_nfeIpicEnq;
        [Size(3)]
        public string mp_nfeIpicEnq
        {
            get { return fmp_nfeIpicEnq; }
            set { SetPropertyValue<string>(nameof(mp_nfeIpicEnq), ref fmp_nfeIpicEnq, value); }
        }
        byte fmp_nfeIpiTribCst;
        public byte mp_nfeIpiTribCst
        {
            get { return fmp_nfeIpiTribCst; }
            set { SetPropertyValue<byte>(nameof(mp_nfeIpiTribCst), ref fmp_nfeIpiTribCst, value); }
        }
        decimal fmp_nfeIpiTribXml1VlrBC;
        public decimal mp_nfeIpiTribXml1VlrBC
        {
            get { return fmp_nfeIpiTribXml1VlrBC; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeIpiTribXml1VlrBC), ref fmp_nfeIpiTribXml1VlrBC, value); }
        }
        decimal fmp_nfeIpiTribXml1VlrBC_ImpXml;
        public decimal mp_nfeIpiTribXml1VlrBC_ImpXml
        {
            get { return fmp_nfeIpiTribXml1VlrBC_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeIpiTribXml1VlrBC_ImpXml), ref fmp_nfeIpiTribXml1VlrBC_ImpXml, value); }
        }
        decimal fmp_nfeIpiTribXml1PercIPI;
        public decimal mp_nfeIpiTribXml1PercIPI
        {
            get { return fmp_nfeIpiTribXml1PercIPI; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeIpiTribXml1PercIPI), ref fmp_nfeIpiTribXml1PercIPI, value); }
        }
        decimal fmp_nfeIpiTribXml2qUnid;
        public decimal mp_nfeIpiTribXml2qUnid
        {
            get { return fmp_nfeIpiTribXml2qUnid; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeIpiTribXml2qUnid), ref fmp_nfeIpiTribXml2qUnid, value); }
        }
        decimal fmp_nfeIpiTribXml2VlrUnit;
        public decimal mp_nfeIpiTribXml2VlrUnit
        {
            get { return fmp_nfeIpiTribXml2VlrUnit; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeIpiTribXml2VlrUnit), ref fmp_nfeIpiTribXml2VlrUnit, value); }
        }
        decimal fmp_nfeIpiTribXml2VlrIpi;
        public decimal mp_nfeIpiTribXml2VlrIpi
        {
            get { return fmp_nfeIpiTribXml2VlrIpi; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeIpiTribXml2VlrIpi), ref fmp_nfeIpiTribXml2VlrIpi, value); }
        }
        decimal fmp_nfeIpiTribXml2VlrIpi_ImpXml;
        public decimal mp_nfeIpiTribXml2VlrIpi_ImpXml
        {
            get { return fmp_nfeIpiTribXml2VlrIpi_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeIpiTribXml2VlrIpi_ImpXml), ref fmp_nfeIpiTribXml2VlrIpi_ImpXml, value); }
        }
        byte fmp_nfeIpiIpintCst;
        public byte mp_nfeIpiIpintCst
        {
            get { return fmp_nfeIpiIpintCst; }
            set { SetPropertyValue<byte>(nameof(mp_nfeIpiIpintCst), ref fmp_nfeIpiIpintCst, value); }
        }
        decimal fmp_nfeImpImpVlrBc;
        public decimal mp_nfeImpImpVlrBc
        {
            get { return fmp_nfeImpImpVlrBc; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeImpImpVlrBc), ref fmp_nfeImpImpVlrBc, value); }
        }
        decimal fmp_nfeImpImpVlrDespAdu;
        public decimal mp_nfeImpImpVlrDespAdu
        {
            get { return fmp_nfeImpImpVlrDespAdu; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeImpImpVlrDespAdu), ref fmp_nfeImpImpVlrDespAdu, value); }
        }
        decimal fmp_nfeImpImpVlr;
        public decimal mp_nfeImpImpVlr
        {
            get { return fmp_nfeImpImpVlr; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeImpImpVlr), ref fmp_nfeImpImpVlr, value); }
        }
        decimal fmp_nfeImpImpVlrIof;
        public decimal mp_nfeImpImpVlrIof
        {
            get { return fmp_nfeImpImpVlrIof; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeImpImpVlrIof), ref fmp_nfeImpImpVlrIof, value); }
        }
        decimal fmp_nfeVlrBcIcmsUfDest;
        public decimal mp_nfeVlrBcIcmsUfDest
        {
            get { return fmp_nfeVlrBcIcmsUfDest; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrBcIcmsUfDest), ref fmp_nfeVlrBcIcmsUfDest, value); }
        }
        decimal fmp_nfeVlrBcIcmsUfDest_ImpXml;
        public decimal mp_nfeVlrBcIcmsUfDest_ImpXml
        {
            get { return fmp_nfeVlrBcIcmsUfDest_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrBcIcmsUfDest_ImpXml), ref fmp_nfeVlrBcIcmsUfDest_ImpXml, value); }
        }
        decimal fmp_nfeVlrBcFcpUfDest;
        public decimal mp_nfeVlrBcFcpUfDest
        {
            get { return fmp_nfeVlrBcFcpUfDest; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrBcFcpUfDest), ref fmp_nfeVlrBcFcpUfDest, value); }
        }
        decimal fmp_nfeVlrBcFcpUfDest_ImpXml;
        public decimal mp_nfeVlrBcFcpUfDest_ImpXml
        {
            get { return fmp_nfeVlrBcFcpUfDest_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrBcFcpUfDest_ImpXml), ref fmp_nfeVlrBcFcpUfDest_ImpXml, value); }
        }
        decimal fmp_nfePercFcpUfDest;
        public decimal mp_nfePercFcpUfDest
        {
            get { return fmp_nfePercFcpUfDest; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePercFcpUfDest), ref fmp_nfePercFcpUfDest, value); }
        }
        decimal fmp_nfeAliqIcmsUfDest;
        public decimal mp_nfeAliqIcmsUfDest
        {
            get { return fmp_nfeAliqIcmsUfDest; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeAliqIcmsUfDest), ref fmp_nfeAliqIcmsUfDest, value); }
        }
        decimal fmp_nfeAliqIcmsInterUfDest;
        public decimal mp_nfeAliqIcmsInterUfDest
        {
            get { return fmp_nfeAliqIcmsInterUfDest; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeAliqIcmsInterUfDest), ref fmp_nfeAliqIcmsInterUfDest, value); }
        }
        decimal fmp_nfePercIcmsPartUfDest;
        public decimal mp_nfePercIcmsPartUfDest
        {
            get { return fmp_nfePercIcmsPartUfDest; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePercIcmsPartUfDest), ref fmp_nfePercIcmsPartUfDest, value); }
        }
        decimal fmp_nfeVlrFcpUfDest;
        public decimal mp_nfeVlrFcpUfDest
        {
            get { return fmp_nfeVlrFcpUfDest; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrFcpUfDest), ref fmp_nfeVlrFcpUfDest, value); }
        }
        decimal fmp_nfeVlrIcmsUfDest;
        public decimal mp_nfeVlrIcmsUfDest
        {
            get { return fmp_nfeVlrIcmsUfDest; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrIcmsUfDest), ref fmp_nfeVlrIcmsUfDest, value); }
        }
        decimal fmp_nfeVlrIcmsUfDest_ImpXml;
        public decimal mp_nfeVlrIcmsUfDest_ImpXml
        {
            get { return fmp_nfeVlrIcmsUfDest_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrIcmsUfDest_ImpXml), ref fmp_nfeVlrIcmsUfDest_ImpXml, value); }
        }
        decimal fmp_nfeVlrIcmsUfRemet;
        public decimal mp_nfeVlrIcmsUfRemet
        {
            get { return fmp_nfeVlrIcmsUfRemet; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrIcmsUfRemet), ref fmp_nfeVlrIcmsUfRemet, value); }
        }
        decimal fmp_nfeVlrIcmsUfRemet_ImpXml;
        public decimal mp_nfeVlrIcmsUfRemet_ImpXml
        {
            get { return fmp_nfeVlrIcmsUfRemet_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeVlrIcmsUfRemet_ImpXml), ref fmp_nfeVlrIcmsUfRemet_ImpXml, value); }
        }
        byte fmp_nfePisCofinsCst;
        public byte mp_nfePisCofinsCst
        {
            get { return fmp_nfePisCofinsCst; }
            set { SetPropertyValue<byte>(nameof(mp_nfePisCofinsCst), ref fmp_nfePisCofinsCst, value); }
        }
        decimal fmp_nfePisAliqVlrBc;
        public decimal mp_nfePisAliqVlrBc
        {
            get { return fmp_nfePisAliqVlrBc; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisAliqVlrBc), ref fmp_nfePisAliqVlrBc, value); }
        }
        decimal fmp_nfePisAliqVlrBc_ImpXml;
        public decimal mp_nfePisAliqVlrBc_ImpXml
        {
            get { return fmp_nfePisAliqVlrBc_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisAliqVlrBc_ImpXml), ref fmp_nfePisAliqVlrBc_ImpXml, value); }
        }
        decimal fmp_nfePisAliq;
        public decimal mp_nfePisAliq
        {
            get { return fmp_nfePisAliq; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisAliq), ref fmp_nfePisAliq, value); }
        }
        decimal fmp_nfePisAliq_ImpXml;
        public decimal mp_nfePisAliq_ImpXml
        {
            get { return fmp_nfePisAliq_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisAliq_ImpXml), ref fmp_nfePisAliq_ImpXml, value); }
        }
        decimal fmp_nfePisAliqVlr;
        public decimal mp_nfePisAliqVlr
        {
            get { return fmp_nfePisAliqVlr; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisAliqVlr), ref fmp_nfePisAliqVlr, value); }
        }
        decimal fmp_nfePisAliqVlr_ImpXml;
        public decimal mp_nfePisAliqVlr_ImpXml
        {
            get { return fmp_nfePisAliqVlr_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisAliqVlr_ImpXml), ref fmp_nfePisAliqVlr_ImpXml, value); }
        }
        decimal fmp_nfePisQtdeBcProd;
        public decimal mp_nfePisQtdeBcProd
        {
            get { return fmp_nfePisQtdeBcProd; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisQtdeBcProd), ref fmp_nfePisQtdeBcProd, value); }
        }
        decimal fmp_nfePisQtdeAliqProd;
        public decimal mp_nfePisQtdeAliqProd
        {
            get { return fmp_nfePisQtdeAliqProd; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisQtdeAliqProd), ref fmp_nfePisQtdeAliqProd, value); }
        }
        decimal fmp_nfePisQtdeVlr;
        public decimal mp_nfePisQtdeVlr
        {
            get { return fmp_nfePisQtdeVlr; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisQtdeVlr), ref fmp_nfePisQtdeVlr, value); }
        }
        decimal fmp_nfePisQtdeVlr_ImpXml;
        public decimal mp_nfePisQtdeVlr_ImpXml
        {
            get { return fmp_nfePisQtdeVlr_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisQtdeVlr_ImpXml), ref fmp_nfePisQtdeVlr_ImpXml, value); }
        }
        decimal fmp_nfePisOutrBcVlr;
        public decimal mp_nfePisOutrBcVlr
        {
            get { return fmp_nfePisOutrBcVlr; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisOutrBcVlr), ref fmp_nfePisOutrBcVlr, value); }
        }
        decimal fmp_nfePisOutrBcVlr_ImpXml;
        public decimal mp_nfePisOutrBcVlr_ImpXml
        {
            get { return fmp_nfePisOutrBcVlr_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisOutrBcVlr_ImpXml), ref fmp_nfePisOutrBcVlr_ImpXml, value); }
        }
        decimal fmp_nfePisOutrAliq;
        public decimal mp_nfePisOutrAliq
        {
            get { return fmp_nfePisOutrAliq; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisOutrAliq), ref fmp_nfePisOutrAliq, value); }
        }
        decimal fmp_nfePisOutrAliq_ImpXml;
        public decimal mp_nfePisOutrAliq_ImpXml
        {
            get { return fmp_nfePisOutrAliq_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisOutrAliq_ImpXml), ref fmp_nfePisOutrAliq_ImpXml, value); }
        }
        decimal fmp_nfePisOutrVlr;
        public decimal mp_nfePisOutrVlr
        {
            get { return fmp_nfePisOutrVlr; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisOutrVlr), ref fmp_nfePisOutrVlr, value); }
        }
        decimal fmp_nfePisOutrVlr_ImpXml;
        public decimal mp_nfePisOutrVlr_ImpXml
        {
            get { return fmp_nfePisOutrVlr_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisOutrVlr_ImpXml), ref fmp_nfePisOutrVlr_ImpXml, value); }
        }
        decimal fmp_nfePisVlrBcST;
        public decimal mp_nfePisVlrBcST
        {
            get { return fmp_nfePisVlrBcST; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisVlrBcST), ref fmp_nfePisVlrBcST, value); }
        }
        decimal fmp_nfePisVlrBcST_ImpXml;
        public decimal mp_nfePisVlrBcST_ImpXml
        {
            get { return fmp_nfePisVlrBcST_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisVlrBcST_ImpXml), ref fmp_nfePisVlrBcST_ImpXml, value); }
        }
        decimal fmp_nfePisAliqST;
        public decimal mp_nfePisAliqST
        {
            get { return fmp_nfePisAliqST; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisAliqST), ref fmp_nfePisAliqST, value); }
        }
        decimal fmp_nfePisQtdeBcProdST;
        public decimal mp_nfePisQtdeBcProdST
        {
            get { return fmp_nfePisQtdeBcProdST; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisQtdeBcProdST), ref fmp_nfePisQtdeBcProdST, value); }
        }
        decimal fmp_nfePisQtdeBcProdST_ImpXml;
        public decimal mp_nfePisQtdeBcProdST_ImpXml
        {
            get { return fmp_nfePisQtdeBcProdST_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisQtdeBcProdST_ImpXml), ref fmp_nfePisQtdeBcProdST_ImpXml, value); }
        }
        decimal fmp_nfePisAliqProdST;
        public decimal mp_nfePisAliqProdST
        {
            get { return fmp_nfePisAliqProdST; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisAliqProdST), ref fmp_nfePisAliqProdST, value); }
        }
        decimal fmp_nfePisVlrST;
        public decimal mp_nfePisVlrST
        {
            get { return fmp_nfePisVlrST; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisVlrST), ref fmp_nfePisVlrST, value); }
        }
        decimal fmp_nfePisVlrST_ImpXml;
        public decimal mp_nfePisVlrST_ImpXml
        {
            get { return fmp_nfePisVlrST_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfePisVlrST_ImpXml), ref fmp_nfePisVlrST_ImpXml, value); }
        }
        decimal fmp_nfeCofinsAliqVlrBc;
        public decimal mp_nfeCofinsAliqVlrBc
        {
            get { return fmp_nfeCofinsAliqVlrBc; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsAliqVlrBc), ref fmp_nfeCofinsAliqVlrBc, value); }
        }
        decimal fmp_nfeCofinsAliqVlrBc_ImpXml;
        public decimal mp_nfeCofinsAliqVlrBc_ImpXml
        {
            get { return fmp_nfeCofinsAliqVlrBc_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsAliqVlrBc_ImpXml), ref fmp_nfeCofinsAliqVlrBc_ImpXml, value); }
        }
        decimal fmp_nfeCofinsAliq;
        public decimal mp_nfeCofinsAliq
        {
            get { return fmp_nfeCofinsAliq; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsAliq), ref fmp_nfeCofinsAliq, value); }
        }
        decimal fmp_nfeCofinsAliq_ImpXml;
        public decimal mp_nfeCofinsAliq_ImpXml
        {
            get { return fmp_nfeCofinsAliq_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsAliq_ImpXml), ref fmp_nfeCofinsAliq_ImpXml, value); }
        }
        decimal fmp_nfeCofinsAliqVlr;
        public decimal mp_nfeCofinsAliqVlr
        {
            get { return fmp_nfeCofinsAliqVlr; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsAliqVlr), ref fmp_nfeCofinsAliqVlr, value); }
        }
        decimal fmp_nfeCofinsAliqVlr_ImpXml;
        public decimal mp_nfeCofinsAliqVlr_ImpXml
        {
            get { return fmp_nfeCofinsAliqVlr_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsAliqVlr_ImpXml), ref fmp_nfeCofinsAliqVlr_ImpXml, value); }
        }
        decimal fmp_nfeCofinsQtdeBcProd;
        public decimal mp_nfeCofinsQtdeBcProd
        {
            get { return fmp_nfeCofinsQtdeBcProd; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsQtdeBcProd), ref fmp_nfeCofinsQtdeBcProd, value); }
        }
        decimal fmp_nfeCofinsQtdeBcProd_ImpXml;
        public decimal mp_nfeCofinsQtdeBcProd_ImpXml
        {
            get { return fmp_nfeCofinsQtdeBcProd_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsQtdeBcProd_ImpXml), ref fmp_nfeCofinsQtdeBcProd_ImpXml, value); }
        }
        decimal fmp_nfeCofinsQtdeAliqProd;
        public decimal mp_nfeCofinsQtdeAliqProd
        {
            get { return fmp_nfeCofinsQtdeAliqProd; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsQtdeAliqProd), ref fmp_nfeCofinsQtdeAliqProd, value); }
        }
        decimal fmp_nfeCofinsQtdeVlr;
        public decimal mp_nfeCofinsQtdeVlr
        {
            get { return fmp_nfeCofinsQtdeVlr; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsQtdeVlr), ref fmp_nfeCofinsQtdeVlr, value); }
        }
        decimal fmp_nfeCofinsQtdeVlr_ImpXml;
        public decimal mp_nfeCofinsQtdeVlr_ImpXml
        {
            get { return fmp_nfeCofinsQtdeVlr_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsQtdeVlr_ImpXml), ref fmp_nfeCofinsQtdeVlr_ImpXml, value); }
        }
        decimal fmp_nfeCofinsOutrBcVlr;
        public decimal mp_nfeCofinsOutrBcVlr
        {
            get { return fmp_nfeCofinsOutrBcVlr; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsOutrBcVlr), ref fmp_nfeCofinsOutrBcVlr, value); }
        }
        decimal fmp_nfeCofinsOutrBcVlr_ImpXml;
        public decimal mp_nfeCofinsOutrBcVlr_ImpXml
        {
            get { return fmp_nfeCofinsOutrBcVlr_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsOutrBcVlr_ImpXml), ref fmp_nfeCofinsOutrBcVlr_ImpXml, value); }
        }
        decimal fmp_nfeCofinsOutrAliq;
        public decimal mp_nfeCofinsOutrAliq
        {
            get { return fmp_nfeCofinsOutrAliq; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsOutrAliq), ref fmp_nfeCofinsOutrAliq, value); }
        }
        decimal fmp_nfeCofinsOutrAliq_ImpXml;
        public decimal mp_nfeCofinsOutrAliq_ImpXml
        {
            get { return fmp_nfeCofinsOutrAliq_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsOutrAliq_ImpXml), ref fmp_nfeCofinsOutrAliq_ImpXml, value); }
        }
        decimal fmp_nfeCofinsOutrBcProd;
        public decimal mp_nfeCofinsOutrBcProd
        {
            get { return fmp_nfeCofinsOutrBcProd; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsOutrBcProd), ref fmp_nfeCofinsOutrBcProd, value); }
        }
        decimal fmp_nfeCofinsOutrBcProd_ImpXml;
        public decimal mp_nfeCofinsOutrBcProd_ImpXml
        {
            get { return fmp_nfeCofinsOutrBcProd_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsOutrBcProd_ImpXml), ref fmp_nfeCofinsOutrBcProd_ImpXml, value); }
        }
        decimal fmp_nfeCofinsOutrAliqProd;
        public decimal mp_nfeCofinsOutrAliqProd
        {
            get { return fmp_nfeCofinsOutrAliqProd; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsOutrAliqProd), ref fmp_nfeCofinsOutrAliqProd, value); }
        }
        decimal fmp_nfeCofinsOutrVlr;
        public decimal mp_nfeCofinsOutrVlr
        {
            get { return fmp_nfeCofinsOutrVlr; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsOutrVlr), ref fmp_nfeCofinsOutrVlr, value); }
        }
        decimal fmp_nfeCofinsOutrVlr_ImpXml;
        public decimal mp_nfeCofinsOutrVlr_ImpXml
        {
            get { return fmp_nfeCofinsOutrVlr_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsOutrVlr_ImpXml), ref fmp_nfeCofinsOutrVlr_ImpXml, value); }
        }
        decimal fmp_nfeCofinsVlrBcST;
        public decimal mp_nfeCofinsVlrBcST
        {
            get { return fmp_nfeCofinsVlrBcST; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsVlrBcST), ref fmp_nfeCofinsVlrBcST, value); }
        }
        decimal fmp_nfeCofinsVlrBcST_ImpXml;
        public decimal mp_nfeCofinsVlrBcST_ImpXml
        {
            get { return fmp_nfeCofinsVlrBcST_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsVlrBcST_ImpXml), ref fmp_nfeCofinsVlrBcST_ImpXml, value); }
        }
        decimal fmp_nfeCofinsAliqST;
        public decimal mp_nfeCofinsAliqST
        {
            get { return fmp_nfeCofinsAliqST; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsAliqST), ref fmp_nfeCofinsAliqST, value); }
        }
        decimal fmp_nfeCofinsQtdeBcProdST;
        public decimal mp_nfeCofinsQtdeBcProdST
        {
            get { return fmp_nfeCofinsQtdeBcProdST; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsQtdeBcProdST), ref fmp_nfeCofinsQtdeBcProdST, value); }
        }
        decimal fmp_nfeCofinsQtdeBcProdST_ImpXml;
        public decimal mp_nfeCofinsQtdeBcProdST_ImpXml
        {
            get { return fmp_nfeCofinsQtdeBcProdST_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsQtdeBcProdST_ImpXml), ref fmp_nfeCofinsQtdeBcProdST_ImpXml, value); }
        }
        decimal fmp_nfeCofinsAliqProdST;
        public decimal mp_nfeCofinsAliqProdST
        {
            get { return fmp_nfeCofinsAliqProdST; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsAliqProdST), ref fmp_nfeCofinsAliqProdST, value); }
        }
        decimal fmp_nfeCofinsVlrST;
        public decimal mp_nfeCofinsVlrST
        {
            get { return fmp_nfeCofinsVlrST; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsVlrST), ref fmp_nfeCofinsVlrST, value); }
        }
        decimal fmp_nfeCofinsVlrST_ImpXml;
        public decimal mp_nfeCofinsVlrST_ImpXml
        {
            get { return fmp_nfeCofinsVlrST_ImpXml; }
            set { SetPropertyValue<decimal>(nameof(mp_nfeCofinsVlrST_ImpXml), ref fmp_nfeCofinsVlrST_ImpXml, value); }
        }
        decimal fmp_qtdAud;
        public decimal mp_qtdAud
        {
            get { return fmp_qtdAud; }
            set { SetPropertyValue<decimal>(nameof(mp_qtdAud), ref fmp_qtdAud, value); }
        }
        tb_movimentacao ffk_tb_movimentacao;
        [Association(@"tb_movimentacao_produtoReferencestb_movimentacao")]
        public tb_movimentacao fk_tb_movimentacao
        {
            get { return ffk_tb_movimentacao; }
            set { SetPropertyValue<tb_movimentacao>(nameof(fk_tb_movimentacao), ref ffk_tb_movimentacao, value); }
        }
        long ffk_tb_ncm;
        public long fk_tb_ncm
        {
            get { return ffk_tb_ncm; }
            set { SetPropertyValue<long>(nameof(fk_tb_ncm), ref ffk_tb_ncm, value); }
        }
        tb_ator ffk_tb_atorAtend;
        [Association(@"tb_movimentacao_produtoReferencestb_ator")]
        public tb_ator fk_tb_atorAtend
        {
            get { return ffk_tb_atorAtend; }
            set { SetPropertyValue<tb_ator>(nameof(fk_tb_atorAtend), ref ffk_tb_atorAtend, value); }
        }
        tb_produto ffk_tb_produto;
        [Association(@"tb_movimentacao_produtoReferencestb_produto")]
        public tb_produto fk_tb_produto
        {
            get { return ffk_tb_produto; }
            set { SetPropertyValue<tb_produto>(nameof(fk_tb_produto), ref ffk_tb_produto, value); }
        }
    }

}
