//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplicationPDV.bancoSQLite
{

    public partial class tb_pdv : XPLiteObject
    {
        long fid_pdv;
        [Key(AutoGenerate = true)]
        public long id_pdv
        {
            get { return fid_pdv; }
            set { SetPropertyValue<long>(nameof(id_pdv), ref fid_pdv, value); }
        }
        string fpdv_serv;
        [Size(300)]
        public string pdv_serv
        {
            get { return fpdv_serv; }
            set { SetPropertyValue<string>(nameof(pdv_serv), ref fpdv_serv, value); }
        }
        string fpdv_host;
        [Size(300)]
        public string pdv_host
        {
            get { return fpdv_host; }
            set { SetPropertyValue<string>(nameof(pdv_host), ref fpdv_host, value); }
        }
        DateTime fpdv_dtCri;
        public DateTime pdv_dtCri
        {
            get { return fpdv_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(pdv_dtCri), ref fpdv_dtCri, value); }
        }
        DateTime fpdv_dtAlt;
        public DateTime pdv_dtAlt
        {
            get { return fpdv_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(pdv_dtAlt), ref fpdv_dtAlt, value); }
        }
        DateTime fpdv_dtAcs;
        public DateTime pdv_dtAcs
        {
            get { return fpdv_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(pdv_dtAcs), ref fpdv_dtAcs, value); }
        }
        decimal fpdv_desat;
        public decimal pdv_desat
        {
            get { return fpdv_desat; }
            set { SetPropertyValue<decimal>(nameof(pdv_desat), ref fpdv_desat, value); }
        }
        short fpdv_pdvNum;
        public short pdv_pdvNum
        {
            get { return fpdv_pdvNum; }
            set { SetPropertyValue<short>(nameof(pdv_pdvNum), ref fpdv_pdvNum, value); }
        }
        short fpdv_nfeHomSerie;
        public short pdv_nfeHomSerie
        {
            get { return fpdv_nfeHomSerie; }
            set { SetPropertyValue<short>(nameof(pdv_nfeHomSerie), ref fpdv_nfeHomSerie, value); }
        }
        long fpdv_nfeHomNum;
        public long pdv_nfeHomNum
        {
            get { return fpdv_nfeHomNum; }
            set { SetPropertyValue<long>(nameof(pdv_nfeHomNum), ref fpdv_nfeHomNum, value); }
        }
        short fpdv_nfeProdSerie;
        public short pdv_nfeProdSerie
        {
            get { return fpdv_nfeProdSerie; }
            set { SetPropertyValue<short>(nameof(pdv_nfeProdSerie), ref fpdv_nfeProdSerie, value); }
        }
        long fpdv_nfeProdNum;
        public long pdv_nfeProdNum
        {
            get { return fpdv_nfeProdNum; }
            set { SetPropertyValue<long>(nameof(pdv_nfeProdNum), ref fpdv_nfeProdNum, value); }
        }
        string fpdv_dskCaption;
        [Size(64)]
        public string pdv_dskCaption
        {
            get { return fpdv_dskCaption; }
            set { SetPropertyValue<string>(nameof(pdv_dskCaption), ref fpdv_dskCaption, value); }
        }
        decimal fpdv_dskIndex;
        public decimal pdv_dskIndex
        {
            get { return fpdv_dskIndex; }
            set { SetPropertyValue<decimal>(nameof(pdv_dskIndex), ref fpdv_dskIndex, value); }
        }
        string fpdv_dskSerialNumber;
        [Size(128)]
        public string pdv_dskSerialNumber
        {
            get { return fpdv_dskSerialNumber; }
            set { SetPropertyValue<string>(nameof(pdv_dskSerialNumber), ref fpdv_dskSerialNumber, value); }
        }
        decimal fpdv_dskSignature;
        public decimal pdv_dskSignature
        {
            get { return fpdv_dskSignature; }
            set { SetPropertyValue<decimal>(nameof(pdv_dskSignature), ref fpdv_dskSignature, value); }
        }
        decimal fpdv_dskSize;
        public decimal pdv_dskSize
        {
            get { return fpdv_dskSize; }
            set { SetPropertyValue<decimal>(nameof(pdv_dskSize), ref fpdv_dskSize, value); }
        }
        string fpdv_dskStatus;
        [Size(10)]
        public string pdv_dskStatus
        {
            get { return fpdv_dskStatus; }
            set { SetPropertyValue<string>(nameof(pdv_dskStatus), ref fpdv_dskStatus, value); }
        }
        string fpdv_nicAdapterType;
        [Size(64)]
        public string pdv_nicAdapterType
        {
            get { return fpdv_nicAdapterType; }
            set { SetPropertyValue<string>(nameof(pdv_nicAdapterType), ref fpdv_nicAdapterType, value); }
        }
        decimal fpdv_nicAdapterTypeID;
        public decimal pdv_nicAdapterTypeID
        {
            get { return fpdv_nicAdapterTypeID; }
            set { SetPropertyValue<decimal>(nameof(pdv_nicAdapterTypeID), ref fpdv_nicAdapterTypeID, value); }
        }
        string fpdv_nicCaption;
        [Size(64)]
        public string pdv_nicCaption
        {
            get { return fpdv_nicCaption; }
            set { SetPropertyValue<string>(nameof(pdv_nicCaption), ref fpdv_nicCaption, value); }
        }
        string fpdv_nicDescription;
        [Size(128)]
        public string pdv_nicDescription
        {
            get { return fpdv_nicDescription; }
            set { SetPropertyValue<string>(nameof(pdv_nicDescription), ref fpdv_nicDescription, value); }
        }
        decimal fpdv_nicInterfaceIndex;
        public decimal pdv_nicInterfaceIndex
        {
            get { return fpdv_nicInterfaceIndex; }
            set { SetPropertyValue<decimal>(nameof(pdv_nicInterfaceIndex), ref fpdv_nicInterfaceIndex, value); }
        }
        string fpdv_nicMacAddress;
        [Size(32)]
        public string pdv_nicMacAddress
        {
            get { return fpdv_nicMacAddress; }
            set { SetPropertyValue<string>(nameof(pdv_nicMacAddress), ref fpdv_nicMacAddress, value); }
        }
        string fpdv_nicMacAddressVpn;
        [Size(32)]
        public string pdv_nicMacAddressVpn
        {
            get { return fpdv_nicMacAddressVpn; }
            set { SetPropertyValue<string>(nameof(pdv_nicMacAddressVpn), ref fpdv_nicMacAddressVpn, value); }
        }
        string fpdv_nicManufacturer;
        [Size(64)]
        public string pdv_nicManufacturer
        {
            get { return fpdv_nicManufacturer; }
            set { SetPropertyValue<string>(nameof(pdv_nicManufacturer), ref fpdv_nicManufacturer, value); }
        }
        string fpdv_nicName;
        [Size(128)]
        public string pdv_nicName
        {
            get { return fpdv_nicName; }
            set { SetPropertyValue<string>(nameof(pdv_nicName), ref fpdv_nicName, value); }
        }
        decimal fpdv_nicNetEnabled;
        public decimal pdv_nicNetEnabled
        {
            get { return fpdv_nicNetEnabled; }
            set { SetPropertyValue<decimal>(nameof(pdv_nicNetEnabled), ref fpdv_nicNetEnabled, value); }
        }
        decimal fpdv_nicSpeed;
        public decimal pdv_nicSpeed
        {
            get { return fpdv_nicSpeed; }
            set { SetPropertyValue<decimal>(nameof(pdv_nicSpeed), ref fpdv_nicSpeed, value); }
        }
        decimal fpdv_nicCfgDHCPEnabled;
        public decimal pdv_nicCfgDHCPEnabled
        {
            get { return fpdv_nicCfgDHCPEnabled; }
            set { SetPropertyValue<decimal>(nameof(pdv_nicCfgDHCPEnabled), ref fpdv_nicCfgDHCPEnabled, value); }
        }
        string fpdv_nicCfgDHCPServer;
        [Size(48)]
        public string pdv_nicCfgDHCPServer
        {
            get { return fpdv_nicCfgDHCPServer; }
            set { SetPropertyValue<string>(nameof(pdv_nicCfgDHCPServer), ref fpdv_nicCfgDHCPServer, value); }
        }
        string fpdv_nicCfgDNSDomain;
        [Size(255)]
        public string pdv_nicCfgDNSDomain
        {
            get { return fpdv_nicCfgDNSDomain; }
            set { SetPropertyValue<string>(nameof(pdv_nicCfgDNSDomain), ref fpdv_nicCfgDNSDomain, value); }
        }
        string fpdv_nicCfgIPAddress;
        [Size(SizeAttribute.Unlimited)]
        public string pdv_nicCfgIPAddress
        {
            get { return fpdv_nicCfgIPAddress; }
            set { SetPropertyValue<string>(nameof(pdv_nicCfgIPAddress), ref fpdv_nicCfgIPAddress, value); }
        }
        string fpdv_nicCfgIPAddressVpn;
        [Size(SizeAttribute.Unlimited)]
        public string pdv_nicCfgIPAddressVpn
        {
            get { return fpdv_nicCfgIPAddressVpn; }
            set { SetPropertyValue<string>(nameof(pdv_nicCfgIPAddressVpn), ref fpdv_nicCfgIPAddressVpn, value); }
        }
        decimal fpdv_nicCfgIPConnectionMetric;
        public decimal pdv_nicCfgIPConnectionMetric
        {
            get { return fpdv_nicCfgIPConnectionMetric; }
            set { SetPropertyValue<decimal>(nameof(pdv_nicCfgIPConnectionMetric), ref fpdv_nicCfgIPConnectionMetric, value); }
        }
        decimal fpdv_nicCfgIPEnabled;
        public decimal pdv_nicCfgIPEnabled
        {
            get { return fpdv_nicCfgIPEnabled; }
            set { SetPropertyValue<decimal>(nameof(pdv_nicCfgIPEnabled), ref fpdv_nicCfgIPEnabled, value); }
        }
        decimal fpdv_pcPgFlAllocatedBaseSize;
        public decimal pdv_pcPgFlAllocatedBaseSize
        {
            get { return fpdv_pcPgFlAllocatedBaseSize; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPgFlAllocatedBaseSize), ref fpdv_pcPgFlAllocatedBaseSize, value); }
        }
        decimal fpdv_pcPgFlCurrentUsage;
        public decimal pdv_pcPgFlCurrentUsage
        {
            get { return fpdv_pcPgFlCurrentUsage; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPgFlCurrentUsage), ref fpdv_pcPgFlCurrentUsage, value); }
        }
        decimal fpdv_pcPgFlPeakUsage;
        public decimal pdv_pcPgFlPeakUsage
        {
            get { return fpdv_pcPgFlPeakUsage; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPgFlPeakUsage), ref fpdv_pcPgFlPeakUsage, value); }
        }
        string fpdv_pcPowInstanceID;
        [Size(60)]
        public string pdv_pcPowInstanceID
        {
            get { return fpdv_pcPowInstanceID; }
            set { SetPropertyValue<string>(nameof(pdv_pcPowInstanceID), ref fpdv_pcPowInstanceID, value); }
        }
        string fpdv_pcPowElementName;
        [Size(60)]
        public string pdv_pcPowElementName
        {
            get { return fpdv_pcPowElementName; }
            set { SetPropertyValue<string>(nameof(pdv_pcPowElementName), ref fpdv_pcPowElementName, value); }
        }
        string fpdv_pcLdCaption;
        [Size(60)]
        public string pdv_pcLdCaption
        {
            get { return fpdv_pcLdCaption; }
            set { SetPropertyValue<string>(nameof(pdv_pcLdCaption), ref fpdv_pcLdCaption, value); }
        }
        decimal fpdv_pcLdCompressed;
        public decimal pdv_pcLdCompressed
        {
            get { return fpdv_pcLdCompressed; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcLdCompressed), ref fpdv_pcLdCompressed, value); }
        }
        decimal fpdv_pcLdConfigManagerErrorCode;
        public decimal pdv_pcLdConfigManagerErrorCode
        {
            get { return fpdv_pcLdConfigManagerErrorCode; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcLdConfigManagerErrorCode), ref fpdv_pcLdConfigManagerErrorCode, value); }
        }
        string fpdv_pcLdDeviceID;
        [Size(60)]
        public string pdv_pcLdDeviceID
        {
            get { return fpdv_pcLdDeviceID; }
            set { SetPropertyValue<string>(nameof(pdv_pcLdDeviceID), ref fpdv_pcLdDeviceID, value); }
        }
        decimal fpdv_pcLdDriveType;
        public decimal pdv_pcLdDriveType
        {
            get { return fpdv_pcLdDriveType; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcLdDriveType), ref fpdv_pcLdDriveType, value); }
        }
        string fpdv_pcLdFileSystem;
        [Size(20)]
        public string pdv_pcLdFileSystem
        {
            get { return fpdv_pcLdFileSystem; }
            set { SetPropertyValue<string>(nameof(pdv_pcLdFileSystem), ref fpdv_pcLdFileSystem, value); }
        }
        decimal fpdv_pcLdFreeSpace;
        public decimal pdv_pcLdFreeSpace
        {
            get { return fpdv_pcLdFreeSpace; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcLdFreeSpace), ref fpdv_pcLdFreeSpace, value); }
        }
        decimal fpdv_pcLdLastErrorCode;
        public decimal pdv_pcLdLastErrorCode
        {
            get { return fpdv_pcLdLastErrorCode; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcLdLastErrorCode), ref fpdv_pcLdLastErrorCode, value); }
        }
        string fpdv_pcLdName;
        [Size(64)]
        public string pdv_pcLdName
        {
            get { return fpdv_pcLdName; }
            set { SetPropertyValue<string>(nameof(pdv_pcLdName), ref fpdv_pcLdName, value); }
        }
        decimal fpdv_pcLdSize;
        public decimal pdv_pcLdSize
        {
            get { return fpdv_pcLdSize; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcLdSize), ref fpdv_pcLdSize, value); }
        }
        decimal fpdv_pcLdVolumeDirty;
        public decimal pdv_pcLdVolumeDirty
        {
            get { return fpdv_pcLdVolumeDirty; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcLdVolumeDirty), ref fpdv_pcLdVolumeDirty, value); }
        }
        string fpdv_pcLdVolumeSerialNumber;
        [Size(60)]
        public string pdv_pcLdVolumeSerialNumber
        {
            get { return fpdv_pcLdVolumeSerialNumber; }
            set { SetPropertyValue<string>(nameof(pdv_pcLdVolumeSerialNumber), ref fpdv_pcLdVolumeSerialNumber, value); }
        }
        decimal fpdv_pcAutomaticManagedPagefile;
        public decimal pdv_pcAutomaticManagedPagefile
        {
            get { return fpdv_pcAutomaticManagedPagefile; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcAutomaticManagedPagefile), ref fpdv_pcAutomaticManagedPagefile, value); }
        }
        decimal fpdv_pcAutomaticResetBootOption;
        public decimal pdv_pcAutomaticResetBootOption
        {
            get { return fpdv_pcAutomaticResetBootOption; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcAutomaticResetBootOption), ref fpdv_pcAutomaticResetBootOption, value); }
        }
        decimal fpdv_pcAutomaticResetCapability;
        public decimal pdv_pcAutomaticResetCapability
        {
            get { return fpdv_pcAutomaticResetCapability; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcAutomaticResetCapability), ref fpdv_pcAutomaticResetCapability, value); }
        }
        decimal fpdv_pcBootROMSupported;
        public decimal pdv_pcBootROMSupported
        {
            get { return fpdv_pcBootROMSupported; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcBootROMSupported), ref fpdv_pcBootROMSupported, value); }
        }
        string fpdv_pcBootupState;
        [Size(50)]
        public string pdv_pcBootupState
        {
            get { return fpdv_pcBootupState; }
            set { SetPropertyValue<string>(nameof(pdv_pcBootupState), ref fpdv_pcBootupState, value); }
        }
        short fpdv_pcCurrentTimeZone;
        public short pdv_pcCurrentTimeZone
        {
            get { return fpdv_pcCurrentTimeZone; }
            set { SetPropertyValue<short>(nameof(pdv_pcCurrentTimeZone), ref fpdv_pcCurrentTimeZone, value); }
        }
        decimal fpdv_pcDaylightInEffect;
        public decimal pdv_pcDaylightInEffect
        {
            get { return fpdv_pcDaylightInEffect; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcDaylightInEffect), ref fpdv_pcDaylightInEffect, value); }
        }
        string fpdv_pcDNSHostName;
        [Size(255)]
        public string pdv_pcDNSHostName
        {
            get { return fpdv_pcDNSHostName; }
            set { SetPropertyValue<string>(nameof(pdv_pcDNSHostName), ref fpdv_pcDNSHostName, value); }
        }
        decimal fpdv_pcDomainRole;
        public decimal pdv_pcDomainRole
        {
            get { return fpdv_pcDomainRole; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcDomainRole), ref fpdv_pcDomainRole, value); }
        }
        decimal fpdv_pcEnableDaylightSavingsTime;
        public decimal pdv_pcEnableDaylightSavingsTime
        {
            get { return fpdv_pcEnableDaylightSavingsTime; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcEnableDaylightSavingsTime), ref fpdv_pcEnableDaylightSavingsTime, value); }
        }
        decimal fpdv_pcHypervisorPresent;
        public decimal pdv_pcHypervisorPresent
        {
            get { return fpdv_pcHypervisorPresent; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcHypervisorPresent), ref fpdv_pcHypervisorPresent, value); }
        }
        string fpdv_pcManufacturer;
        [Size(50)]
        public string pdv_pcManufacturer
        {
            get { return fpdv_pcManufacturer; }
            set { SetPropertyValue<string>(nameof(pdv_pcManufacturer), ref fpdv_pcManufacturer, value); }
        }
        decimal fpdv_pcNetworkServerModeEnabled;
        public decimal pdv_pcNetworkServerModeEnabled
        {
            get { return fpdv_pcNetworkServerModeEnabled; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcNetworkServerModeEnabled), ref fpdv_pcNetworkServerModeEnabled, value); }
        }
        decimal fpdv_pcNumberOfLogicalProcessors;
        public decimal pdv_pcNumberOfLogicalProcessors
        {
            get { return fpdv_pcNumberOfLogicalProcessors; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcNumberOfLogicalProcessors), ref fpdv_pcNumberOfLogicalProcessors, value); }
        }
        decimal fpdv_pcNumberOfProcessors;
        public decimal pdv_pcNumberOfProcessors
        {
            get { return fpdv_pcNumberOfProcessors; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcNumberOfProcessors), ref fpdv_pcNumberOfProcessors, value); }
        }
        decimal fpdv_pcPCSystemType;
        public decimal pdv_pcPCSystemType
        {
            get { return fpdv_pcPCSystemType; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPCSystemType), ref fpdv_pcPCSystemType, value); }
        }
        decimal fpdv_pcTotalPhysicalMemory;
        public decimal pdv_pcTotalPhysicalMemory
        {
            get { return fpdv_pcTotalPhysicalMemory; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcTotalPhysicalMemory), ref fpdv_pcTotalPhysicalMemory, value); }
        }
        string fpdv_pcUserName;
        [Size(255)]
        public string pdv_pcUserName
        {
            get { return fpdv_pcUserName; }
            set { SetPropertyValue<string>(nameof(pdv_pcUserName), ref fpdv_pcUserName, value); }
        }
        decimal fpdv_pcWakeUpType;
        public decimal pdv_pcWakeUpType
        {
            get { return fpdv_pcWakeUpType; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcWakeUpType), ref fpdv_pcWakeUpType, value); }
        }
        string fpdv_biosCaption;
        [Size(64)]
        public string pdv_biosCaption
        {
            get { return fpdv_biosCaption; }
            set { SetPropertyValue<string>(nameof(pdv_biosCaption), ref fpdv_biosCaption, value); }
        }
        string fpdv_biosSerialNumber;
        [Size(64)]
        public string pdv_biosSerialNumber
        {
            get { return fpdv_biosSerialNumber; }
            set { SetPropertyValue<string>(nameof(pdv_biosSerialNumber), ref fpdv_biosSerialNumber, value); }
        }
        string fpdv_biosSMBIOSBIOSVersion;
        [Size(64)]
        public string pdv_biosSMBIOSBIOSVersion
        {
            get { return fpdv_biosSMBIOSBIOSVersion; }
            set { SetPropertyValue<string>(nameof(pdv_biosSMBIOSBIOSVersion), ref fpdv_biosSMBIOSBIOSVersion, value); }
        }
        string fpdv_biosSoftwareElementID;
        [Size(256)]
        public string pdv_biosSoftwareElementID
        {
            get { return fpdv_biosSoftwareElementID; }
            set { SetPropertyValue<string>(nameof(pdv_biosSoftwareElementID), ref fpdv_biosSoftwareElementID, value); }
        }
        string fpdv_boardManufacturer;
        [Size(256)]
        public string pdv_boardManufacturer
        {
            get { return fpdv_boardManufacturer; }
            set { SetPropertyValue<string>(nameof(pdv_boardManufacturer), ref fpdv_boardManufacturer, value); }
        }
        string fpdv_boardProduct;
        [Size(64)]
        public string pdv_boardProduct
        {
            get { return fpdv_boardProduct; }
            set { SetPropertyValue<string>(nameof(pdv_boardProduct), ref fpdv_boardProduct, value); }
        }
        string fpdv_boardSerialNumber;
        [Size(64)]
        public string pdv_boardSerialNumber
        {
            get { return fpdv_boardSerialNumber; }
            set { SetPropertyValue<string>(nameof(pdv_boardSerialNumber), ref fpdv_boardSerialNumber, value); }
        }
        string fpdv_boardStatus;
        [Size(10)]
        public string pdv_boardStatus
        {
            get { return fpdv_boardStatus; }
            set { SetPropertyValue<string>(nameof(pdv_boardStatus), ref fpdv_boardStatus, value); }
        }
        string fpdv_boardVersion;
        [Size(64)]
        public string pdv_boardVersion
        {
            get { return fpdv_boardVersion; }
            set { SetPropertyValue<string>(nameof(pdv_boardVersion), ref fpdv_boardVersion, value); }
        }
        string fpdv_pcOsBuildNumber;
        [Size(10)]
        public string pdv_pcOsBuildNumber
        {
            get { return fpdv_pcOsBuildNumber; }
            set { SetPropertyValue<string>(nameof(pdv_pcOsBuildNumber), ref fpdv_pcOsBuildNumber, value); }
        }
        string fpdv_pcOsCaption;
        [Size(64)]
        public string pdv_pcOsCaption
        {
            get { return fpdv_pcOsCaption; }
            set { SetPropertyValue<string>(nameof(pdv_pcOsCaption), ref fpdv_pcOsCaption, value); }
        }
        string fpdv_pcOsCodeSet;
        [Size(6)]
        public string pdv_pcOsCodeSet
        {
            get { return fpdv_pcOsCodeSet; }
            set { SetPropertyValue<string>(nameof(pdv_pcOsCodeSet), ref fpdv_pcOsCodeSet, value); }
        }
        string fpdv_pcOsCountryCode;
        [Size(256)]
        public string pdv_pcOsCountryCode
        {
            get { return fpdv_pcOsCountryCode; }
            set { SetPropertyValue<string>(nameof(pdv_pcOsCountryCode), ref fpdv_pcOsCountryCode, value); }
        }
        decimal fpdv_pcOsCurrentTimeZone;
        public decimal pdv_pcOsCurrentTimeZone
        {
            get { return fpdv_pcOsCurrentTimeZone; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsCurrentTimeZone), ref fpdv_pcOsCurrentTimeZone, value); }
        }
        decimal fpdv_pcOsFreePhysicalMemory;
        public decimal pdv_pcOsFreePhysicalMemory
        {
            get { return fpdv_pcOsFreePhysicalMemory; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsFreePhysicalMemory), ref fpdv_pcOsFreePhysicalMemory, value); }
        }
        decimal fpdv_pcOsFreeSpaceInPagingFiles;
        public decimal pdv_pcOsFreeSpaceInPagingFiles
        {
            get { return fpdv_pcOsFreeSpaceInPagingFiles; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsFreeSpaceInPagingFiles), ref fpdv_pcOsFreeSpaceInPagingFiles, value); }
        }
        decimal fpdv_pcOsFreeVirtualMemory;
        public decimal pdv_pcOsFreeVirtualMemory
        {
            get { return fpdv_pcOsFreeVirtualMemory; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsFreeVirtualMemory), ref fpdv_pcOsFreeVirtualMemory, value); }
        }
        DateTime fpdv_pcOsInstallDate;
        public DateTime pdv_pcOsInstallDate
        {
            get { return fpdv_pcOsInstallDate; }
            set { SetPropertyValue<DateTime>(nameof(pdv_pcOsInstallDate), ref fpdv_pcOsInstallDate, value); }
        }
        DateTime fpdv_pcOsLastBootUpTime;
        public DateTime pdv_pcOsLastBootUpTime
        {
            get { return fpdv_pcOsLastBootUpTime; }
            set { SetPropertyValue<DateTime>(nameof(pdv_pcOsLastBootUpTime), ref fpdv_pcOsLastBootUpTime, value); }
        }
        DateTime fpdv_pcOsLocalDateTime;
        public DateTime pdv_pcOsLocalDateTime
        {
            get { return fpdv_pcOsLocalDateTime; }
            set { SetPropertyValue<DateTime>(nameof(pdv_pcOsLocalDateTime), ref fpdv_pcOsLocalDateTime, value); }
        }
        string fpdv_pcOsLocale;
        [Size(6)]
        public string pdv_pcOsLocale
        {
            get { return fpdv_pcOsLocale; }
            set { SetPropertyValue<string>(nameof(pdv_pcOsLocale), ref fpdv_pcOsLocale, value); }
        }
        decimal fpdv_pcOsNumberOfProcesses;
        public decimal pdv_pcOsNumberOfProcesses
        {
            get { return fpdv_pcOsNumberOfProcesses; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsNumberOfProcesses), ref fpdv_pcOsNumberOfProcesses, value); }
        }
        decimal fpdv_pcOsNumberOfUsers;
        public decimal pdv_pcOsNumberOfUsers
        {
            get { return fpdv_pcOsNumberOfUsers; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsNumberOfUsers), ref fpdv_pcOsNumberOfUsers, value); }
        }
        decimal fpdv_pcOsOperatingSystemSKU;
        public decimal pdv_pcOsOperatingSystemSKU
        {
            get { return fpdv_pcOsOperatingSystemSKU; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsOperatingSystemSKU), ref fpdv_pcOsOperatingSystemSKU, value); }
        }
        string fpdv_pcOSArchitecture;
        [Size(10)]
        public string pdv_pcOSArchitecture
        {
            get { return fpdv_pcOSArchitecture; }
            set { SetPropertyValue<string>(nameof(pdv_pcOSArchitecture), ref fpdv_pcOSArchitecture, value); }
        }
        decimal fpdv_pcOSLanguage;
        public decimal pdv_pcOSLanguage
        {
            get { return fpdv_pcOSLanguage; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOSLanguage), ref fpdv_pcOSLanguage, value); }
        }
        decimal fpdv_pcOSProductSuite;
        public decimal pdv_pcOSProductSuite
        {
            get { return fpdv_pcOSProductSuite; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOSProductSuite), ref fpdv_pcOSProductSuite, value); }
        }
        decimal fpdv_pcOsPortableOperatingSystem;
        public decimal pdv_pcOsPortableOperatingSystem
        {
            get { return fpdv_pcOsPortableOperatingSystem; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsPortableOperatingSystem), ref fpdv_pcOsPortableOperatingSystem, value); }
        }
        decimal fpdv_pcOsPrimary;
        public decimal pdv_pcOsPrimary
        {
            get { return fpdv_pcOsPrimary; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsPrimary), ref fpdv_pcOsPrimary, value); }
        }
        decimal fpdv_pcOsProductType;
        public decimal pdv_pcOsProductType
        {
            get { return fpdv_pcOsProductType; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsProductType), ref fpdv_pcOsProductType, value); }
        }
        string fpdv_pcOsRegisteredUser;
        public string pdv_pcOsRegisteredUser
        {
            get { return fpdv_pcOsRegisteredUser; }
            set { SetPropertyValue<string>(nameof(pdv_pcOsRegisteredUser), ref fpdv_pcOsRegisteredUser, value); }
        }
        string fpdv_pcOsSerialNumber;
        [Size(50)]
        public string pdv_pcOsSerialNumber
        {
            get { return fpdv_pcOsSerialNumber; }
            set { SetPropertyValue<string>(nameof(pdv_pcOsSerialNumber), ref fpdv_pcOsSerialNumber, value); }
        }
        decimal fpdv_pcOsServicePackMajorVersion;
        public decimal pdv_pcOsServicePackMajorVersion
        {
            get { return fpdv_pcOsServicePackMajorVersion; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsServicePackMajorVersion), ref fpdv_pcOsServicePackMajorVersion, value); }
        }
        decimal fpdv_pcOsServicePackMinorVersion;
        public decimal pdv_pcOsServicePackMinorVersion
        {
            get { return fpdv_pcOsServicePackMinorVersion; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsServicePackMinorVersion), ref fpdv_pcOsServicePackMinorVersion, value); }
        }
        decimal fpdv_pcOsSizeStoredInPagingFiles;
        public decimal pdv_pcOsSizeStoredInPagingFiles
        {
            get { return fpdv_pcOsSizeStoredInPagingFiles; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsSizeStoredInPagingFiles), ref fpdv_pcOsSizeStoredInPagingFiles, value); }
        }
        decimal fpdv_pcOsSuiteMask;
        public decimal pdv_pcOsSuiteMask
        {
            get { return fpdv_pcOsSuiteMask; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsSuiteMask), ref fpdv_pcOsSuiteMask, value); }
        }
        string fpdv_pcOsSystemDrive;
        [Size(2)]
        public string pdv_pcOsSystemDrive
        {
            get { return fpdv_pcOsSystemDrive; }
            set { SetPropertyValue<string>(nameof(pdv_pcOsSystemDrive), ref fpdv_pcOsSystemDrive, value); }
        }
        decimal fpdv_pcOsTotalSwapSpaceSize;
        public decimal pdv_pcOsTotalSwapSpaceSize
        {
            get { return fpdv_pcOsTotalSwapSpaceSize; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsTotalSwapSpaceSize), ref fpdv_pcOsTotalSwapSpaceSize, value); }
        }
        decimal fpdv_pcOsTotalVirtualMemorySize;
        public decimal pdv_pcOsTotalVirtualMemorySize
        {
            get { return fpdv_pcOsTotalVirtualMemorySize; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsTotalVirtualMemorySize), ref fpdv_pcOsTotalVirtualMemorySize, value); }
        }
        decimal fpdv_pcOsTotalVisibleMemorySize;
        public decimal pdv_pcOsTotalVisibleMemorySize
        {
            get { return fpdv_pcOsTotalVisibleMemorySize; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcOsTotalVisibleMemorySize), ref fpdv_pcOsTotalVisibleMemorySize, value); }
        }
        string fpdv_pcOsVersion;
        [Size(20)]
        public string pdv_pcOsVersion
        {
            get { return fpdv_pcOsVersion; }
            set { SetPropertyValue<string>(nameof(pdv_pcOsVersion), ref fpdv_pcOsVersion, value); }
        }
        string fpdv_procHandle;
        [Size(256)]
        public string pdv_procHandle
        {
            get { return fpdv_procHandle; }
            set { SetPropertyValue<string>(nameof(pdv_procHandle), ref fpdv_procHandle, value); }
        }
        decimal fpdv_procHandleCount;
        public decimal pdv_procHandleCount
        {
            get { return fpdv_procHandleCount; }
            set { SetPropertyValue<decimal>(nameof(pdv_procHandleCount), ref fpdv_procHandleCount, value); }
        }
        decimal fpdv_procKernelModeTime;
        public decimal pdv_procKernelModeTime
        {
            get { return fpdv_procKernelModeTime; }
            set { SetPropertyValue<decimal>(nameof(pdv_procKernelModeTime), ref fpdv_procKernelModeTime, value); }
        }
        decimal fpdv_procOtherOperationCount;
        public decimal pdv_procOtherOperationCount
        {
            get { return fpdv_procOtherOperationCount; }
            set { SetPropertyValue<decimal>(nameof(pdv_procOtherOperationCount), ref fpdv_procOtherOperationCount, value); }
        }
        decimal fpdv_procOtherTransferCount;
        public decimal pdv_procOtherTransferCount
        {
            get { return fpdv_procOtherTransferCount; }
            set { SetPropertyValue<decimal>(nameof(pdv_procOtherTransferCount), ref fpdv_procOtherTransferCount, value); }
        }
        decimal fpdv_procPageFaults;
        public decimal pdv_procPageFaults
        {
            get { return fpdv_procPageFaults; }
            set { SetPropertyValue<decimal>(nameof(pdv_procPageFaults), ref fpdv_procPageFaults, value); }
        }
        decimal fpdv_procPageFileUsage;
        public decimal pdv_procPageFileUsage
        {
            get { return fpdv_procPageFileUsage; }
            set { SetPropertyValue<decimal>(nameof(pdv_procPageFileUsage), ref fpdv_procPageFileUsage, value); }
        }
        decimal fpdv_procPeakPageFileUsage;
        public decimal pdv_procPeakPageFileUsage
        {
            get { return fpdv_procPeakPageFileUsage; }
            set { SetPropertyValue<decimal>(nameof(pdv_procPeakPageFileUsage), ref fpdv_procPeakPageFileUsage, value); }
        }
        decimal fpdv_procPeakVirtualSize;
        public decimal pdv_procPeakVirtualSize
        {
            get { return fpdv_procPeakVirtualSize; }
            set { SetPropertyValue<decimal>(nameof(pdv_procPeakVirtualSize), ref fpdv_procPeakVirtualSize, value); }
        }
        decimal fpdv_procPeakWorkingSetSize;
        public decimal pdv_procPeakWorkingSetSize
        {
            get { return fpdv_procPeakWorkingSetSize; }
            set { SetPropertyValue<decimal>(nameof(pdv_procPeakWorkingSetSize), ref fpdv_procPeakWorkingSetSize, value); }
        }
        decimal fpdv_procPriority;
        public decimal pdv_procPriority
        {
            get { return fpdv_procPriority; }
            set { SetPropertyValue<decimal>(nameof(pdv_procPriority), ref fpdv_procPriority, value); }
        }
        decimal fpdv_procPrivatePageCount;
        public decimal pdv_procPrivatePageCount
        {
            get { return fpdv_procPrivatePageCount; }
            set { SetPropertyValue<decimal>(nameof(pdv_procPrivatePageCount), ref fpdv_procPrivatePageCount, value); }
        }
        decimal fpdv_procProcessId;
        public decimal pdv_procProcessId
        {
            get { return fpdv_procProcessId; }
            set { SetPropertyValue<decimal>(nameof(pdv_procProcessId), ref fpdv_procProcessId, value); }
        }
        decimal fpdv_procReadOperationCount;
        public decimal pdv_procReadOperationCount
        {
            get { return fpdv_procReadOperationCount; }
            set { SetPropertyValue<decimal>(nameof(pdv_procReadOperationCount), ref fpdv_procReadOperationCount, value); }
        }
        decimal fpdv_procReadTransferCount;
        public decimal pdv_procReadTransferCount
        {
            get { return fpdv_procReadTransferCount; }
            set { SetPropertyValue<decimal>(nameof(pdv_procReadTransferCount), ref fpdv_procReadTransferCount, value); }
        }
        decimal fpdv_procThreadCount;
        public decimal pdv_procThreadCount
        {
            get { return fpdv_procThreadCount; }
            set { SetPropertyValue<decimal>(nameof(pdv_procThreadCount), ref fpdv_procThreadCount, value); }
        }
        decimal fpdv_procUserModeTime;
        public decimal pdv_procUserModeTime
        {
            get { return fpdv_procUserModeTime; }
            set { SetPropertyValue<decimal>(nameof(pdv_procUserModeTime), ref fpdv_procUserModeTime, value); }
        }
        decimal fpdv_procVirtualSize;
        public decimal pdv_procVirtualSize
        {
            get { return fpdv_procVirtualSize; }
            set { SetPropertyValue<decimal>(nameof(pdv_procVirtualSize), ref fpdv_procVirtualSize, value); }
        }
        decimal fpdv_procWorkingSetSize;
        public decimal pdv_procWorkingSetSize
        {
            get { return fpdv_procWorkingSetSize; }
            set { SetPropertyValue<decimal>(nameof(pdv_procWorkingSetSize), ref fpdv_procWorkingSetSize, value); }
        }
        decimal fpdv_procWriteOperationCount;
        public decimal pdv_procWriteOperationCount
        {
            get { return fpdv_procWriteOperationCount; }
            set { SetPropertyValue<decimal>(nameof(pdv_procWriteOperationCount), ref fpdv_procWriteOperationCount, value); }
        }
        decimal fpdv_procWriteTransferCount;
        public decimal pdv_procWriteTransferCount
        {
            get { return fpdv_procWriteTransferCount; }
            set { SetPropertyValue<decimal>(nameof(pdv_procWriteTransferCount), ref fpdv_procWriteTransferCount, value); }
        }
        decimal fpdv_pcPrcAddressWidth;
        public decimal pdv_pcPrcAddressWidth
        {
            get { return fpdv_pcPrcAddressWidth; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcAddressWidth), ref fpdv_pcPrcAddressWidth, value); }
        }
        decimal fpdv_pcPrcArchitecture;
        public decimal pdv_pcPrcArchitecture
        {
            get { return fpdv_pcPrcArchitecture; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcArchitecture), ref fpdv_pcPrcArchitecture, value); }
        }
        decimal fpdv_pcPrcAvailability;
        public decimal pdv_pcPrcAvailability
        {
            get { return fpdv_pcPrcAvailability; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcAvailability), ref fpdv_pcPrcAvailability, value); }
        }
        string fpdv_pcPrcCaption;
        [Size(64)]
        public string pdv_pcPrcCaption
        {
            get { return fpdv_pcPrcCaption; }
            set { SetPropertyValue<string>(nameof(pdv_pcPrcCaption), ref fpdv_pcPrcCaption, value); }
        }
        decimal fpdv_pcPrcCharacteristics;
        public decimal pdv_pcPrcCharacteristics
        {
            get { return fpdv_pcPrcCharacteristics; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcCharacteristics), ref fpdv_pcPrcCharacteristics, value); }
        }
        decimal fpdv_pcPrcConfigManagerErrorCode;
        public decimal pdv_pcPrcConfigManagerErrorCode
        {
            get { return fpdv_pcPrcConfigManagerErrorCode; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcConfigManagerErrorCode), ref fpdv_pcPrcConfigManagerErrorCode, value); }
        }
        decimal fpdv_pcPrcConfigManagerUserConfig;
        public decimal pdv_pcPrcConfigManagerUserConfig
        {
            get { return fpdv_pcPrcConfigManagerUserConfig; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcConfigManagerUserConfig), ref fpdv_pcPrcConfigManagerUserConfig, value); }
        }
        decimal fpdv_pcPrcCpuStatus;
        public decimal pdv_pcPrcCpuStatus
        {
            get { return fpdv_pcPrcCpuStatus; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcCpuStatus), ref fpdv_pcPrcCpuStatus, value); }
        }
        decimal fpdv_pcPrcCurrentClockSpeed;
        public decimal pdv_pcPrcCurrentClockSpeed
        {
            get { return fpdv_pcPrcCurrentClockSpeed; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcCurrentClockSpeed), ref fpdv_pcPrcCurrentClockSpeed, value); }
        }
        decimal fpdv_pcPrcCurrentVoltage;
        public decimal pdv_pcPrcCurrentVoltage
        {
            get { return fpdv_pcPrcCurrentVoltage; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcCurrentVoltage), ref fpdv_pcPrcCurrentVoltage, value); }
        }
        decimal fpdv_pcPrcDataWidth;
        public decimal pdv_pcPrcDataWidth
        {
            get { return fpdv_pcPrcDataWidth; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcDataWidth), ref fpdv_pcPrcDataWidth, value); }
        }
        decimal fpdv_pcPrcExtClock;
        public decimal pdv_pcPrcExtClock
        {
            get { return fpdv_pcPrcExtClock; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcExtClock), ref fpdv_pcPrcExtClock, value); }
        }
        decimal fpdv_pcPrcFamily;
        public decimal pdv_pcPrcFamily
        {
            get { return fpdv_pcPrcFamily; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcFamily), ref fpdv_pcPrcFamily, value); }
        }
        decimal fpdv_pcPrcL2CacheSize;
        public decimal pdv_pcPrcL2CacheSize
        {
            get { return fpdv_pcPrcL2CacheSize; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcL2CacheSize), ref fpdv_pcPrcL2CacheSize, value); }
        }
        decimal fpdv_pcPrcL2CacheSpeed;
        public decimal pdv_pcPrcL2CacheSpeed
        {
            get { return fpdv_pcPrcL2CacheSpeed; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcL2CacheSpeed), ref fpdv_pcPrcL2CacheSpeed, value); }
        }
        decimal fpdv_pcPrcL3CacheSize;
        public decimal pdv_pcPrcL3CacheSize
        {
            get { return fpdv_pcPrcL3CacheSize; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcL3CacheSize), ref fpdv_pcPrcL3CacheSize, value); }
        }
        decimal fpdv_pcPrcL3CacheSpeed;
        public decimal pdv_pcPrcL3CacheSpeed
        {
            get { return fpdv_pcPrcL3CacheSpeed; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcL3CacheSpeed), ref fpdv_pcPrcL3CacheSpeed, value); }
        }
        decimal fpdv_pcPrcLevel;
        public decimal pdv_pcPrcLevel
        {
            get { return fpdv_pcPrcLevel; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcLevel), ref fpdv_pcPrcLevel, value); }
        }
        decimal fpdv_pcPrcLoadPercentage;
        public decimal pdv_pcPrcLoadPercentage
        {
            get { return fpdv_pcPrcLoadPercentage; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcLoadPercentage), ref fpdv_pcPrcLoadPercentage, value); }
        }
        decimal fpdv_pcPrcMaxClockSpeed;
        public decimal pdv_pcPrcMaxClockSpeed
        {
            get { return fpdv_pcPrcMaxClockSpeed; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcMaxClockSpeed), ref fpdv_pcPrcMaxClockSpeed, value); }
        }
        string fpdv_pcPrcName;
        public string pdv_pcPrcName
        {
            get { return fpdv_pcPrcName; }
            set { SetPropertyValue<string>(nameof(pdv_pcPrcName), ref fpdv_pcPrcName, value); }
        }
        decimal fpdv_pcPrcNumberOfCores;
        public decimal pdv_pcPrcNumberOfCores
        {
            get { return fpdv_pcPrcNumberOfCores; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcNumberOfCores), ref fpdv_pcPrcNumberOfCores, value); }
        }
        decimal fpdv_pcPrcNumberOfEnabledCore;
        public decimal pdv_pcPrcNumberOfEnabledCore
        {
            get { return fpdv_pcPrcNumberOfEnabledCore; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcNumberOfEnabledCore), ref fpdv_pcPrcNumberOfEnabledCore, value); }
        }
        decimal fpdv_pcPrcNumberOfLogicalProcessors;
        public decimal pdv_pcPrcNumberOfLogicalProcessors
        {
            get { return fpdv_pcPrcNumberOfLogicalProcessors; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcNumberOfLogicalProcessors), ref fpdv_pcPrcNumberOfLogicalProcessors, value); }
        }
        decimal fpdv_pcPrcPowerManagementSupported;
        public decimal pdv_pcPrcPowerManagementSupported
        {
            get { return fpdv_pcPrcPowerManagementSupported; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcPowerManagementSupported), ref fpdv_pcPrcPowerManagementSupported, value); }
        }
        string fpdv_pcPrcProcessorId;
        public string pdv_pcPrcProcessorId
        {
            get { return fpdv_pcPrcProcessorId; }
            set { SetPropertyValue<string>(nameof(pdv_pcPrcProcessorId), ref fpdv_pcPrcProcessorId, value); }
        }
        decimal fpdv_pcPrcProcessorType;
        public decimal pdv_pcPrcProcessorType
        {
            get { return fpdv_pcPrcProcessorType; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcProcessorType), ref fpdv_pcPrcProcessorType, value); }
        }
        decimal fpdv_pcPrcRevision;
        public decimal pdv_pcPrcRevision
        {
            get { return fpdv_pcPrcRevision; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcRevision), ref fpdv_pcPrcRevision, value); }
        }
        decimal fpdv_pcPrcSecondLevelAddressTranslationExtensions;
        public decimal pdv_pcPrcSecondLevelAddressTranslationExtensions
        {
            get { return fpdv_pcPrcSecondLevelAddressTranslationExtensions; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcSecondLevelAddressTranslationExtensions), ref fpdv_pcPrcSecondLevelAddressTranslationExtensions, value); }
        }
        string fpdv_pcPrcStatus;
        [Size(10)]
        public string pdv_pcPrcStatus
        {
            get { return fpdv_pcPrcStatus; }
            set { SetPropertyValue<string>(nameof(pdv_pcPrcStatus), ref fpdv_pcPrcStatus, value); }
        }
        decimal fpdv_pcPrcStatusInfo;
        public decimal pdv_pcPrcStatusInfo
        {
            get { return fpdv_pcPrcStatusInfo; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcStatusInfo), ref fpdv_pcPrcStatusInfo, value); }
        }
        string fpdv_pcPrcSystemName;
        [Size(255)]
        public string pdv_pcPrcSystemName
        {
            get { return fpdv_pcPrcSystemName; }
            set { SetPropertyValue<string>(nameof(pdv_pcPrcSystemName), ref fpdv_pcPrcSystemName, value); }
        }
        decimal fpdv_pcPrcThreadCount;
        public decimal pdv_pcPrcThreadCount
        {
            get { return fpdv_pcPrcThreadCount; }
            set { SetPropertyValue<decimal>(nameof(pdv_pcPrcThreadCount), ref fpdv_pcPrcThreadCount, value); }
        }
        decimal fpdv_gpuAdapterRAM;
        public decimal pdv_gpuAdapterRAM
        {
            get { return fpdv_gpuAdapterRAM; }
            set { SetPropertyValue<decimal>(nameof(pdv_gpuAdapterRAM), ref fpdv_gpuAdapterRAM, value); }
        }
        decimal fpdv_gpuAvailability;
        public decimal pdv_gpuAvailability
        {
            get { return fpdv_gpuAvailability; }
            set { SetPropertyValue<decimal>(nameof(pdv_gpuAvailability), ref fpdv_gpuAvailability, value); }
        }
        decimal fpdv_gpuConfigManagerErrorCode;
        public decimal pdv_gpuConfigManagerErrorCode
        {
            get { return fpdv_gpuConfigManagerErrorCode; }
            set { SetPropertyValue<decimal>(nameof(pdv_gpuConfigManagerErrorCode), ref fpdv_gpuConfigManagerErrorCode, value); }
        }
        decimal fpdv_gpuCurrentBitsPerPixel;
        public decimal pdv_gpuCurrentBitsPerPixel
        {
            get { return fpdv_gpuCurrentBitsPerPixel; }
            set { SetPropertyValue<decimal>(nameof(pdv_gpuCurrentBitsPerPixel), ref fpdv_gpuCurrentBitsPerPixel, value); }
        }
        decimal fpdv_gpuCurrentHorizontalResolution;
        public decimal pdv_gpuCurrentHorizontalResolution
        {
            get { return fpdv_gpuCurrentHorizontalResolution; }
            set { SetPropertyValue<decimal>(nameof(pdv_gpuCurrentHorizontalResolution), ref fpdv_gpuCurrentHorizontalResolution, value); }
        }
        decimal fpdv_gpuCurrentNumberOfColors;
        public decimal pdv_gpuCurrentNumberOfColors
        {
            get { return fpdv_gpuCurrentNumberOfColors; }
            set { SetPropertyValue<decimal>(nameof(pdv_gpuCurrentNumberOfColors), ref fpdv_gpuCurrentNumberOfColors, value); }
        }
        decimal fpdv_gpuCurrentRefreshRate;
        public decimal pdv_gpuCurrentRefreshRate
        {
            get { return fpdv_gpuCurrentRefreshRate; }
            set { SetPropertyValue<decimal>(nameof(pdv_gpuCurrentRefreshRate), ref fpdv_gpuCurrentRefreshRate, value); }
        }
        decimal fpdv_gpuCurrentScanMode;
        public decimal pdv_gpuCurrentScanMode
        {
            get { return fpdv_gpuCurrentScanMode; }
            set { SetPropertyValue<decimal>(nameof(pdv_gpuCurrentScanMode), ref fpdv_gpuCurrentScanMode, value); }
        }
        decimal fpdv_gpuCurrentVerticalResolution;
        public decimal pdv_gpuCurrentVerticalResolution
        {
            get { return fpdv_gpuCurrentVerticalResolution; }
            set { SetPropertyValue<decimal>(nameof(pdv_gpuCurrentVerticalResolution), ref fpdv_gpuCurrentVerticalResolution, value); }
        }
        decimal fpdv_gpuDitherType;
        public decimal pdv_gpuDitherType
        {
            get { return fpdv_gpuDitherType; }
            set { SetPropertyValue<decimal>(nameof(pdv_gpuDitherType), ref fpdv_gpuDitherType, value); }
        }
        string fpdv_gpuDriverVersion;
        [Size(50)]
        public string pdv_gpuDriverVersion
        {
            get { return fpdv_gpuDriverVersion; }
            set { SetPropertyValue<string>(nameof(pdv_gpuDriverVersion), ref fpdv_gpuDriverVersion, value); }
        }
        string fpdv_gpuStatus;
        [Size(10)]
        public string pdv_gpuStatus
        {
            get { return fpdv_gpuStatus; }
            set { SetPropertyValue<string>(nameof(pdv_gpuStatus), ref fpdv_gpuStatus, value); }
        }
        string fpdv_gpuVideoProcessor;
        public string pdv_gpuVideoProcessor
        {
            get { return fpdv_gpuVideoProcessor; }
            set { SetPropertyValue<string>(nameof(pdv_gpuVideoProcessor), ref fpdv_gpuVideoProcessor, value); }
        }
        byte fpdv_persTim;
        public byte pdv_persTim
        {
            get { return fpdv_persTim; }
            set { SetPropertyValue<byte>(nameof(pdv_persTim), ref fpdv_persTim, value); }
        }
        DateTime fpdv_pdvUpdRunVerDt;
        public DateTime pdv_pdvUpdRunVerDt
        {
            get { return fpdv_pdvUpdRunVerDt; }
            set { SetPropertyValue<DateTime>(nameof(pdv_pdvUpdRunVerDt), ref fpdv_pdvUpdRunVerDt, value); }
        }
        string fpdv_pdvUpdRunVer;
        [Size(20)]
        public string pdv_pdvUpdRunVer
        {
            get { return fpdv_pdvUpdRunVer; }
            set { SetPropertyValue<string>(nameof(pdv_pdvUpdRunVer), ref fpdv_pdvUpdRunVer, value); }
        }
        DateTime fpdv_pdvUpdNewVerDt;
        public DateTime pdv_pdvUpdNewVerDt
        {
            get { return fpdv_pdvUpdNewVerDt; }
            set { SetPropertyValue<DateTime>(nameof(pdv_pdvUpdNewVerDt), ref fpdv_pdvUpdNewVerDt, value); }
        }
        string fpdv_pdvUpdNewVer;
        [Size(20)]
        public string pdv_pdvUpdNewVer
        {
            get { return fpdv_pdvUpdNewVer; }
            set { SetPropertyValue<string>(nameof(pdv_pdvUpdNewVer), ref fpdv_pdvUpdNewVer, value); }
        }
        decimal fpdv_pdvUpdReady;
        public decimal pdv_pdvUpdReady
        {
            get { return fpdv_pdvUpdReady; }
            set { SetPropertyValue<decimal>(nameof(pdv_pdvUpdReady), ref fpdv_pdvUpdReady, value); }
        }
        tb_ator ffk_tb_ator;
        [Association(@"tb_pdvReferencestb_ator")]
        public tb_ator fk_tb_ator
        {
            get { return ffk_tb_ator; }
            set { SetPropertyValue<tb_ator>(nameof(fk_tb_ator), ref ffk_tb_ator, value); }
        }
        [Association(@"tb_clasCont2Referencestb_pdv")]
        public XPCollection<tb_clasCont2> tb_clasCont2s { get { return GetCollection<tb_clasCont2>(nameof(tb_clasCont2s)); } }
        [Association(@"tb_jornadaReferencestb_pdv")]
        public XPCollection<tb_jornada> tb_jornadas { get { return GetCollection<tb_jornada>(nameof(tb_jornadas)); } }
        [Association(@"tb_nfe_enviada_filialReferencestb_pdv")]
        public XPCollection<tb_nfe_enviada_filial> tb_nfe_enviada_filials { get { return GetCollection<tb_nfe_enviada_filial>(nameof(tb_nfe_enviada_filials)); } }
    }

}
