//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplicationPDV.bancoSQLite
{

    public partial class tb_produto : XPLiteObject
    {
        long fid_produto;
        [Key(AutoGenerate = true)]
        public long id_produto
        {
            get { return fid_produto; }
            set { SetPropertyValue<long>(nameof(id_produto), ref fid_produto, value); }
        }
        DateTime fpd_dtCri;
        public DateTime pd_dtCri
        {
            get { return fpd_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(pd_dtCri), ref fpd_dtCri, value); }
        }
        DateTime fpd_dtAlt;
        public DateTime pd_dtAlt
        {
            get { return fpd_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(pd_dtAlt), ref fpd_dtAlt, value); }
        }
        DateTime fpd_dtAcs;
        public DateTime pd_dtAcs
        {
            get { return fpd_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(pd_dtAcs), ref fpd_dtAcs, value); }
        }
        long fpd_desat;
        public long pd_desat
        {
            get { return fpd_desat; }
            set { SetPropertyValue<long>(nameof(pd_desat), ref fpd_desat, value); }
        }
        long fpd_genero;
        public long pd_genero
        {
            get { return fpd_genero; }
            set { SetPropertyValue<long>(nameof(pd_genero), ref fpd_genero, value); }
        }
        long fpd_unMedCom;
        public long pd_unMedCom
        {
            get { return fpd_unMedCom; }
            set { SetPropertyValue<long>(nameof(pd_unMedCom), ref fpd_unMedCom, value); }
        }
        long fpd_codRef;
        public long pd_codRef
        {
            get { return fpd_codRef; }
            set { SetPropertyValue<long>(nameof(pd_codRef), ref fpd_codRef, value); }
        }
        string fpd_codRefStr;
        [Size(SizeAttribute.Unlimited)]
        public string pd_codRefStr
        {
            get { return fpd_codRefStr; }
            set { SetPropertyValue<string>(nameof(pd_codRefStr), ref fpd_codRefStr, value); }
        }
        string fpd_barras;
        [Size(SizeAttribute.Unlimited)]
        public string pd_barras
        {
            get { return fpd_barras; }
            set { SetPropertyValue<string>(nameof(pd_barras), ref fpd_barras, value); }
        }
        string fpd_impRef;
        [Size(SizeAttribute.Unlimited)]
        public string pd_impRef
        {
            get { return fpd_impRef; }
            set { SetPropertyValue<string>(nameof(pd_impRef), ref fpd_impRef, value); }
        }
        long fpd_proTipo;
        public long pd_proTipo
        {
            get { return fpd_proTipo; }
            set { SetPropertyValue<long>(nameof(pd_proTipo), ref fpd_proTipo, value); }
        }
        long fpd_especie;
        public long pd_especie
        {
            get { return fpd_especie; }
            set { SetPropertyValue<long>(nameof(pd_especie), ref fpd_especie, value); }
        }
        decimal fpd_estTot;
        public decimal pd_estTot
        {
            get { return fpd_estTot; }
            set { SetPropertyValue<decimal>(nameof(pd_estTot), ref fpd_estTot, value); }
        }
        long fpd_invend;
        public long pd_invend
        {
            get { return fpd_invend; }
            set { SetPropertyValue<long>(nameof(pd_invend), ref fpd_invend, value); }
        }
        string fpd_descCurta;
        [Size(SizeAttribute.Unlimited)]
        public string pd_descCurta
        {
            get { return fpd_descCurta; }
            set { SetPropertyValue<string>(nameof(pd_descCurta), ref fpd_descCurta, value); }
        }
        string fpd_desc;
        [Size(SizeAttribute.Unlimited)]
        public string pd_desc
        {
            get { return fpd_desc; }
            set { SetPropertyValue<string>(nameof(pd_desc), ref fpd_desc, value); }
        }
        long fpd_fxEta;
        public long pd_fxEta
        {
            get { return fpd_fxEta; }
            set { SetPropertyValue<long>(nameof(pd_fxEta), ref fpd_fxEta, value); }
        }
        decimal fpd_vlrUnComBase;
        public decimal pd_vlrUnComBase
        {
            get { return fpd_vlrUnComBase; }
            set { SetPropertyValue<decimal>(nameof(pd_vlrUnComBase), ref fpd_vlrUnComBase, value); }
        }
        decimal fpd_cstUnComBase;
        public decimal pd_cstUnComBase
        {
            get { return fpd_cstUnComBase; }
            set { SetPropertyValue<decimal>(nameof(pd_cstUnComBase), ref fpd_cstUnComBase, value); }
        }
        decimal fpd_estMinBase;
        public decimal pd_estMinBase
        {
            get { return fpd_estMinBase; }
            set { SetPropertyValue<decimal>(nameof(pd_estMinBase), ref fpd_estMinBase, value); }
        }
        decimal fpd_estMaxBase;
        public decimal pd_estMaxBase
        {
            get { return fpd_estMaxBase; }
            set { SetPropertyValue<decimal>(nameof(pd_estMaxBase), ref fpd_estMaxBase, value); }
        }
        long fpd_nfeProdOrigem;
        public long pd_nfeProdOrigem
        {
            get { return fpd_nfeProdOrigem; }
            set { SetPropertyValue<long>(nameof(pd_nfeProdOrigem), ref fpd_nfeProdOrigem, value); }
        }
        long fpd_nfeCsosn;
        public long pd_nfeCsosn
        {
            get { return fpd_nfeCsosn; }
            set { SetPropertyValue<long>(nameof(pd_nfeCsosn), ref fpd_nfeCsosn, value); }
        }
        long fpd_vend;
        public long pd_vend
        {
            get { return fpd_vend; }
            set { SetPropertyValue<long>(nameof(pd_vend), ref fpd_vend, value); }
        }
        string fpd_tmpStr;
        [Size(SizeAttribute.Unlimited)]
        public string pd_tmpStr
        {
            get { return fpd_tmpStr; }
            set { SetPropertyValue<string>(nameof(pd_tmpStr), ref fpd_tmpStr, value); }
        }
        long fpd_ativo;
        public long pd_ativo
        {
            get { return fpd_ativo; }
            set { SetPropertyValue<long>(nameof(pd_ativo), ref fpd_ativo, value); }
        }
        long ffk_tb_Est;
        public long fk_tb_Est
        {
            get { return ffk_tb_Est; }
            set { SetPropertyValue<long>(nameof(fk_tb_Est), ref ffk_tb_Est, value); }
        }
        tb_rede ffk_tb_rede;
        [Association(@"tb_produtoReferencestb_rede")]
        public tb_rede fk_tb_rede
        {
            get { return ffk_tb_rede; }
            set { SetPropertyValue<tb_rede>(nameof(fk_tb_rede), ref ffk_tb_rede, value); }
        }
        long ffk_tb_Ncm;
        public long fk_tb_Ncm
        {
            get { return ffk_tb_Ncm; }
            set { SetPropertyValue<long>(nameof(fk_tb_Ncm), ref ffk_tb_Ncm, value); }
        }
        tb_ator ffk_tb_ator;
        [Association(@"tb_produtoReferencestb_ator")]
        public tb_ator fk_tb_ator
        {
            get { return ffk_tb_ator; }
            set { SetPropertyValue<tb_ator>(nameof(fk_tb_ator), ref ffk_tb_ator, value); }
        }
        long ffk_tb_ProRel;
        public long fk_tb_ProRel
        {
            get { return ffk_tb_ProRel; }
            set { SetPropertyValue<long>(nameof(fk_tb_ProRel), ref ffk_tb_ProRel, value); }
        }
        tb_marca_produto ffk_tb_marca_produto;
        [Association(@"tb_produtoReferencestb_marca_produto")]
        public tb_marca_produto fk_tb_marca_produto
        {
            get { return ffk_tb_marca_produto; }
            set { SetPropertyValue<tb_marca_produto>(nameof(fk_tb_marca_produto), ref ffk_tb_marca_produto, value); }
        }
        tb_subcategoria_produto ffk_tb_subcategoria_produto;
        [Association(@"tb_produtoReferencestb_subcategoria_produto")]
        public tb_subcategoria_produto fk_tb_subcategoria_produto
        {
            get { return ffk_tb_subcategoria_produto; }
            set { SetPropertyValue<tb_subcategoria_produto>(nameof(fk_tb_subcategoria_produto), ref ffk_tb_subcategoria_produto, value); }
        }
        tb_categoria_produto ffk_tb_categoria_produto;
        [Association(@"tb_produtoReferencestb_categoria_produto")]
        public tb_categoria_produto fk_tb_categoria_produto
        {
            get { return ffk_tb_categoria_produto; }
            set { SetPropertyValue<tb_categoria_produto>(nameof(fk_tb_categoria_produto), ref ffk_tb_categoria_produto, value); }
        }
        [Association(@"tb_produto_filialReferencestb_produto")]
        public XPCollection<tb_produto_filial> tb_produto_filials { get { return GetCollection<tb_produto_filial>(nameof(tb_produto_filials)); } }
        [Association(@"tb_relacao_produto_cadastro_XMLReferencestb_produto")]
        public XPCollection<tb_relacao_produto_cadastro_XML> tb_relacao_produto_cadastro_XMLs { get { return GetCollection<tb_relacao_produto_cadastro_XML>(nameof(tb_relacao_produto_cadastro_XMLs)); } }
    }

}
