//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplicationPDV.bancoSQLite
{

    public partial class tb_pais : XPLiteObject
    {
        long fid_pais;
        [Key(AutoGenerate = true)]
        public long id_pais
        {
            get { return fid_pais; }
            set { SetPropertyValue<long>(nameof(id_pais), ref fid_pais, value); }
        }
        decimal fps_desat;
        public decimal ps_desat
        {
            get { return fps_desat; }
            set { SetPropertyValue<decimal>(nameof(ps_desat), ref fps_desat, value); }
        }
        short fps_id;
        public short ps_id
        {
            get { return fps_id; }
            set { SetPropertyValue<short>(nameof(ps_id), ref fps_id, value); }
        }
        string fps_sigla;
        [Size(3)]
        public string ps_sigla
        {
            get { return fps_sigla; }
            set { SetPropertyValue<string>(nameof(ps_sigla), ref fps_sigla, value); }
        }
        string fps_nome;
        [Size(256)]
        public string ps_nome
        {
            get { return fps_nome; }
            set { SetPropertyValue<string>(nameof(ps_nome), ref fps_nome, value); }
        }
        decimal fps_canc;
        public decimal ps_canc
        {
            get { return fps_canc; }
            set { SetPropertyValue<decimal>(nameof(ps_canc), ref fps_canc, value); }
        }
        tb_unidade_monetaria ffk_tb_unidade_monetaria;
        [Association(@"tb_paisReferencestb_unidade_monetaria")]
        public tb_unidade_monetaria fk_tb_unidade_monetaria
        {
            get { return ffk_tb_unidade_monetaria; }
            set { SetPropertyValue<tb_unidade_monetaria>(nameof(fk_tb_unidade_monetaria), ref ffk_tb_unidade_monetaria, value); }
        }
        [Association(@"tb_regioes_brReferencestb_pais")]
        public XPCollection<tb_regioes_br> tb_regioes_brs { get { return GetCollection<tb_regioes_br>(nameof(tb_regioes_brs)); } }
    }

}
