//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplicationPDV.bancoSQLite
{

    public partial class tb_subcategoria_produto : XPLiteObject
    {
        long fid_subcategoria_produto;
        [Key(AutoGenerate = true)]
        public long id_subcategoria_produto
        {
            get { return fid_subcategoria_produto; }
            set { SetPropertyValue<long>(nameof(id_subcategoria_produto), ref fid_subcategoria_produto, value); }
        }
        byte fscp_nfePisCofinsReg;
        public byte scp_nfePisCofinsReg
        {
            get { return fscp_nfePisCofinsReg; }
            set { SetPropertyValue<byte>(nameof(scp_nfePisCofinsReg), ref fscp_nfePisCofinsReg, value); }
        }
        DateTime fscp_dtCri;
        public DateTime scp_dtCri
        {
            get { return fscp_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(scp_dtCri), ref fscp_dtCri, value); }
        }
        DateTime fscp_dtAlt;
        public DateTime scp_dtAlt
        {
            get { return fscp_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(scp_dtAlt), ref fscp_dtAlt, value); }
        }
        DateTime fscp_dtAcs;
        public DateTime scp_dtAcs
        {
            get { return fscp_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(scp_dtAcs), ref fscp_dtAcs, value); }
        }
        string fscp_desc;
        [Size(48)]
        public string scp_desc
        {
            get { return fscp_desc; }
            set { SetPropertyValue<string>(nameof(scp_desc), ref fscp_desc, value); }
        }
        decimal fscp_desat;
        public decimal scp_desat
        {
            get { return fscp_desat; }
            set { SetPropertyValue<decimal>(nameof(scp_desat), ref fscp_desat, value); }
        }
        string fscp_ncmNum;
        [Size(8)]
        public string scp_ncmNum
        {
            get { return fscp_ncmNum; }
            set { SetPropertyValue<string>(nameof(scp_ncmNum), ref fscp_ncmNum, value); }
        }
        short fscp_nfeCsosn;
        public short scp_nfeCsosn
        {
            get { return fscp_nfeCsosn; }
            set { SetPropertyValue<short>(nameof(scp_nfeCsosn), ref fscp_nfeCsosn, value); }
        }
        decimal fscp_descMax;
        public decimal scp_descMax
        {
            get { return fscp_descMax; }
            set { SetPropertyValue<decimal>(nameof(scp_descMax), ref fscp_descMax, value); }
        }
        tb_categoria_produto ffk_tb_categoria_produto;
        [Association(@"tb_subcategoria_produtoReferencestb_categoria_produto")]
        public tb_categoria_produto fk_tb_categoria_produto
        {
            get { return ffk_tb_categoria_produto; }
            set { SetPropertyValue<tb_categoria_produto>(nameof(fk_tb_categoria_produto), ref ffk_tb_categoria_produto, value); }
        }
        tb_ncm ffk_tb_Ncm;
        [Association(@"tb_subcategoria_produtoReferencestb_ncm")]
        public tb_ncm fk_tb_Ncm
        {
            get { return ffk_tb_Ncm; }
            set { SetPropertyValue<tb_ncm>(nameof(fk_tb_Ncm), ref ffk_tb_Ncm, value); }
        }
        [Association(@"tb_produtoReferencestb_subcategoria_produto")]
        public XPCollection<tb_produto> tb_produtos { get { return GetCollection<tb_produto>(nameof(tb_produtos)); } }
    }

}
