//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplicationPDV.bancoSQLite
{

    public partial class tb_sub_forma_pagamento : XPLiteObject
    {
        long fid_sub_forma_pagamento;
        [Key(AutoGenerate = true)]
        public long id_sub_forma_pagamento
        {
            get { return fid_sub_forma_pagamento; }
            set { SetPropertyValue<long>(nameof(id_sub_forma_pagamento), ref fid_sub_forma_pagamento, value); }
        }
        DateTime fsfp_dtCri;
        public DateTime sfp_dtCri
        {
            get { return fsfp_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(sfp_dtCri), ref fsfp_dtCri, value); }
        }
        DateTime fsfp_dtAlt;
        public DateTime sfp_dtAlt
        {
            get { return fsfp_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(sfp_dtAlt), ref fsfp_dtAlt, value); }
        }
        DateTime fsfp_dtAcs;
        public DateTime sfp_dtAcs
        {
            get { return fsfp_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(sfp_dtAcs), ref fsfp_dtAcs, value); }
        }
        decimal fsfp_desat;
        public decimal sfp_desat
        {
            get { return fsfp_desat; }
            set { SetPropertyValue<decimal>(nameof(sfp_desat), ref fsfp_desat, value); }
        }
        string fsfp_desc;
        [Size(60)]
        public string sfp_desc
        {
            get { return fsfp_desc; }
            set { SetPropertyValue<string>(nameof(sfp_desc), ref fsfp_desc, value); }
        }
        short fsfp_ordExib;
        public short sfp_ordExib
        {
            get { return fsfp_ordExib; }
            set { SetPropertyValue<short>(nameof(sfp_ordExib), ref fsfp_ordExib, value); }
        }
        char fsfp_atalhoTecl;
        public char sfp_atalhoTecl
        {
            get { return fsfp_atalhoTecl; }
            set { SetPropertyValue<char>(nameof(sfp_atalhoTecl), ref fsfp_atalhoTecl, value); }
        }
        short fsfp_intParc;
        public short sfp_intParc
        {
            get { return fsfp_intParc; }
            set { SetPropertyValue<short>(nameof(sfp_intParc), ref fsfp_intParc, value); }
        }
        byte fsfp_nfeTipoBand;
        public byte sfp_nfeTipoBand
        {
            get { return fsfp_nfeTipoBand; }
            set { SetPropertyValue<byte>(nameof(sfp_nfeTipoBand), ref fsfp_nfeTipoBand, value); }
        }
        tb_forma_pagamento ffk_tb_forma_pagamento;
        [Association(@"tb_sub_forma_pagamentoReferencestb_forma_pagamento")]
        public tb_forma_pagamento fk_tb_forma_pagamento
        {
            get { return ffk_tb_forma_pagamento; }
            set { SetPropertyValue<tb_forma_pagamento>(nameof(fk_tb_forma_pagamento), ref ffk_tb_forma_pagamento, value); }
        }
        [Association(@"tb_movimentacao_pagamentoReferencestb_sub_forma_pagamento")]
        public XPCollection<tb_movimentacao_pagamento> tb_movimentacao_pagamentos { get { return GetCollection<tb_movimentacao_pagamento>(nameof(tb_movimentacao_pagamentos)); } }
        [Association(@"tb_movimentacao_pagamento_parcelaReferencestb_sub_forma_pagamento")]
        public XPCollection<tb_movimentacao_pagamento_parcela> tb_movimentacao_pagamento_parcelas { get { return GetCollection<tb_movimentacao_pagamento_parcela>(nameof(tb_movimentacao_pagamento_parcelas)); } }
    }

}
