//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace App_TelasCompartilhadas.bancoSQLite
{

    public partial class tb_contExtSubGru : XPLiteObject
    {
        long fid_contExtSubGru;
        [Key(AutoGenerate = true)]
        public long id_contExtSubGru
        {
            get { return fid_contExtSubGru; }
            set { SetPropertyValue<long>(nameof(id_contExtSubGru), ref fid_contExtSubGru, value); }
        }
        decimal fcesg_deb;
        public decimal cesg_deb
        {
            get { return fcesg_deb; }
            set { SetPropertyValue<decimal>(nameof(cesg_deb), ref fcesg_deb, value); }
        }
        decimal fcesg_cred;
        public decimal cesg_cred
        {
            get { return fcesg_cred; }
            set { SetPropertyValue<decimal>(nameof(cesg_cred), ref fcesg_cred, value); }
        }
        DateTime fcesg_dtCri;
        public DateTime cesg_dtCri
        {
            get { return fcesg_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(cesg_dtCri), ref fcesg_dtCri, value); }
        }
        DateTime fcesg_dtAlt;
        public DateTime cesg_dtAlt
        {
            get { return fcesg_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(cesg_dtAlt), ref fcesg_dtAlt, value); }
        }
        DateTime fcesg_dtAcs;
        public DateTime cesg_dtAcs
        {
            get { return fcesg_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(cesg_dtAcs), ref fcesg_dtAcs, value); }
        }
        decimal fcesg_canc;
        public decimal cesg_canc
        {
            get { return fcesg_canc; }
            set { SetPropertyValue<decimal>(nameof(cesg_canc), ref fcesg_canc, value); }
        }
        decimal fcesg_conc;
        public decimal cesg_conc
        {
            get { return fcesg_conc; }
            set { SetPropertyValue<decimal>(nameof(cesg_conc), ref fcesg_conc, value); }
        }
        tb_contSubGru ffk_tb_contSubGru;
        [Association(@"tb_contExtSubGruReferencestb_contSubGru")]
        public tb_contSubGru fk_tb_contSubGru
        {
            get { return ffk_tb_contSubGru; }
            set { SetPropertyValue<tb_contSubGru>(nameof(fk_tb_contSubGru), ref ffk_tb_contSubGru, value); }
        }
    }

}
