//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace App_TelasCompartilhadas.bancoSQLite
{

    public partial class tb_codigo_produto : XPLiteObject
    {
        long fid_codigo_produto;
        [Key]
        public long id_codigo_produto
        {
            get { return fid_codigo_produto; }
            set { SetPropertyValue<long>(nameof(id_codigo_produto), ref fid_codigo_produto, value); }
        }
        decimal fcp_desat;
        public decimal cp_desat
        {
            get { return fcp_desat; }
            set { SetPropertyValue<decimal>(nameof(cp_desat), ref fcp_desat, value); }
        }
        DateTime fcp_dtCri;
        public DateTime cp_dtCri
        {
            get { return fcp_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(cp_dtCri), ref fcp_dtCri, value); }
        }
        DateTime fcp_dtAlt;
        public DateTime cp_dtAlt
        {
            get { return fcp_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(cp_dtAlt), ref fcp_dtAlt, value); }
        }
        DateTime fcp_dtAcs;
        public DateTime cp_dtAcs
        {
            get { return fcp_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(cp_dtAcs), ref fcp_dtAcs, value); }
        }
        string fcp_barras;
        [Size(14)]
        public string cp_barras
        {
            get { return fcp_barras; }
            set { SetPropertyValue<string>(nameof(cp_barras), ref fcp_barras, value); }
        }
        tb_produto ffk_tb_produto;
        [Association(@"tb_codigo_produtoReferencestb_produto")]
        public tb_produto fk_tb_produto
        {
            get { return ffk_tb_produto; }
            set { SetPropertyValue<tb_produto>(nameof(fk_tb_produto), ref ffk_tb_produto, value); }
        }
    }

}
