//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace App_TelasCompartilhadas.bancoSQLite
{

    public partial class tb_clasCont2 : XPLiteObject
    {
        long fid_clasCont2;
        [Key(AutoGenerate = true)]
        public long id_clasCont2
        {
            get { return fid_clasCont2; }
            set { SetPropertyValue<long>(nameof(id_clasCont2), ref fid_clasCont2, value); }
        }
        long fcc2_clasCont1;
        public long cc2_clasCont1
        {
            get { return fcc2_clasCont1; }
            set { SetPropertyValue<long>(nameof(cc2_clasCont1), ref fcc2_clasCont1, value); }
        }
        DateTime fcc2_dtCri;
        public DateTime cc2_dtCri
        {
            get { return fcc2_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(cc2_dtCri), ref fcc2_dtCri, value); }
        }
        DateTime fcc2_dtAlt;
        public DateTime cc2_dtAlt
        {
            get { return fcc2_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(cc2_dtAlt), ref fcc2_dtAlt, value); }
        }
        DateTime fcc2_dtAcs;
        public DateTime cc2_dtAcs
        {
            get { return fcc2_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(cc2_dtAcs), ref fcc2_dtAcs, value); }
        }
        decimal fcc2_desat;
        public decimal cc2_desat
        {
            get { return fcc2_desat; }
            set { SetPropertyValue<decimal>(nameof(cc2_desat), ref fcc2_desat, value); }
        }
        string fcc2_desc;
        [Size(60)]
        public string cc2_desc
        {
            get { return fcc2_desc; }
            set { SetPropertyValue<string>(nameof(cc2_desc), ref fcc2_desc, value); }
        }
        tb_pdv ffk_tb_pdv;
        [Association(@"tb_clasCont2Referencestb_pdv")]
        public tb_pdv fk_tb_pdv
        {
            get { return ffk_tb_pdv; }
            set { SetPropertyValue<tb_pdv>(nameof(fk_tb_pdv), ref ffk_tb_pdv, value); }
        }
        [Association(@"tb_movimentacaoReferencestb_clasCont2")]
        public XPCollection<tb_movimentacao> tb_movimentacaos { get { return GetCollection<tb_movimentacao>(nameof(tb_movimentacaos)); } }
    }

}
