//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace App_TelasCompartilhadas.bancoSQLite
{

    public partial class tb_cont : XPLiteObject
    {
        long fid_cont;
        [Key(AutoGenerate = true)]
        public long id_cont
        {
            get { return fid_cont; }
            set { SetPropertyValue<long>(nameof(id_cont), ref fid_cont, value); }
        }
        string fct_desc;
        [Size(60)]
        public string ct_desc
        {
            get { return fct_desc; }
            set { SetPropertyValue<string>(nameof(ct_desc), ref fct_desc, value); }
        }
        decimal fct_saldo;
        public decimal ct_saldo
        {
            get { return fct_saldo; }
            set { SetPropertyValue<decimal>(nameof(ct_saldo), ref fct_saldo, value); }
        }
        DateTime fct_dtCri;
        public DateTime ct_dtCri
        {
            get { return fct_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(ct_dtCri), ref fct_dtCri, value); }
        }
        DateTime fct_dAlt;
        public DateTime ct_dAlt
        {
            get { return fct_dAlt; }
            set { SetPropertyValue<DateTime>(nameof(ct_dAlt), ref fct_dAlt, value); }
        }
        DateTime fct_dtAcs;
        public DateTime ct_dtAcs
        {
            get { return fct_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(ct_dtAcs), ref fct_dtAcs, value); }
        }
        decimal fct_canc;
        public decimal ct_canc
        {
            get { return fct_canc; }
            set { SetPropertyValue<decimal>(nameof(ct_canc), ref fct_canc, value); }
        }
        decimal fct_conc;
        public decimal ct_conc
        {
            get { return fct_conc; }
            set { SetPropertyValue<decimal>(nameof(ct_conc), ref fct_conc, value); }
        }
        tb_ator ffk_tb_ator;
        [Association(@"tb_contReferencestb_ator")]
        public tb_ator fk_tb_ator
        {
            get { return ffk_tb_ator; }
            set { SetPropertyValue<tb_ator>(nameof(fk_tb_ator), ref ffk_tb_ator, value); }
        }
        tb_contSubGru ffk_tb_contSubGru;
        [Association(@"tb_contReferencestb_contSubGru")]
        public tb_contSubGru fk_tb_contSubGru
        {
            get { return ffk_tb_contSubGru; }
            set { SetPropertyValue<tb_contSubGru>(nameof(fk_tb_contSubGru), ref ffk_tb_contSubGru, value); }
        }
        [Association(@"tb_contExtReferencestb_cont")]
        public XPCollection<tb_contExt> tb_contExts { get { return GetCollection<tb_contExt>(nameof(tb_contExts)); } }
    }

}
