//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace App_TelasCompartilhadas.bancoSQLite
{

    public partial class tb_contSec : XPLiteObject
    {
        long fid_contSec;
        [Key(AutoGenerate = true)]
        public long id_contSec
        {
            get { return fid_contSec; }
            set { SetPropertyValue<long>(nameof(id_contSec), ref fid_contSec, value); }
        }
        DateTime fcs_dtCri;
        public DateTime cs_dtCri
        {
            get { return fcs_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(cs_dtCri), ref fcs_dtCri, value); }
        }
        DateTime fcs_dtAlt;
        public DateTime cs_dtAlt
        {
            get { return fcs_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(cs_dtAlt), ref fcs_dtAlt, value); }
        }
        DateTime fcs_dtAcs;
        public DateTime cs_dtAcs
        {
            get { return fcs_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(cs_dtAcs), ref fcs_dtAcs, value); }
        }
        string fcs_desc;
        [Size(60)]
        public string cs_desc
        {
            get { return fcs_desc; }
            set { SetPropertyValue<string>(nameof(cs_desc), ref fcs_desc, value); }
        }
        decimal fcs_canc;
        public decimal cs_canc
        {
            get { return fcs_canc; }
            set { SetPropertyValue<decimal>(nameof(cs_canc), ref fcs_canc, value); }
        }
        decimal fcs_conc;
        public decimal cs_conc
        {
            get { return fcs_conc; }
            set { SetPropertyValue<decimal>(nameof(cs_conc), ref fcs_conc, value); }
        }
        [Association(@"tb_contExtSecReferencestb_contSec")]
        public XPCollection<tb_contExtSec> tb_contExtSecs { get { return GetCollection<tb_contExtSec>(nameof(tb_contExtSecs)); } }
    }

}
