//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace App_TelasCompartilhadas.bancoSQLite
{

    public partial class tb_estados_br : XPLiteObject
    {
        long fid_estados_br;
        [Key(AutoGenerate = true)]
        public long id_estados_br
        {
            get { return fid_estados_br; }
            set { SetPropertyValue<long>(nameof(id_estados_br), ref fid_estados_br, value); }
        }
        decimal feb_desat;
        public decimal eb_desat
        {
            get { return feb_desat; }
            set { SetPropertyValue<decimal>(nameof(eb_desat), ref feb_desat, value); }
        }
        byte feb_id;
        public byte eb_id
        {
            get { return feb_id; }
            set { SetPropertyValue<byte>(nameof(eb_id), ref feb_id, value); }
        }
        string feb_sigla;
        [Size(2)]
        public string eb_sigla
        {
            get { return feb_sigla; }
            set { SetPropertyValue<string>(nameof(eb_sigla), ref feb_sigla, value); }
        }
        string feb_nome;
        [Size(20)]
        public string eb_nome
        {
            get { return feb_nome; }
            set { SetPropertyValue<string>(nameof(eb_nome), ref feb_nome, value); }
        }
        tb_regioes_br ffk_tb_regioes_br;
        [Association(@"tb_estados_brReferencestb_regioes_br")]
        public tb_regioes_br fk_tb_regioes_br
        {
            get { return ffk_tb_regioes_br; }
            set { SetPropertyValue<tb_regioes_br>(nameof(fk_tb_regioes_br), ref ffk_tb_regioes_br, value); }
        }
        [Association(@"tb_atorReferencestb_estados_br")]
        public XPCollection<tb_ator> tb_ators { get { return GetCollection<tb_ator>(nameof(tb_ators)); } }
        [Association(@"tb_municipioReferencestb_estados_br")]
        public XPCollection<tb_municipio> tb_municipios { get { return GetCollection<tb_municipio>(nameof(tb_municipios)); } }
    }

}
