//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace App_TelasCompartilhadas.bancoSQLite
{

    public partial class tb_movimentacao_pagamento_parcela : XPLiteObject
    {
        long fid_movimentacao_pagamento_parcela;
        [Key]
        public long id_movimentacao_pagamento_parcela
        {
            get { return fid_movimentacao_pagamento_parcela; }
            set { SetPropertyValue<long>(nameof(id_movimentacao_pagamento_parcela), ref fid_movimentacao_pagamento_parcela, value); }
        }
        DateTime fmpp_dtCri;
        public DateTime mpp_dtCri
        {
            get { return fmpp_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(mpp_dtCri), ref fmpp_dtCri, value); }
        }
        DateTime fmpp_dtAlt;
        public DateTime mpp_dtAlt
        {
            get { return fmpp_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(mpp_dtAlt), ref fmpp_dtAlt, value); }
        }
        DateTime fmpp_dtAcs;
        public DateTime mpp_dtAcs
        {
            get { return fmpp_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(mpp_dtAcs), ref fmpp_dtAcs, value); }
        }
        short fmpp_numParc;
        public short mpp_numParc
        {
            get { return fmpp_numParc; }
            set { SetPropertyValue<short>(nameof(mpp_numParc), ref fmpp_numParc, value); }
        }
        short fmpp_qtdParc;
        public short mpp_qtdParc
        {
            get { return fmpp_qtdParc; }
            set { SetPropertyValue<short>(nameof(mpp_qtdParc), ref fmpp_qtdParc, value); }
        }
        decimal fmpp_vlrCli;
        public decimal mpp_vlrCli
        {
            get { return fmpp_vlrCli; }
            set { SetPropertyValue<decimal>(nameof(mpp_vlrCli), ref fmpp_vlrCli, value); }
        }
        decimal fmpp_taxaParc;
        public decimal mpp_taxaParc
        {
            get { return fmpp_taxaParc; }
            set { SetPropertyValue<decimal>(nameof(mpp_taxaParc), ref fmpp_taxaParc, value); }
        }
        decimal fmpp_vlrRec;
        public decimal mpp_vlrRec
        {
            get { return fmpp_vlrRec; }
            set { SetPropertyValue<decimal>(nameof(mpp_vlrRec), ref fmpp_vlrRec, value); }
        }
        DateTime fmpp_dtVenc;
        public DateTime mpp_dtVenc
        {
            get { return fmpp_dtVenc; }
            set { SetPropertyValue<DateTime>(nameof(mpp_dtVenc), ref fmpp_dtVenc, value); }
        }
        decimal fmpp_canc;
        public decimal mpp_canc
        {
            get { return fmpp_canc; }
            set { SetPropertyValue<decimal>(nameof(mpp_canc), ref fmpp_canc, value); }
        }
        tb_movimentacao_pagamento ffk_tb_movimentacao_pagamento;
        [Association(@"tb_movimentacao_pagamento_parcelaReferencestb_movimentacao_pagamento")]
        public tb_movimentacao_pagamento fk_tb_movimentacao_pagamento
        {
            get { return ffk_tb_movimentacao_pagamento; }
            set { SetPropertyValue<tb_movimentacao_pagamento>(nameof(fk_tb_movimentacao_pagamento), ref ffk_tb_movimentacao_pagamento, value); }
        }
        tb_sub_forma_pagamento ffk_tb_sub_forma_pagamento;
        [Association(@"tb_movimentacao_pagamento_parcelaReferencestb_sub_forma_pagamento")]
        public tb_sub_forma_pagamento fk_tb_sub_forma_pagamento
        {
            get { return ffk_tb_sub_forma_pagamento; }
            set { SetPropertyValue<tb_sub_forma_pagamento>(nameof(fk_tb_sub_forma_pagamento), ref ffk_tb_sub_forma_pagamento, value); }
        }
    }

}
