//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace App_TelasCompartilhadas.bancoSQLite
{

    public partial class tb_marca_produto : XPLiteObject
    {
        long fid_marca_produto;
        [Key]
        public long id_marca_produto
        {
            get { return fid_marca_produto; }
            set { SetPropertyValue<long>(nameof(id_marca_produto), ref fid_marca_produto, value); }
        }
        DateTime fmp_dtCri;
        public DateTime mp_dtCri
        {
            get { return fmp_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(mp_dtCri), ref fmp_dtCri, value); }
        }
        DateTime fmp_dtAlt;
        public DateTime mp_dtAlt
        {
            get { return fmp_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(mp_dtAlt), ref fmp_dtAlt, value); }
        }
        DateTime fmp_dtAcs;
        public DateTime mp_dtAcs
        {
            get { return fmp_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(mp_dtAcs), ref fmp_dtAcs, value); }
        }
        long fmp_desat;
        public long mp_desat
        {
            get { return fmp_desat; }
            set { SetPropertyValue<long>(nameof(mp_desat), ref fmp_desat, value); }
        }
        string fmp_desc;
        [Size(48)]
        public string mp_desc
        {
            get { return fmp_desc; }
            set { SetPropertyValue<string>(nameof(mp_desc), ref fmp_desc, value); }
        }
        tb_rede ffk_tb_rede;
        [Association(@"tb_marca_produtoReferencestb_rede")]
        public tb_rede fk_tb_rede
        {
            get { return ffk_tb_rede; }
            set { SetPropertyValue<tb_rede>(nameof(fk_tb_rede), ref ffk_tb_rede, value); }
        }
        [Association(@"tb_estReferencestb_marca_produto")]
        public XPCollection<tb_est> tb_ests { get { return GetCollection<tb_est>(nameof(tb_ests)); } }
        [Association(@"tb_produtoReferencestb_marca_produto")]
        public XPCollection<tb_produto> tb_produtos { get { return GetCollection<tb_produto>(nameof(tb_produtos)); } }
    }

}
