//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace App_TelasCompartilhadas.bancoSQLite
{

    public partial class tb_ncm : XPLiteObject
    {
        long fid_ncm;
        [Key]
        public long id_ncm
        {
            get { return fid_ncm; }
            set { SetPropertyValue<long>(nameof(id_ncm), ref fid_ncm, value); }
        }
        DateTime fnc_dtCri;
        public DateTime nc_dtCri
        {
            get { return fnc_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(nc_dtCri), ref fnc_dtCri, value); }
        }
        DateTime fnc_dtAlt;
        public DateTime nc_dtAlt
        {
            get { return fnc_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(nc_dtAlt), ref fnc_dtAlt, value); }
        }
        DateTime fnc_dtAcs;
        public DateTime nc_dtAcs
        {
            get { return fnc_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(nc_dtAcs), ref fnc_dtAcs, value); }
        }
        decimal fnc_desat;
        public decimal nc_desat
        {
            get { return fnc_desat; }
            set { SetPropertyValue<decimal>(nameof(nc_desat), ref fnc_desat, value); }
        }
        string fnc_anoDoAto;
        [Size(10)]
        public string nc_anoDoAto
        {
            get { return fnc_anoDoAto; }
            set { SetPropertyValue<string>(nameof(nc_anoDoAto), ref fnc_anoDoAto, value); }
        }
        long fnc_numAto;
        public long nc_numAto
        {
            get { return fnc_numAto; }
            set { SetPropertyValue<long>(nameof(nc_numAto), ref fnc_numAto, value); }
        }
        long fnc_parentOid;
        public long nc_parentOid
        {
            get { return fnc_parentOid; }
            set { SetPropertyValue<long>(nameof(nc_parentOid), ref fnc_parentOid, value); }
        }
        string fnc_rootNcm;
        [Size(2)]
        public string nc_rootNcm
        {
            get { return fnc_rootNcm; }
            set { SetPropertyValue<string>(nameof(nc_rootNcm), ref fnc_rootNcm, value); }
        }
        string fnc_ncmBase;
        [Size(8)]
        public string nc_ncmBase
        {
            get { return fnc_ncmBase; }
            set { SetPropertyValue<string>(nameof(nc_ncmBase), ref fnc_ncmBase, value); }
        }
        string fnc_ncmFull;
        [Size(8)]
        public string nc_ncmFull
        {
            get { return fnc_ncmFull; }
            set { SetPropertyValue<string>(nameof(nc_ncmFull), ref fnc_ncmFull, value); }
        }
        string fnc_desc;
        [Size(2048)]
        public string nc_desc
        {
            get { return fnc_desc; }
            set { SetPropertyValue<string>(nameof(nc_desc), ref fnc_desc, value); }
        }
        DateTime fnc_dtIni;
        public DateTime nc_dtIni
        {
            get { return fnc_dtIni; }
            set { SetPropertyValue<DateTime>(nameof(nc_dtIni), ref fnc_dtIni, value); }
        }
        DateTime fnc_dtFim;
        public DateTime nc_dtFim
        {
            get { return fnc_dtFim; }
            set { SetPropertyValue<DateTime>(nameof(nc_dtFim), ref fnc_dtFim, value); }
        }
        [Association(@"tb_produtoReferencestb_ncm")]
        public XPCollection<tb_produto> tb_produtos { get { return GetCollection<tb_produto>(nameof(tb_produtos)); } }
        [Association(@"tb_subcategoria_produtoReferencestb_ncm")]
        public XPCollection<tb_subcategoria_produto> tb_subcategoria_produtos { get { return GetCollection<tb_subcategoria_produto>(nameof(tb_subcategoria_produtos)); } }
    }

}
