//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace App_TelasCompartilhadas.bancoSQLite
{

    public partial class tb_relacao_produto_cadastro_XML : XPLiteObject
    {
        long fid_relacao_produto_cadastro_XML;
        [Key(AutoGenerate = true)]
        public long id_relacao_produto_cadastro_XML
        {
            get { return fid_relacao_produto_cadastro_XML; }
            set { SetPropertyValue<long>(nameof(id_relacao_produto_cadastro_XML), ref fid_relacao_produto_cadastro_XML, value); }
        }
        long frpc_codRef;
        public long rpc_codRef
        {
            get { return frpc_codRef; }
            set { SetPropertyValue<long>(nameof(rpc_codRef), ref frpc_codRef, value); }
        }
        string frpc_desc;
        [Size(48)]
        public string rpc_desc
        {
            get { return frpc_desc; }
            set { SetPropertyValue<string>(nameof(rpc_desc), ref frpc_desc, value); }
        }
        string frpc_cnpj_fornecedor;
        [Size(18)]
        public string rpc_cnpj_fornecedor
        {
            get { return frpc_cnpj_fornecedor; }
            set { SetPropertyValue<string>(nameof(rpc_cnpj_fornecedor), ref frpc_cnpj_fornecedor, value); }
        }
        DateTime frpc_dtCri;
        public DateTime rpc_dtCri
        {
            get { return frpc_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(rpc_dtCri), ref frpc_dtCri, value); }
        }
        DateTime frpc_dtAlt;
        public DateTime rpc_dtAlt
        {
            get { return frpc_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(rpc_dtAlt), ref frpc_dtAlt, value); }
        }
        DateTime frpc_dtAcs;
        public DateTime rpc_dtAcs
        {
            get { return frpc_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(rpc_dtAcs), ref frpc_dtAcs, value); }
        }
        tb_produto ffk_tb_produto;
        [Association(@"tb_relacao_produto_cadastro_XMLReferencestb_produto")]
        public tb_produto fk_tb_produto
        {
            get { return ffk_tb_produto; }
            set { SetPropertyValue<tb_produto>(nameof(fk_tb_produto), ref ffk_tb_produto, value); }
        }
        tb_produto_filial ffk_tb_produto_filial;
        [Association(@"tb_relacao_produto_cadastro_XMLReferencestb_produto_filial")]
        public tb_produto_filial fk_tb_produto_filial
        {
            get { return ffk_tb_produto_filial; }
            set { SetPropertyValue<tb_produto_filial>(nameof(fk_tb_produto_filial), ref ffk_tb_produto_filial, value); }
        }
        tb_ator ffk_tb_ator;
        [Association(@"tb_relacao_produto_cadastro_XMLReferencestb_ator")]
        public tb_ator fk_tb_ator
        {
            get { return ffk_tb_ator; }
            set { SetPropertyValue<tb_ator>(nameof(fk_tb_ator), ref ffk_tb_ator, value); }
        }
        [Association(@"tb_produtoReferencestb_relacao_produto_cadastro_XML")]
        public XPCollection<tb_produto> tb_produtos { get { return GetCollection<tb_produto>(nameof(tb_produtos)); } }
    }

}
