//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace App_TelasCompartilhadas.bancoSQLite
{

    public partial class tb_rede : XPLiteObject
    {
        long fid_rede;
        [Key]
        public long id_rede
        {
            get { return fid_rede; }
            set { SetPropertyValue<long>(nameof(id_rede), ref fid_rede, value); }
        }
        DateTime fre_dtCri;
        public DateTime re_dtCri
        {
            get { return fre_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(re_dtCri), ref fre_dtCri, value); }
        }
        DateTime fre_dtAlt;
        public DateTime re_dtAlt
        {
            get { return fre_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(re_dtAlt), ref fre_dtAlt, value); }
        }
        DateTime fre_dtAcs;
        public DateTime re_dtAcs
        {
            get { return fre_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(re_dtAcs), ref fre_dtAcs, value); }
        }
        string fre_desc;
        [Size(60)]
        public string re_desc
        {
            get { return fre_desc; }
            set { SetPropertyValue<string>(nameof(re_desc), ref fre_desc, value); }
        }
        decimal fre_desat;
        public decimal re_desat
        {
            get { return fre_desat; }
            set { SetPropertyValue<decimal>(nameof(re_desat), ref fre_desat, value); }
        }
        decimal fre_desatSinc;
        public decimal re_desatSinc
        {
            get { return fre_desatSinc; }
            set { SetPropertyValue<decimal>(nameof(re_desatSinc), ref fre_desatSinc, value); }
        }
        byte fre_PersTim;
        public byte re_PersTim
        {
            get { return fre_PersTim; }
            set { SetPropertyValue<byte>(nameof(re_PersTim), ref fre_PersTim, value); }
        }
        [Association(@"tb_clasCont1Referencestb_rede")]
        public XPCollection<tb_clasCont1> tb_clasCont1s { get { return GetCollection<tb_clasCont1>(nameof(tb_clasCont1s)); } }
        [Association(@"tb_forma_pagamentoReferencestb_rede")]
        public XPCollection<tb_forma_pagamento> tb_forma_pagamentos { get { return GetCollection<tb_forma_pagamento>(nameof(tb_forma_pagamentos)); } }
        [Association(@"tb_marca_produtoReferencestb_rede")]
        public XPCollection<tb_marca_produto> tb_marca_produtos { get { return GetCollection<tb_marca_produto>(nameof(tb_marca_produtos)); } }
        [Association(@"tb_matrizReferencestb_rede")]
        public XPCollection<tb_matriz> tb_matrizs { get { return GetCollection<tb_matriz>(nameof(tb_matrizs)); } }
        [Association(@"tb_produtoReferencestb_rede")]
        public XPCollection<tb_produto> tb_produtos { get { return GetCollection<tb_produto>(nameof(tb_produtos)); } }
        [Association(@"tb_secao_produtoReferencestb_rede")]
        public XPCollection<tb_secao_produto> tb_secao_produtos { get { return GetCollection<tb_secao_produto>(nameof(tb_secao_produtos)); } }
    }

}
