//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace App_TelasCompartilhadas.bancoSQLite
{

    public partial class tb_resEventoNFe : XPLiteObject
    {
        long fid_resEventoNFe;
        [Key(AutoGenerate = true)]
        public long id_resEventoNFe
        {
            get { return fid_resEventoNFe; }
            set { SetPropertyValue<long>(nameof(id_resEventoNFe), ref fid_resEventoNFe, value); }
        }
        string fref_cnpj;
        [Size(18)]
        public string ref_cnpj
        {
            get { return fref_cnpj; }
            set { SetPropertyValue<string>(nameof(ref_cnpj), ref fref_cnpj, value); }
        }
        string fref_cpf;
        [Size(14)]
        public string ref_cpf
        {
            get { return fref_cpf; }
            set { SetPropertyValue<string>(nameof(ref_cpf), ref fref_cpf, value); }
        }
        string fref_nfeChave;
        [Size(50)]
        public string ref_nfeChave
        {
            get { return fref_nfeChave; }
            set { SetPropertyValue<string>(nameof(ref_nfeChave), ref fref_nfeChave, value); }
        }
        decimal fref_nfeVersao;
        public decimal ref_nfeVersao
        {
            get { return fref_nfeVersao; }
            set { SetPropertyValue<decimal>(nameof(ref_nfeVersao), ref fref_nfeVersao, value); }
        }
        DateTime fref_dtCri;
        public DateTime ref_dtCri
        {
            get { return fref_dtCri; }
            set { SetPropertyValue<DateTime>(nameof(ref_dtCri), ref fref_dtCri, value); }
        }
        DateTime fref_dtAlt;
        public DateTime ref_dtAlt
        {
            get { return fref_dtAlt; }
            set { SetPropertyValue<DateTime>(nameof(ref_dtAlt), ref fref_dtAlt, value); }
        }
        DateTime fref_dtAcs;
        public DateTime ref_dtAcs
        {
            get { return fref_dtAcs; }
            set { SetPropertyValue<DateTime>(nameof(ref_dtAcs), ref fref_dtAcs, value); }
        }
        long fref_nsu;
        public long ref_nsu
        {
            get { return fref_nsu; }
            set { SetPropertyValue<long>(nameof(ref_nsu), ref fref_nsu, value); }
        }
        short fref_codOrg;
        public short ref_codOrg
        {
            get { return fref_codOrg; }
            set { SetPropertyValue<short>(nameof(ref_codOrg), ref fref_codOrg, value); }
        }
        long fref_sTpEvt;
        public long ref_sTpEvt
        {
            get { return fref_sTpEvt; }
            set { SetPropertyValue<long>(nameof(ref_sTpEvt), ref fref_sTpEvt, value); }
        }
        short fref_numSeqEvt;
        public short ref_numSeqEvt
        {
            get { return fref_numSeqEvt; }
            set { SetPropertyValue<short>(nameof(ref_numSeqEvt), ref fref_numSeqEvt, value); }
        }
        string fref_descEvt;
        [Size(60)]
        public string ref_descEvt
        {
            get { return fref_descEvt; }
            set { SetPropertyValue<string>(nameof(ref_descEvt), ref fref_descEvt, value); }
        }
        string fref_nfeNumProtEvt;
        [Size(15)]
        public string ref_nfeNumProtEvt
        {
            get { return fref_nfeNumProtEvt; }
            set { SetPropertyValue<string>(nameof(ref_nfeNumProtEvt), ref fref_nfeNumProtEvt, value); }
        }
        tb_ator ffk_tb_ator;
        [Association(@"tb_resEventoNFeReferencestb_ator")]
        public tb_ator fk_tb_ator
        {
            get { return ffk_tb_ator; }
            set { SetPropertyValue<tb_ator>(nameof(fk_tb_ator), ref ffk_tb_ator, value); }
        }
    }

}
